/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_ItemGroup */

#ifndef _Included_com_scriptographer_adm_ItemGroup
#define _Included_com_scriptographer_adm_ItemGroup
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_ItemGroup_POPUP_MENU_RIGHT
#define com_scriptographer_adm_ItemGroup_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_ItemGroup_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_ItemGroup_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_ItemGroup_POPUP_MENU_ROUND
#define com_scriptographer_adm_ItemGroup_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_ItemGroup_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_ItemGroup_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_ItemGroup_SPINEDIT_VERTICAL
#define com_scriptographer_adm_ItemGroup_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_ItemGroup_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_ItemGroup_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_ItemGroup_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_ItemGroup_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_ItemGroup_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_ItemGroup_SPINEDIT_POPUP_HORIZONTAL 4L
/*
 * Class:     com_scriptographer_adm_ItemGroup
 * Method:    addItem
 * Signature: (Lcom/scriptographer/adm/Item;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ItemGroup_addItem
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
