/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_DocumentList */

#ifndef _Included_com_scriptographer_ai_DocumentList
#define _Included_com_scriptographer_ai_DocumentList
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: documents */
/* Inaccessible static: documentList */
/*
 * Class:     com_scriptographer_ai_DocumentList
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_DocumentList_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_DocumentList
 * Method:    getDocumentHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_DocumentList_getDocumentHandle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
