/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_ArtSet */

#ifndef _Included_com_scriptographer_ai_ArtSet
#define _Included_com_scriptographer_ai_ArtSet
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: ATTR_SELECTED */
/* Inaccessible static: ATTR_LOCKED */
/* Inaccessible static: ATTR_HIDDEN */
/* Inaccessible static: ATTR_FULLY_SELECTED */
/* Inaccessible static: ATTR_EXPANDED */
/* Inaccessible static: ATTR_TARGETED */
/* Inaccessible static: ATTR_IS_CLIPMASK */
/* Inaccessible static: ATTR_IS_TEXTWRAP */
/* Inaccessible static: ATTR_SELECTED_TOPLEVEL_GROUPS */
/* Inaccessible static: ATTR_SELECTED_LAYERS */
/* Inaccessible static: ATTR_SELECTED_TOPLEVEL_WITH_PAINT */
/* Inaccessible static: ATTR_HAS_SIMPLE_STYLE */
/* Inaccessible static: ATTR_HAS_ACTIVE_STYLE */
/* Inaccessible static: ATTR_PART_OF_COMPOUND */
/* Inaccessible static: ATTR_STYLE_IS_DIRTY */
/*
 * Class:     com_scriptographer_ai_ArtSet
 * Method:    nativeGetSelected
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_ArtSet_nativeGetSelected
  (JNIEnv *, jclass);

/*
 * Class:     com_scriptographer_ai_ArtSet
 * Method:    nativeGetMatching
 * Signature: (Ljava/lang/Class;Ljava/util/Map;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_ArtSet_nativeGetMatching
  (JNIEnv *, jclass, jclass, jobject);

/*
 * Class:     com_scriptographer_ai_ArtSet
 * Method:    nativeGetLayer
 * Signature: (I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_ArtSet_nativeGetLayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scriptographer_ai_ArtSet
 * Method:    nativeInvert
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_ArtSet_nativeInvert
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
