/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_ValueItem */

#ifndef _Included_com_scriptographer_adm_ValueItem
#define _Included_com_scriptographer_adm_ValueItem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_ValueItem_POPUP_MENU_RIGHT
#define com_scriptographer_adm_ValueItem_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_ValueItem_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_ValueItem_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_ValueItem_POPUP_MENU_ROUND
#define com_scriptographer_adm_ValueItem_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_ValueItem_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_ValueItem_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_ValueItem_SPINEDIT_VERTICAL
#define com_scriptographer_adm_ValueItem_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_ValueItem_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_ValueItem_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_ValueItem_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_ValueItem_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_ValueItem_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_ValueItem_SPINEDIT_POPUP_HORIZONTAL 4L
/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    getValueRange
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_scriptographer_adm_ValueItem_getValueRange
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    setValueRange
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ValueItem_setValueRange
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    getPrecision
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_ValueItem_getPrecision
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    setPrecision
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ValueItem_setPrecision
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    getBooleanValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_ValueItem_getBooleanValue
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    setBooleanValue
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ValueItem_setBooleanValue
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    getFloatValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_scriptographer_adm_ValueItem_getFloatValue
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_ValueItem
 * Method:    setFloatValue
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ValueItem_setFloatValue
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
