/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Document */

#ifndef _Included_com_scriptographer_ai_Document
#define _Included_com_scriptographer_ai_Document
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_ai_Document_DIALOG_NONE
#define com_scriptographer_ai_Document_DIALOG_NONE 0L
#undef com_scriptographer_ai_Document_DIALOG_ON
#define com_scriptographer_ai_Document_DIALOG_ON 1L
#undef com_scriptographer_ai_Document_DIALOG_PARTIAL_ON
#define com_scriptographer_ai_Document_DIALOG_PARTIAL_ON 2L
#undef com_scriptographer_ai_Document_DIALOG_OFF
#define com_scriptographer_ai_Document_DIALOG_OFF 3L
/* Inaccessible static: formats */
/*
 * Class:     com_scriptographer_ai_Document
 * Method:    nativeCreate
 * Signature: (Ljava/io/File;II)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Document_nativeCreate__Ljava_io_File_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;FFII)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Document_nativeCreate__Ljava_lang_String_2FFII
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jint, jint);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    getPageOrigin
 * Signature: ()Lcom/scriptographer/ai/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Document_getPageOrigin
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    setPageOrigin
 * Signature: (Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_setPageOrigin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    getRulerOrigin
 * Signature: ()Lcom/scriptographer/ai/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Document_getRulerOrigin
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    setRulerOrigin
 * Signature: (Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_setRulerOrigin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    getSize
 * Signature: ()Lcom/scriptographer/ai/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Document_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    setSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_setSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    getCropBox
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Document_getCropBox
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    setCropBox
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_setCropBox
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    isModified
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Document_isModified
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    setModified
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_setModified
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    getFile
 * Signature: ()Ljava/io/File;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Document_getFile
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    nativeGetFormats
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_Document_nativeGetFormats
  (JNIEnv *, jclass);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    activate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_activate
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_print
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_save
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_close
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    redraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_redraw
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    copy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_copy
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    cut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_cut
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    paste
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Document_paste
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Document
 * Method:    write
 * Signature: (Ljava/io/File;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Document_write
  (JNIEnv *, jobject, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
