/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_Image */

#ifndef _Included_com_scriptographer_adm_Image
#define _Included_com_scriptographer_adm_Image
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_Image_TYPE_RGB
#define com_scriptographer_adm_Image_TYPE_RGB 0L
#undef com_scriptographer_adm_Image_TYPE_RGB_ALPHA
#define com_scriptographer_adm_Image_TYPE_RGB_ALPHA 1L
#undef com_scriptographer_adm_Image_TYPE_OFFSCREEN
#define com_scriptographer_adm_Image_TYPE_OFFSCREEN 2L
#undef com_scriptographer_adm_Image_TYPE_OFFSCREEN_ALPHA
#define com_scriptographer_adm_Image_TYPE_OFFSCREEN_ALPHA 3L
/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeCreate
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Image_nativeCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeDestroy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Image_nativeDestroy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeSetPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Image_nativeSetPixels___3IIII
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeGetPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Image_nativeGetPixels
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeSetPixels
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Image_nativeSetPixels__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeCreateIcon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Image_nativeCreateIcon
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeBeginDrawer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Image_nativeBeginDrawer
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Image
 * Method:    nativeEndDrawer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Image_nativeEndDrawer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
