/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_MenuGroup */

#ifndef _Included_com_scriptographer_ai_MenuGroup
#define _Included_com_scriptographer_ai_MenuGroup
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: GROUP_ABOUT */
/* Inaccessible static: GROUP_OPEN */
/* Inaccessible static: GROUP_RECENT */
/* Inaccessible static: GROUP_CLOSE */
/* Inaccessible static: GROUP_SAVE */
/* Inaccessible static: GROUP_SAVE_FOR */
/* Inaccessible static: GROUP_IMPORT */
/* Inaccessible static: GROUP_PLACE */
/* Inaccessible static: GROUP_EXPORT */
/* Inaccessible static: GROUP_DOCUMENT_UTILS */
/* Inaccessible static: GROUP_DOCUMENT_INTERCHANGE */
/* Inaccessible static: GROUP_PRINT */
/* Inaccessible static: GROUP_SEND */
/* Inaccessible static: GROUP_APP_UTILS */
/* Inaccessible static: GROUP_QUIT */
/* Inaccessible static: GROUP_UNDO */
/* Inaccessible static: GROUP_PASTEUTILS */
/* Inaccessible static: GROUP_SELECT */
/* Inaccessible static: GROUP_SELECT_EXTERNAL */
/* Inaccessible static: GROUP_EDITTEXT */
/* Inaccessible static: GROUP_EDIT */
/* Inaccessible static: GROUP_PRESETS */
/* Inaccessible static: GROUP_SAME */
/* Inaccessible static: GROUP_SELECT_OBJECT */
/* Inaccessible static: GROUP_PREFERENCES */
/* Inaccessible static: GROUP_EDIT_UTILITIES */
/* Inaccessible static: GROUP_CLIPBOARD */
/* Inaccessible static: GROUP_REPEAT */
/* Inaccessible static: GROUP_ARRANGE_TRANSFORM */
/* Inaccessible static: GROUP_ARRANGE_MOVE */
/* Inaccessible static: GROUP_ARRANGE_GROUP */
/* Inaccessible static: GROUP_ARRANGE_ATTRIBUTES */
/* Inaccessible static: GROUP_VIEW_MODE */
/* Inaccessible static: GROUP_VIEW_ADORNMENTS */
/* Inaccessible static: GROUP_VIEW */
/* Inaccessible static: GROUP_VIEW_UTILITIES */
/* Inaccessible static: GROUP_VIEW_EXTENSION */
/* Inaccessible static: GROUP_OBJECT_ATTRIBUTES */
/* Inaccessible static: GROUP_OBJECT_UTILITIES */
/* Inaccessible static: GROUP_OBJECTS */
/* Inaccessible static: GROUP_OBJECT_PATHS */
/* Inaccessible static: GROUP_OBJECT_PATHS_POPUP */
/* Inaccessible static: GROUP_LOCK */
/* Inaccessible static: GROUP_HIDE */
/* Inaccessible static: GROUP_GUIDES */
/* Inaccessible static: GROUP_MASK */
/* Inaccessible static: GROUP_COMPOUNDPATHS */
/* Inaccessible static: GROUP_CROPMARKS */
/* Inaccessible static: GROUP_GRAPHS */
/* Inaccessible static: GROUP_BLOCKS */
/* Inaccessible static: GROUP_WRAP */
/* Inaccessible static: GROUP_TYPE_TEXTPATH */
/* Inaccessible static: GROUP_TYPE_ATTRIBUTES */
/* Inaccessible static: GROUP_TYPE_PALETTES */
/* Inaccessible static: GROUP_TYPE_LAYOUT */
/* Inaccessible static: GROUP_TYPE_UTILS */
/* Inaccessible static: GROUP_TYPE_PLUGINS1 */
/* Inaccessible static: GROUP_TYPE_PLUGINS2 */
/* Inaccessible static: GROUP_TYPE_ASIAN_OPTIONS */
/* Inaccessible static: GROUP_TYPE_SIZE_UTILITIES */
/* Inaccessible static: GROUP_TYPE_SIZE */
/* Inaccessible static: GROUP_TYPE_LEADING_UTILITIES */
/* Inaccessible static: GROUP_TYPE_LEADING */
/* Inaccessible static: GROUP_TYPE_ALIGNMENT */
/* Inaccessible static: GROUP_FILTER_UTILITIES */
/* Inaccessible static: GROUP_EFFECTS */
/* Inaccessible static: GROUP_HELP */
/* Inaccessible static: GROUP_HIDDEN_OTHER_SELECT */
/* Inaccessible static: GROUP_HIDDEN_OTHER_TEXT */
/* Inaccessible static: GROUP_HIDDEN_OTHER_OBJECT */
/* Inaccessible static: GROUP_HIDDEN_OTHER_PALETTE */
/* Inaccessible static: GROUP_HIDDEN_OTHER_MISC */
/* Inaccessible static: GROUP_WINDOW_UTILITIES */
/* Inaccessible static: GROUP_TOOL_PALETTES */
/* Inaccessible static: GROUP_WINDOW_LIBARIES */
/* Inaccessible static: GROUP_DOCUMENT_INFO */
/* Inaccessible static: GROUP_OBJECT_RASTER */
/* Inaccessible static: GROUP_ARRANGE_TRANSFORM_MULTIPLE */
/* Inaccessible static: GROUP_ARRANGE_TRANSFORM_MULTIPLE_NEAR */
/* Inaccessible static: GROUP_OBJECT_PATHS_POPOUT */
/* Inaccessible static: GROUP_OBJECT_PATHS_POPOUT_NEAR */
/* Inaccessible static: GROUP_DOCUMENT_SUPPORT */
/* Inaccessible static: GROUP_ASSET_MANAGEMENT */
/* Inaccessible static: GROUP_WORKGROUP */
/* Inaccessible static: GROUP_SCRIPTS */
#undef com_scriptographer_ai_MenuGroup_OPTION_SORTED_ALPHABETICALLY
#define com_scriptographer_ai_MenuGroup_OPTION_SORTED_ALPHABETICALLY 1L
#undef com_scriptographer_ai_MenuGroup_OPTION_SEPERATOR_ABOVE
#define com_scriptographer_ai_MenuGroup_OPTION_SEPERATOR_ABOVE 2L
#undef com_scriptographer_ai_MenuGroup_OPTION_SEPARATOR_BELOW
#define com_scriptographer_ai_MenuGroup_OPTION_SEPARATOR_BELOW 4L
/* Inaccessible static: groups */
/*
 * Class:     com_scriptographer_ai_MenuGroup
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_MenuGroup_nativeCreate
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_scriptographer_ai_MenuGroup
 * Method:    setOption
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_MenuGroup_setOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_MenuGroup
 * Method:    getOptions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_MenuGroup_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
