/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_LiveEffect */

#ifndef _Included_com_scriptographer_ai_LiveEffect
#define _Included_com_scriptographer_ai_LiveEffect
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_ai_LiveEffect_INPUT_DYNAMIC
#define com_scriptographer_ai_LiveEffect_INPUT_DYNAMIC 0L
#undef com_scriptographer_ai_LiveEffect_INPUT_GROUP
#define com_scriptographer_ai_LiveEffect_INPUT_GROUP 1L
#undef com_scriptographer_ai_LiveEffect_INPUT_PATH
#define com_scriptographer_ai_LiveEffect_INPUT_PATH 2L
#undef com_scriptographer_ai_LiveEffect_INPUT_COMPOUNDPATH
#define com_scriptographer_ai_LiveEffect_INPUT_COMPOUNDPATH 4L
#undef com_scriptographer_ai_LiveEffect_INPUT_PLACED
#define com_scriptographer_ai_LiveEffect_INPUT_PLACED 64L
#undef com_scriptographer_ai_LiveEffect_INPUT_MYSTERYPATH
#define com_scriptographer_ai_LiveEffect_INPUT_MYSTERYPATH 128L
#undef com_scriptographer_ai_LiveEffect_INPUT_RASTER
#define com_scriptographer_ai_LiveEffect_INPUT_RASTER 256L
#undef com_scriptographer_ai_LiveEffect_INPUT_PLUGIN
#define com_scriptographer_ai_LiveEffect_INPUT_PLUGIN 512L
#undef com_scriptographer_ai_LiveEffect_INPUT_MESH
#define com_scriptographer_ai_LiveEffect_INPUT_MESH 1024L
#undef com_scriptographer_ai_LiveEffect_INPUT_TEXTFRAME
#define com_scriptographer_ai_LiveEffect_INPUT_TEXTFRAME 2048L
#undef com_scriptographer_ai_LiveEffect_INPUT_SYMBOL
#define com_scriptographer_ai_LiveEffect_INPUT_SYMBOL 4096L
#undef com_scriptographer_ai_LiveEffect_INPUT_FOREIGN
#define com_scriptographer_ai_LiveEffect_INPUT_FOREIGN 8192L
#undef com_scriptographer_ai_LiveEffect_INPUT_LEGACYTEXT
#define com_scriptographer_ai_LiveEffect_INPUT_LEGACYTEXT 16384L
#undef com_scriptographer_ai_LiveEffect_INPUT_ANY
#define com_scriptographer_ai_LiveEffect_INPUT_ANY 4095L
#undef com_scriptographer_ai_LiveEffect_INPUT_ANY_BUT_PLUGIN
#define com_scriptographer_ai_LiveEffect_INPUT_ANY_BUT_PLUGIN 3583L
#undef com_scriptographer_ai_LiveEffect_INPUT_OUTLINED_STROKE
#define com_scriptographer_ai_LiveEffect_INPUT_OUTLINED_STROKE 65536L
#undef com_scriptographer_ai_LiveEffect_INPUT_NO_CLIPMASKS
#define com_scriptographer_ai_LiveEffect_INPUT_NO_CLIPMASKS 131072L
#undef com_scriptographer_ai_LiveEffect_TYPE_DEFAULT
#define com_scriptographer_ai_LiveEffect_TYPE_DEFAULT 0L
#undef com_scriptographer_ai_LiveEffect_TYPE_PRE_EFFECT
#define com_scriptographer_ai_LiveEffect_TYPE_PRE_EFFECT 1L
#undef com_scriptographer_ai_LiveEffect_TYPE_POST_EFFECT
#define com_scriptographer_ai_LiveEffect_TYPE_POST_EFFECT 2L
#undef com_scriptographer_ai_LiveEffect_TYPE_STROKE
#define com_scriptographer_ai_LiveEffect_TYPE_STROKE 3L
#undef com_scriptographer_ai_LiveEffect_TYPE_FILL
#define com_scriptographer_ai_LiveEffect_TYPE_FILL 4L
#undef com_scriptographer_ai_LiveEffect_FLAG_NONE
#define com_scriptographer_ai_LiveEffect_FLAG_NONE 0L
#undef com_scriptographer_ai_LiveEffect_FLAG_SPECIAL_GROU_PRE_FILTER
#define com_scriptographer_ai_LiveEffect_FLAG_SPECIAL_GROU_PRE_FILTER 65536L
#undef com_scriptographer_ai_LiveEffect_FLAG_HAS_SCALABLE_PARAMS
#define com_scriptographer_ai_LiveEffect_FLAG_HAS_SCALABLE_PARAMS 131072L
#undef com_scriptographer_ai_LiveEffect_FLAG_USE_AUTO_RASTARIZE
#define com_scriptographer_ai_LiveEffect_FLAG_USE_AUTO_RASTARIZE 262144L
#undef com_scriptographer_ai_LiveEffect_FLAG_CAN_GENERATE_SVG_FILTER
#define com_scriptographer_ai_LiveEffect_FLAG_CAN_GENERATE_SVG_FILTER 524288L
/* Inaccessible static: effects */
/* Inaccessible static: unusedEffects */
/*
 * Class:     com_scriptographer_ai_LiveEffect
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_LiveEffect_nativeCreate
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_ai_LiveEffect
 * Method:    nativeAddMenuItem
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/scriptographer/ai/MenuItem;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_LiveEffect_nativeAddMenuItem
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_scriptographer_ai_LiveEffect
 * Method:    updateParameters
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_LiveEffect_updateParameters
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_LiveEffect
 * Method:    getMenuItem
 * Signature: (Ljava/util/Map;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_LiveEffect_getMenuItem
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
