/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_HierarchyListEntry */

#ifndef _Included_com_scriptographer_adm_HierarchyListEntry
#define _Included_com_scriptographer_adm_HierarchyListEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getItem
 * Signature: ()Lcom/scriptographer/adm/Item;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getItem
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getChildList
 * Signature: ()Lcom/scriptographer/adm/HierarchyList;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getChildList
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    createChildList
 * Signature: ()Lcom/scriptographer/adm/HierarchyList;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_HierarchyListEntry_createChildList
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    deleteChildList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_deleteChildList
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    setExpanded
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_setExpanded
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    isExpanded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_HierarchyListEntry_isExpanded
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    setEntryNameHidden
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_setEntryNameHidden
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    isEntryNameHidden
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_HierarchyListEntry_isEntryNameHidden
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    setChildSelectable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_setChildSelectable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    isChildSelectable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_HierarchyListEntry_isChildSelectable
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getDepth
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getVisualDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getVisualDepth
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    areChildrenSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_HierarchyListEntry_areChildrenSelected
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getExpandArrowRect
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getExpandArrowRect
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    setTextRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_setTextRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    getEntryItem
 * Signature: ()Lcom/scriptographer/adm/Item;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_HierarchyListEntry_getEntryItem
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    setEntryItem
 * Signature: (Lcom/scriptographer/adm/Item;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_setEntryItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    nativeSetFont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_nativeSetFont
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    nativeSetTextColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_nativeSetTextColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    nativeSetBGColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_nativeSetBGColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_HierarchyListEntry
 * Method:    nativeSetDividerColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_HierarchyListEntry_nativeSetDividerColor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
