/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Path */

#ifndef _Included_com_scriptographer_ai_Path
#define _Included_com_scriptographer_ai_Path
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: artWrappers */
#undef com_scriptographer_ai_Path_TYPE_ANY
#define com_scriptographer_ai_Path_TYPE_ANY -1L
#undef com_scriptographer_ai_Path_TYPE_UNKNOWN
#define com_scriptographer_ai_Path_TYPE_UNKNOWN 0L
#undef com_scriptographer_ai_Path_TYPE_GROUP
#define com_scriptographer_ai_Path_TYPE_GROUP 1L
#undef com_scriptographer_ai_Path_TYPE_PATH
#define com_scriptographer_ai_Path_TYPE_PATH 2L
#undef com_scriptographer_ai_Path_TYPE_COMPOUNDPATH
#define com_scriptographer_ai_Path_TYPE_COMPOUNDPATH 3L
#undef com_scriptographer_ai_Path_TYPE_TEXT
#define com_scriptographer_ai_Path_TYPE_TEXT 4L
#undef com_scriptographer_ai_Path_TYPE_TEXTPATH
#define com_scriptographer_ai_Path_TYPE_TEXTPATH 5L
#undef com_scriptographer_ai_Path_TYPE_TEXTRUN
#define com_scriptographer_ai_Path_TYPE_TEXTRUN 6L
#undef com_scriptographer_ai_Path_TYPE_PLACED
#define com_scriptographer_ai_Path_TYPE_PLACED 7L
#undef com_scriptographer_ai_Path_TYPE_MYSTERYPATH
#define com_scriptographer_ai_Path_TYPE_MYSTERYPATH 8L
#undef com_scriptographer_ai_Path_TYPE_RASTER
#define com_scriptographer_ai_Path_TYPE_RASTER 9L
#undef com_scriptographer_ai_Path_TYPE_PLUGIN
#define com_scriptographer_ai_Path_TYPE_PLUGIN 10L
#undef com_scriptographer_ai_Path_TYPE_MESH
#define com_scriptographer_ai_Path_TYPE_MESH 11L
#undef com_scriptographer_ai_Path_TYPE_TEXTFRAME
#define com_scriptographer_ai_Path_TYPE_TEXTFRAME 12L
#undef com_scriptographer_ai_Path_TYPE_SYMBOL
#define com_scriptographer_ai_Path_TYPE_SYMBOL 13L
#undef com_scriptographer_ai_Path_TYPE_FOREIGN
#define com_scriptographer_ai_Path_TYPE_FOREIGN 14L
#undef com_scriptographer_ai_Path_TYPE_LEGACYTEXT
#define com_scriptographer_ai_Path_TYPE_LEGACYTEXT 15L
#undef com_scriptographer_ai_Path_TYPE_LAYER
#define com_scriptographer_ai_Path_TYPE_LAYER 100L
#undef com_scriptographer_ai_Path_ORDER_UNKNOWN
#define com_scriptographer_ai_Path_ORDER_UNKNOWN 0L
#undef com_scriptographer_ai_Path_ORDER_FIRST_BEFORE_SECOND
#define com_scriptographer_ai_Path_ORDER_FIRST_BEFORE_SECOND 1L
#undef com_scriptographer_ai_Path_ORDER_SECOND_AFTER_FIRST
#define com_scriptographer_ai_Path_ORDER_SECOND_AFTER_FIRST 1L
#undef com_scriptographer_ai_Path_ORDER_FIRST_AFTER_SECOND
#define com_scriptographer_ai_Path_ORDER_FIRST_AFTER_SECOND 2L
#undef com_scriptographer_ai_Path_ORDER_SECOND_BEFORE_FIRST
#define com_scriptographer_ai_Path_ORDER_SECOND_BEFORE_FIRST 2L
#undef com_scriptographer_ai_Path_ORDER_FIRST_INSIDE_SECOND
#define com_scriptographer_ai_Path_ORDER_FIRST_INSIDE_SECOND 3L
#undef com_scriptographer_ai_Path_ORDER_SECOND_INSIDE_FIRST
#define com_scriptographer_ai_Path_ORDER_SECOND_INSIDE_FIRST 4L
#undef com_scriptographer_ai_Path_ATTR_SELECTED
#define com_scriptographer_ai_Path_ATTR_SELECTED 1L
#undef com_scriptographer_ai_Path_ATTR_LOCKED
#define com_scriptographer_ai_Path_ATTR_LOCKED 2L
#undef com_scriptographer_ai_Path_ATTR_HIDDEN
#define com_scriptographer_ai_Path_ATTR_HIDDEN 4L
#undef com_scriptographer_ai_Path_ATTR_FULLY_SELECTED
#define com_scriptographer_ai_Path_ATTR_FULLY_SELECTED 8L
#undef com_scriptographer_ai_Path_ATTR_EXPANDED
#define com_scriptographer_ai_Path_ATTR_EXPANDED 16L
#undef com_scriptographer_ai_Path_ATTR_TARGETED
#define com_scriptographer_ai_Path_ATTR_TARGETED 32L
#undef com_scriptographer_ai_Path_ATTR_IS_CLIPMASK
#define com_scriptographer_ai_Path_ATTR_IS_CLIPMASK 4096L
#undef com_scriptographer_ai_Path_ATTR_IS_TEXTWRAP
#define com_scriptographer_ai_Path_ATTR_IS_TEXTWRAP 65536L
#undef com_scriptographer_ai_Path_ATTR_SELECTED_TOPLEVEL_GROUPS
#define com_scriptographer_ai_Path_ATTR_SELECTED_TOPLEVEL_GROUPS 64L
#undef com_scriptographer_ai_Path_ATTR_SELECTED_LAYERS
#define com_scriptographer_ai_Path_ATTR_SELECTED_LAYERS 128L
#undef com_scriptographer_ai_Path_ATTR_SELECTED_TOPLEVEL_WITH_PAINT
#define com_scriptographer_ai_Path_ATTR_SELECTED_TOPLEVEL_WITH_PAINT 256L
#undef com_scriptographer_ai_Path_ATTR_HAS_SIMPLE_STYLE
#define com_scriptographer_ai_Path_ATTR_HAS_SIMPLE_STYLE 512L
#undef com_scriptographer_ai_Path_ATTR_HAS_ACTIVE_STYLE
#define com_scriptographer_ai_Path_ATTR_HAS_ACTIVE_STYLE 1024L
#undef com_scriptographer_ai_Path_ATTR_PART_OF_COMPOUND
#define com_scriptographer_ai_Path_ATTR_PART_OF_COMPOUND 2048L
#undef com_scriptographer_ai_Path_ATTR_STYLE_IS_DIRTY
#define com_scriptographer_ai_Path_ATTR_STYLE_IS_DIRTY 262144L
#undef com_scriptographer_ai_Path_TRANSFORM_OBJECTS
#define com_scriptographer_ai_Path_TRANSFORM_OBJECTS 1L
#undef com_scriptographer_ai_Path_TRANSFORM_FILL_GRADIENTS
#define com_scriptographer_ai_Path_TRANSFORM_FILL_GRADIENTS 2L
#undef com_scriptographer_ai_Path_TRANSFORM_FILL_PATTERNS
#define com_scriptographer_ai_Path_TRANSFORM_FILL_PATTERNS 4L
#undef com_scriptographer_ai_Path_TRANSFORM_STROKE_PATTERNS
#define com_scriptographer_ai_Path_TRANSFORM_STROKE_PATTERNS 8L
#undef com_scriptographer_ai_Path_TRANSFORM_LINES
#define com_scriptographer_ai_Path_TRANSFORM_LINES 16L
#undef com_scriptographer_ai_Path_TRANSFORM_LINKED_MASKS
#define com_scriptographer_ai_Path_TRANSFORM_LINKED_MASKS 32L
#undef com_scriptographer_ai_Path_TRANSFORM_CHILDREN
#define com_scriptographer_ai_Path_TRANSFORM_CHILDREN 64L
#undef com_scriptographer_ai_Path_TRANSFORM_SELECTION_ONLY
#define com_scriptographer_ai_Path_TRANSFORM_SELECTION_ONLY 128L
#undef com_scriptographer_ai_Path_TRANSFORM_DEEP
#define com_scriptographer_ai_Path_TRANSFORM_DEEP 1024L
/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createRectangle
 * Signature: (Lcom/scriptographer/ai/Rectangle;)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createRectangle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createRoundRectangle
 * Signature: (Lcom/scriptographer/ai/Rectangle;FF)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createRoundRectangle
  (JNIEnv *, jclass, jobject, jfloat, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createOval
 * Signature: (Lcom/scriptographer/ai/Rectangle;Z)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createOval
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createRegularPolygon
 * Signature: (ILcom/scriptographer/ai/Point;F)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createRegularPolygon
  (JNIEnv *, jclass, jint, jobject, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createStar
 * Signature: (ILcom/scriptographer/ai/Point;FF)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createStar
  (JNIEnv *, jclass, jint, jobject, jfloat, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    createSpiral
 * Signature: (Lcom/scriptographer/ai/Point;Lcom/scriptographer/ai/Point;FIZ)Lcom/scriptographer/ai/Path;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_createSpiral
  (JNIEnv *, jclass, jobject, jobject, jfloat, jint, jboolean);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getClosed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Path_getClosed
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    setClosed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Path_setClosed
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getGuide
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Path_getGuide
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    setGuide
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Path_setGuide
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getTabletData
 * Signature: ()[Lcom/scriptographer/ai/TabletValue;
 */
JNIEXPORT jobjectArray JNICALL Java_com_scriptographer_ai_Path_getTabletData
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    setTabletData
 * Signature: ([Lcom/scriptographer/ai/TabletValue;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Path_setTabletData
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getLength
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_scriptographer_ai_Path_getLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getArea
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_scriptographer_ai_Path_getArea
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    nativePointsToCurves
 * Signature: (IFFIF)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Path_nativePointsToCurves
  (JNIEnv *, jclass, jint, jfloat, jfloat, jint, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    nativeCurvesToPoints
 * Signature: (IFF)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Path_nativeCurvesToPoints
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    nativeReduceSegments
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Path_nativeReduceSegments
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    nativeSplit
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Path_nativeSplit
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    hitTest
 * Signature: (Lcom/scriptographer/ai/Point;F)Lcom/scriptographer/ai/SegmentPosition;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_hitTest
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_scriptographer_ai_Path
 * Method:    getPositionWithLength
 * Signature: (FF)Lcom/scriptographer/ai/SegmentPosition;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Path_getPositionWithLength
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
