/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_PathStyle */

#ifndef _Included_com_scriptographer_ai_PathStyle
#define _Included_com_scriptographer_ai_PathStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scriptographer_ai_PathStyle
 * Method:    nativeFetch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_PathStyle_nativeFetch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_PathStyle
 * Method:    nativeCommit
 * Signature: (I[FZ[FZFF[FSSFZZZF)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_PathStyle_nativeCommit
  (JNIEnv *, jobject, jint, jfloatArray, jboolean, jfloatArray, jboolean, jfloat, jfloat, jfloatArray, jshort, jshort, jfloat, jboolean, jboolean, jboolean, jfloat);

#ifdef __cplusplus
}
#endif
#endif
