/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_PictureItem */

#ifndef _Included_com_scriptographer_adm_PictureItem
#define _Included_com_scriptographer_adm_PictureItem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_PictureItem_POPUP_MENU_RIGHT
#define com_scriptographer_adm_PictureItem_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_PictureItem_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_PictureItem_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_PictureItem_POPUP_MENU_ROUND
#define com_scriptographer_adm_PictureItem_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_PictureItem_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_PictureItem_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_PictureItem_SPINEDIT_VERTICAL
#define com_scriptographer_adm_PictureItem_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_PictureItem_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_PictureItem_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_PictureItem_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_PictureItem_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_PictureItem_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_PictureItem_SPINEDIT_POPUP_HORIZONTAL 4L
#undef com_scriptographer_adm_PictureItem_JUSTIFY_LEFT
#define com_scriptographer_adm_PictureItem_JUSTIFY_LEFT 0L
#undef com_scriptographer_adm_PictureItem_JUSTIFY_CENTER
#define com_scriptographer_adm_PictureItem_JUSTIFY_CENTER 1L
#undef com_scriptographer_adm_PictureItem_JUSTIFY_RIGHT
#define com_scriptographer_adm_PictureItem_JUSTIFY_RIGHT 2L
#undef com_scriptographer_adm_PictureItem_UNITS_NO
#define com_scriptographer_adm_PictureItem_UNITS_NO 0L
#undef com_scriptographer_adm_PictureItem_UNITS_POINT
#define com_scriptographer_adm_PictureItem_UNITS_POINT 1L
#undef com_scriptographer_adm_PictureItem_UNITS_INCH
#define com_scriptographer_adm_PictureItem_UNITS_INCH 2L
#undef com_scriptographer_adm_PictureItem_UNITS_MILLIMETER
#define com_scriptographer_adm_PictureItem_UNITS_MILLIMETER 3L
#undef com_scriptographer_adm_PictureItem_UNITS_CENTIMETER
#define com_scriptographer_adm_PictureItem_UNITS_CENTIMETER 4L
#undef com_scriptographer_adm_PictureItem_UNITS_PICA
#define com_scriptographer_adm_PictureItem_UNITS_PICA 5L
#undef com_scriptographer_adm_PictureItem_UNITS_PERCENT
#define com_scriptographer_adm_PictureItem_UNITS_PERCENT 6L
#undef com_scriptographer_adm_PictureItem_UNITS_DEGREE
#define com_scriptographer_adm_PictureItem_UNITS_DEGREE 7L
#undef com_scriptographer_adm_PictureItem_UNITS_Q
#define com_scriptographer_adm_PictureItem_UNITS_Q 8L
#undef com_scriptographer_adm_PictureItem_UNITS_BASE16
#define com_scriptographer_adm_PictureItem_UNITS_BASE16 9L
#undef com_scriptographer_adm_PictureItem_UNITS_PIXEL
#define com_scriptographer_adm_PictureItem_UNITS_PIXEL 10L
#undef com_scriptographer_adm_PictureItem_UNITS_TIME
#define com_scriptographer_adm_PictureItem_UNITS_TIME 11L
#undef com_scriptographer_adm_PictureItem_UNITS_HA
#define com_scriptographer_adm_PictureItem_UNITS_HA 12L
/*
 * Class:     com_scriptographer_adm_PictureItem
 * Method:    nativeSetPicture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_PictureItem_nativeSetPicture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_PictureItem
 * Method:    nativeSetRolloverPicture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_PictureItem_nativeSetRolloverPicture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_PictureItem
 * Method:    nativeSetSelectedPicture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_PictureItem_nativeSetSelectedPicture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_PictureItem
 * Method:    nativeSetDisabledPicture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_PictureItem_nativeSetDisabledPicture
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
