/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Raster */

#ifndef _Included_com_scriptographer_ai_Raster
#define _Included_com_scriptographer_ai_Raster
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: artWrappers */
#undef com_scriptographer_ai_Raster_TYPE_ANY
#define com_scriptographer_ai_Raster_TYPE_ANY -1L
#undef com_scriptographer_ai_Raster_TYPE_UNKNOWN
#define com_scriptographer_ai_Raster_TYPE_UNKNOWN 0L
#undef com_scriptographer_ai_Raster_TYPE_GROUP
#define com_scriptographer_ai_Raster_TYPE_GROUP 1L
#undef com_scriptographer_ai_Raster_TYPE_PATH
#define com_scriptographer_ai_Raster_TYPE_PATH 2L
#undef com_scriptographer_ai_Raster_TYPE_COMPOUNDPATH
#define com_scriptographer_ai_Raster_TYPE_COMPOUNDPATH 3L
#undef com_scriptographer_ai_Raster_TYPE_TEXT
#define com_scriptographer_ai_Raster_TYPE_TEXT 4L
#undef com_scriptographer_ai_Raster_TYPE_TEXTPATH
#define com_scriptographer_ai_Raster_TYPE_TEXTPATH 5L
#undef com_scriptographer_ai_Raster_TYPE_TEXTRUN
#define com_scriptographer_ai_Raster_TYPE_TEXTRUN 6L
#undef com_scriptographer_ai_Raster_TYPE_PLACED
#define com_scriptographer_ai_Raster_TYPE_PLACED 7L
#undef com_scriptographer_ai_Raster_TYPE_MYSTERYPATH
#define com_scriptographer_ai_Raster_TYPE_MYSTERYPATH 8L
#undef com_scriptographer_ai_Raster_TYPE_RASTER
#define com_scriptographer_ai_Raster_TYPE_RASTER 9L
#undef com_scriptographer_ai_Raster_TYPE_PLUGIN
#define com_scriptographer_ai_Raster_TYPE_PLUGIN 10L
#undef com_scriptographer_ai_Raster_TYPE_MESH
#define com_scriptographer_ai_Raster_TYPE_MESH 11L
#undef com_scriptographer_ai_Raster_TYPE_TEXTFRAME
#define com_scriptographer_ai_Raster_TYPE_TEXTFRAME 12L
#undef com_scriptographer_ai_Raster_TYPE_SYMBOL
#define com_scriptographer_ai_Raster_TYPE_SYMBOL 13L
#undef com_scriptographer_ai_Raster_TYPE_FOREIGN
#define com_scriptographer_ai_Raster_TYPE_FOREIGN 14L
#undef com_scriptographer_ai_Raster_TYPE_LEGACYTEXT
#define com_scriptographer_ai_Raster_TYPE_LEGACYTEXT 15L
#undef com_scriptographer_ai_Raster_TYPE_LAYER
#define com_scriptographer_ai_Raster_TYPE_LAYER 100L
#undef com_scriptographer_ai_Raster_ORDER_UNKNOWN
#define com_scriptographer_ai_Raster_ORDER_UNKNOWN 0L
#undef com_scriptographer_ai_Raster_ORDER_FIRST_BEFORE_SECOND
#define com_scriptographer_ai_Raster_ORDER_FIRST_BEFORE_SECOND 1L
#undef com_scriptographer_ai_Raster_ORDER_SECOND_AFTER_FIRST
#define com_scriptographer_ai_Raster_ORDER_SECOND_AFTER_FIRST 1L
#undef com_scriptographer_ai_Raster_ORDER_FIRST_AFTER_SECOND
#define com_scriptographer_ai_Raster_ORDER_FIRST_AFTER_SECOND 2L
#undef com_scriptographer_ai_Raster_ORDER_SECOND_BEFORE_FIRST
#define com_scriptographer_ai_Raster_ORDER_SECOND_BEFORE_FIRST 2L
#undef com_scriptographer_ai_Raster_ORDER_FIRST_INSIDE_SECOND
#define com_scriptographer_ai_Raster_ORDER_FIRST_INSIDE_SECOND 3L
#undef com_scriptographer_ai_Raster_ORDER_SECOND_INSIDE_FIRST
#define com_scriptographer_ai_Raster_ORDER_SECOND_INSIDE_FIRST 4L
#undef com_scriptographer_ai_Raster_ATTR_SELECTED
#define com_scriptographer_ai_Raster_ATTR_SELECTED 1L
#undef com_scriptographer_ai_Raster_ATTR_LOCKED
#define com_scriptographer_ai_Raster_ATTR_LOCKED 2L
#undef com_scriptographer_ai_Raster_ATTR_HIDDEN
#define com_scriptographer_ai_Raster_ATTR_HIDDEN 4L
#undef com_scriptographer_ai_Raster_ATTR_FULLY_SELECTED
#define com_scriptographer_ai_Raster_ATTR_FULLY_SELECTED 8L
#undef com_scriptographer_ai_Raster_ATTR_EXPANDED
#define com_scriptographer_ai_Raster_ATTR_EXPANDED 16L
#undef com_scriptographer_ai_Raster_ATTR_TARGETED
#define com_scriptographer_ai_Raster_ATTR_TARGETED 32L
#undef com_scriptographer_ai_Raster_ATTR_IS_CLIPMASK
#define com_scriptographer_ai_Raster_ATTR_IS_CLIPMASK 4096L
#undef com_scriptographer_ai_Raster_ATTR_IS_TEXTWRAP
#define com_scriptographer_ai_Raster_ATTR_IS_TEXTWRAP 65536L
#undef com_scriptographer_ai_Raster_ATTR_SELECTED_TOPLEVEL_GROUPS
#define com_scriptographer_ai_Raster_ATTR_SELECTED_TOPLEVEL_GROUPS 64L
#undef com_scriptographer_ai_Raster_ATTR_SELECTED_LAYERS
#define com_scriptographer_ai_Raster_ATTR_SELECTED_LAYERS 128L
#undef com_scriptographer_ai_Raster_ATTR_SELECTED_TOPLEVEL_WITH_PAINT
#define com_scriptographer_ai_Raster_ATTR_SELECTED_TOPLEVEL_WITH_PAINT 256L
#undef com_scriptographer_ai_Raster_ATTR_HAS_SIMPLE_STYLE
#define com_scriptographer_ai_Raster_ATTR_HAS_SIMPLE_STYLE 512L
#undef com_scriptographer_ai_Raster_ATTR_HAS_ACTIVE_STYLE
#define com_scriptographer_ai_Raster_ATTR_HAS_ACTIVE_STYLE 1024L
#undef com_scriptographer_ai_Raster_ATTR_PART_OF_COMPOUND
#define com_scriptographer_ai_Raster_ATTR_PART_OF_COMPOUND 2048L
#undef com_scriptographer_ai_Raster_ATTR_STYLE_IS_DIRTY
#define com_scriptographer_ai_Raster_ATTR_STYLE_IS_DIRTY 262144L
#undef com_scriptographer_ai_Raster_TRANSFORM_OBJECTS
#define com_scriptographer_ai_Raster_TRANSFORM_OBJECTS 1L
#undef com_scriptographer_ai_Raster_TRANSFORM_FILL_GRADIENTS
#define com_scriptographer_ai_Raster_TRANSFORM_FILL_GRADIENTS 2L
#undef com_scriptographer_ai_Raster_TRANSFORM_FILL_PATTERNS
#define com_scriptographer_ai_Raster_TRANSFORM_FILL_PATTERNS 4L
#undef com_scriptographer_ai_Raster_TRANSFORM_STROKE_PATTERNS
#define com_scriptographer_ai_Raster_TRANSFORM_STROKE_PATTERNS 8L
#undef com_scriptographer_ai_Raster_TRANSFORM_LINES
#define com_scriptographer_ai_Raster_TRANSFORM_LINES 16L
#undef com_scriptographer_ai_Raster_TRANSFORM_LINKED_MASKS
#define com_scriptographer_ai_Raster_TRANSFORM_LINKED_MASKS 32L
#undef com_scriptographer_ai_Raster_TRANSFORM_CHILDREN
#define com_scriptographer_ai_Raster_TRANSFORM_CHILDREN 64L
#undef com_scriptographer_ai_Raster_TRANSFORM_SELECTION_ONLY
#define com_scriptographer_ai_Raster_TRANSFORM_SELECTION_ONLY 128L
#undef com_scriptographer_ai_Raster_TRANSFORM_DEEP
#define com_scriptographer_ai_Raster_TRANSFORM_DEEP 1024L
/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Raster_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    setWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Raster_setWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Raster_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    setHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Raster_setHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Raster_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Raster_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    getPixel
 * Signature: (II)Lcom/scriptographer/ai/Color;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Raster_getPixel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    setPixel
 * Signature: (IILcom/scriptographer/ai/Color;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Raster_setPixel
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_scriptographer_ai_Raster
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Raster_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
