/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_TextEdit */

#ifndef _Included_com_scriptographer_adm_TextEdit
#define _Included_com_scriptographer_adm_TextEdit
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_TextEdit_POPUP_MENU_RIGHT
#define com_scriptographer_adm_TextEdit_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_TextEdit_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_TextEdit_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_TextEdit_POPUP_MENU_ROUND
#define com_scriptographer_adm_TextEdit_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_TextEdit_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_TextEdit_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_TextEdit_SPINEDIT_VERTICAL
#define com_scriptographer_adm_TextEdit_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_TextEdit_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_TextEdit_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_TextEdit_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_TextEdit_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_TextEdit_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_TextEdit_SPINEDIT_POPUP_HORIZONTAL 4L
#undef com_scriptographer_adm_TextEdit_JUSTIFY_LEFT
#define com_scriptographer_adm_TextEdit_JUSTIFY_LEFT 0L
#undef com_scriptographer_adm_TextEdit_JUSTIFY_CENTER
#define com_scriptographer_adm_TextEdit_JUSTIFY_CENTER 1L
#undef com_scriptographer_adm_TextEdit_JUSTIFY_RIGHT
#define com_scriptographer_adm_TextEdit_JUSTIFY_RIGHT 2L
#undef com_scriptographer_adm_TextEdit_UNITS_NO
#define com_scriptographer_adm_TextEdit_UNITS_NO 0L
#undef com_scriptographer_adm_TextEdit_UNITS_POINT
#define com_scriptographer_adm_TextEdit_UNITS_POINT 1L
#undef com_scriptographer_adm_TextEdit_UNITS_INCH
#define com_scriptographer_adm_TextEdit_UNITS_INCH 2L
#undef com_scriptographer_adm_TextEdit_UNITS_MILLIMETER
#define com_scriptographer_adm_TextEdit_UNITS_MILLIMETER 3L
#undef com_scriptographer_adm_TextEdit_UNITS_CENTIMETER
#define com_scriptographer_adm_TextEdit_UNITS_CENTIMETER 4L
#undef com_scriptographer_adm_TextEdit_UNITS_PICA
#define com_scriptographer_adm_TextEdit_UNITS_PICA 5L
#undef com_scriptographer_adm_TextEdit_UNITS_PERCENT
#define com_scriptographer_adm_TextEdit_UNITS_PERCENT 6L
#undef com_scriptographer_adm_TextEdit_UNITS_DEGREE
#define com_scriptographer_adm_TextEdit_UNITS_DEGREE 7L
#undef com_scriptographer_adm_TextEdit_UNITS_Q
#define com_scriptographer_adm_TextEdit_UNITS_Q 8L
#undef com_scriptographer_adm_TextEdit_UNITS_BASE16
#define com_scriptographer_adm_TextEdit_UNITS_BASE16 9L
#undef com_scriptographer_adm_TextEdit_UNITS_PIXEL
#define com_scriptographer_adm_TextEdit_UNITS_PIXEL 10L
#undef com_scriptographer_adm_TextEdit_UNITS_TIME
#define com_scriptographer_adm_TextEdit_UNITS_TIME 11L
#undef com_scriptographer_adm_TextEdit_UNITS_HA
#define com_scriptographer_adm_TextEdit_UNITS_HA 12L
#undef com_scriptographer_adm_TextEdit_STYLE_READONLY
#define com_scriptographer_adm_TextEdit_STYLE_READONLY 64L
#undef com_scriptographer_adm_TextEdit_STYLE_MULTILINE
#define com_scriptographer_adm_TextEdit_STYLE_MULTILINE 128L
#undef com_scriptographer_adm_TextEdit_STYLE_POPUP
#define com_scriptographer_adm_TextEdit_STYLE_POPUP 256L
#undef com_scriptographer_adm_TextEdit_STYLE_SCROLLING
#define com_scriptographer_adm_TextEdit_STYLE_SCROLLING 512L
#undef com_scriptographer_adm_TextEdit_STYLE_SINGLELINE
#define com_scriptographer_adm_TextEdit_STYLE_SINGLELINE 0L
#undef com_scriptographer_adm_TextEdit_STYLE_NUMERIC
#define com_scriptographer_adm_TextEdit_STYLE_NUMERIC 2L
#undef com_scriptographer_adm_TextEdit_STYLE_EXCLUSIVE
#define com_scriptographer_adm_TextEdit_STYLE_EXCLUSIVE 5L
#undef com_scriptographer_adm_TextEdit_STYLE_TRACK_RAW_KEYS
#define com_scriptographer_adm_TextEdit_STYLE_TRACK_RAW_KEYS 4L
#undef com_scriptographer_adm_TextEdit_STYLE_PASSWORD
#define com_scriptographer_adm_TextEdit_STYLE_PASSWORD 32L
#undef com_scriptographer_adm_TextEdit_OPTION_PASSWORD
#define com_scriptographer_adm_TextEdit_OPTION_PASSWORD 2L
#undef com_scriptographer_adm_TextEdit_OPTION_UNICODE
#define com_scriptographer_adm_TextEdit_OPTION_UNICODE 4L
#undef com_scriptographer_adm_TextEdit_OPTION_DISABLE_DRAG_DROP
#define com_scriptographer_adm_TextEdit_OPTION_DISABLE_DRAG_DROP 8L
/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    setMaxLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_TextEdit_setMaxLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    getMaxLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_TextEdit_getMaxLength
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    setSelectionRange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_TextEdit_setSelectionRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    getSelectionRange
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_scriptographer_adm_TextEdit_getSelectionRange
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    selectAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_TextEdit_selectAll
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    setAllowMath
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_TextEdit_setAllowMath
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    getAllowMath
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_TextEdit_getAllowMath
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    setAllowUnits
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_TextEdit_setAllowUnits
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_TextEdit
 * Method:    getAllowUnits
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_TextEdit_getAllowUnits
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
