/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_ScrollBar */

#ifndef _Included_com_scriptographer_adm_ScrollBar
#define _Included_com_scriptographer_adm_ScrollBar
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_ScrollBar_POPUP_MENU_RIGHT
#define com_scriptographer_adm_ScrollBar_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_ScrollBar_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_ScrollBar_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_ScrollBar_POPUP_MENU_ROUND
#define com_scriptographer_adm_ScrollBar_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_ScrollBar_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_ScrollBar_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_ScrollBar_SPINEDIT_VERTICAL
#define com_scriptographer_adm_ScrollBar_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_ScrollBar_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_ScrollBar_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_ScrollBar_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_ScrollBar_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_ScrollBar_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_ScrollBar_SPINEDIT_POPUP_HORIZONTAL 4L
/*
 * Class:     com_scriptographer_adm_ScrollBar
 * Method:    getIncrements
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_scriptographer_adm_ScrollBar_getIncrements
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_ScrollBar
 * Method:    setIncrements
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_ScrollBar_setIncrements
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
