/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ConsoleOutputStream */

#ifndef _Included_com_scriptographer_ConsoleOutputStream
#define _Included_com_scriptographer_ConsoleOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: console */
/*
 * Class:     com_scriptographer_ConsoleOutputStream
 * Method:    writeLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ConsoleOutputStream_writeLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
