/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Art */

#ifndef _Included_com_scriptographer_ai_Art
#define _Included_com_scriptographer_ai_Art
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: artWrappers */
#undef com_scriptographer_ai_Art_TYPE_ANY
#define com_scriptographer_ai_Art_TYPE_ANY -1L
#undef com_scriptographer_ai_Art_TYPE_UNKNOWN
#define com_scriptographer_ai_Art_TYPE_UNKNOWN 0L
#undef com_scriptographer_ai_Art_TYPE_GROUP
#define com_scriptographer_ai_Art_TYPE_GROUP 1L
#undef com_scriptographer_ai_Art_TYPE_PATH
#define com_scriptographer_ai_Art_TYPE_PATH 2L
#undef com_scriptographer_ai_Art_TYPE_COMPOUNDPATH
#define com_scriptographer_ai_Art_TYPE_COMPOUNDPATH 3L
#undef com_scriptographer_ai_Art_TYPE_TEXT
#define com_scriptographer_ai_Art_TYPE_TEXT 4L
#undef com_scriptographer_ai_Art_TYPE_TEXTPATH
#define com_scriptographer_ai_Art_TYPE_TEXTPATH 5L
#undef com_scriptographer_ai_Art_TYPE_TEXTRUN
#define com_scriptographer_ai_Art_TYPE_TEXTRUN 6L
#undef com_scriptographer_ai_Art_TYPE_PLACED
#define com_scriptographer_ai_Art_TYPE_PLACED 7L
#undef com_scriptographer_ai_Art_TYPE_MYSTERYPATH
#define com_scriptographer_ai_Art_TYPE_MYSTERYPATH 8L
#undef com_scriptographer_ai_Art_TYPE_RASTER
#define com_scriptographer_ai_Art_TYPE_RASTER 9L
#undef com_scriptographer_ai_Art_TYPE_PLUGIN
#define com_scriptographer_ai_Art_TYPE_PLUGIN 10L
#undef com_scriptographer_ai_Art_TYPE_MESH
#define com_scriptographer_ai_Art_TYPE_MESH 11L
#undef com_scriptographer_ai_Art_TYPE_TEXTFRAME
#define com_scriptographer_ai_Art_TYPE_TEXTFRAME 12L
#undef com_scriptographer_ai_Art_TYPE_SYMBOL
#define com_scriptographer_ai_Art_TYPE_SYMBOL 13L
#undef com_scriptographer_ai_Art_TYPE_FOREIGN
#define com_scriptographer_ai_Art_TYPE_FOREIGN 14L
#undef com_scriptographer_ai_Art_TYPE_LEGACYTEXT
#define com_scriptographer_ai_Art_TYPE_LEGACYTEXT 15L
#undef com_scriptographer_ai_Art_TYPE_LAYER
#define com_scriptographer_ai_Art_TYPE_LAYER 100L
#undef com_scriptographer_ai_Art_ORDER_UNKNOWN
#define com_scriptographer_ai_Art_ORDER_UNKNOWN 0L
#undef com_scriptographer_ai_Art_ORDER_FIRST_BEFORE_SECOND
#define com_scriptographer_ai_Art_ORDER_FIRST_BEFORE_SECOND 1L
#undef com_scriptographer_ai_Art_ORDER_SECOND_AFTER_FIRST
#define com_scriptographer_ai_Art_ORDER_SECOND_AFTER_FIRST 1L
#undef com_scriptographer_ai_Art_ORDER_FIRST_AFTER_SECOND
#define com_scriptographer_ai_Art_ORDER_FIRST_AFTER_SECOND 2L
#undef com_scriptographer_ai_Art_ORDER_SECOND_BEFORE_FIRST
#define com_scriptographer_ai_Art_ORDER_SECOND_BEFORE_FIRST 2L
#undef com_scriptographer_ai_Art_ORDER_FIRST_INSIDE_SECOND
#define com_scriptographer_ai_Art_ORDER_FIRST_INSIDE_SECOND 3L
#undef com_scriptographer_ai_Art_ORDER_SECOND_INSIDE_FIRST
#define com_scriptographer_ai_Art_ORDER_SECOND_INSIDE_FIRST 4L
#undef com_scriptographer_ai_Art_ATTR_SELECTED
#define com_scriptographer_ai_Art_ATTR_SELECTED 1L
#undef com_scriptographer_ai_Art_ATTR_LOCKED
#define com_scriptographer_ai_Art_ATTR_LOCKED 2L
#undef com_scriptographer_ai_Art_ATTR_HIDDEN
#define com_scriptographer_ai_Art_ATTR_HIDDEN 4L
#undef com_scriptographer_ai_Art_ATTR_FULLY_SELECTED
#define com_scriptographer_ai_Art_ATTR_FULLY_SELECTED 8L
#undef com_scriptographer_ai_Art_ATTR_EXPANDED
#define com_scriptographer_ai_Art_ATTR_EXPANDED 16L
#undef com_scriptographer_ai_Art_ATTR_TARGETED
#define com_scriptographer_ai_Art_ATTR_TARGETED 32L
#undef com_scriptographer_ai_Art_ATTR_IS_CLIPMASK
#define com_scriptographer_ai_Art_ATTR_IS_CLIPMASK 4096L
#undef com_scriptographer_ai_Art_ATTR_IS_TEXTWRAP
#define com_scriptographer_ai_Art_ATTR_IS_TEXTWRAP 65536L
#undef com_scriptographer_ai_Art_ATTR_SELECTED_TOPLEVEL_GROUPS
#define com_scriptographer_ai_Art_ATTR_SELECTED_TOPLEVEL_GROUPS 64L
#undef com_scriptographer_ai_Art_ATTR_SELECTED_LAYERS
#define com_scriptographer_ai_Art_ATTR_SELECTED_LAYERS 128L
#undef com_scriptographer_ai_Art_ATTR_SELECTED_TOPLEVEL_WITH_PAINT
#define com_scriptographer_ai_Art_ATTR_SELECTED_TOPLEVEL_WITH_PAINT 256L
#undef com_scriptographer_ai_Art_ATTR_HAS_SIMPLE_STYLE
#define com_scriptographer_ai_Art_ATTR_HAS_SIMPLE_STYLE 512L
#undef com_scriptographer_ai_Art_ATTR_HAS_ACTIVE_STYLE
#define com_scriptographer_ai_Art_ATTR_HAS_ACTIVE_STYLE 1024L
#undef com_scriptographer_ai_Art_ATTR_PART_OF_COMPOUND
#define com_scriptographer_ai_Art_ATTR_PART_OF_COMPOUND 2048L
#undef com_scriptographer_ai_Art_ATTR_STYLE_IS_DIRTY
#define com_scriptographer_ai_Art_ATTR_STYLE_IS_DIRTY 262144L
#undef com_scriptographer_ai_Art_TRANSFORM_OBJECTS
#define com_scriptographer_ai_Art_TRANSFORM_OBJECTS 1L
#undef com_scriptographer_ai_Art_TRANSFORM_FILL_GRADIENTS
#define com_scriptographer_ai_Art_TRANSFORM_FILL_GRADIENTS 2L
#undef com_scriptographer_ai_Art_TRANSFORM_FILL_PATTERNS
#define com_scriptographer_ai_Art_TRANSFORM_FILL_PATTERNS 4L
#undef com_scriptographer_ai_Art_TRANSFORM_STROKE_PATTERNS
#define com_scriptographer_ai_Art_TRANSFORM_STROKE_PATTERNS 8L
#undef com_scriptographer_ai_Art_TRANSFORM_LINES
#define com_scriptographer_ai_Art_TRANSFORM_LINES 16L
#undef com_scriptographer_ai_Art_TRANSFORM_LINKED_MASKS
#define com_scriptographer_ai_Art_TRANSFORM_LINKED_MASKS 32L
#undef com_scriptographer_ai_Art_TRANSFORM_CHILDREN
#define com_scriptographer_ai_Art_TRANSFORM_CHILDREN 64L
#undef com_scriptographer_ai_Art_TRANSFORM_SELECTION_ONLY
#define com_scriptographer_ai_Art_TRANSFORM_SELECTION_ONLY 128L
#undef com_scriptographer_ai_Art_TRANSFORM_DEEP
#define com_scriptographer_ai_Art_TRANSFORM_DEEP 1024L
/*
 * Class:     com_scriptographer_ai_Art
 * Method:    clone
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_clone
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    nativeCreate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Art_nativeCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    nativeRemove
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Art_nativeRemove
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getFirstChild
 * Signature: ()Lcom/scriptographer/ai/Art;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getFirstChild
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getLastChild
 * Signature: ()Lcom/scriptographer/ai/Art;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getLastChild
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getNextSibling
 * Signature: ()Lcom/scriptographer/ai/Art;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getPreviousSibling
 * Signature: ()Lcom/scriptographer/ai/Art;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getPreviousSibling
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getParent
 * Signature: ()Lcom/scriptographer/ai/Art;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getParent
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getBounds
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_Art_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Art_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scriptographer_ai_Art_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    isCenterVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Art_isCenterVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    setCenterVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Art_setCenterVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    setUserAttributes
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Art_setUserAttributes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    getUserAttributes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_Art_getUserAttributes
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    append
 * Signature: (Lcom/scriptographer/ai/Art;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Art_append
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    moveAbove
 * Signature: (Lcom/scriptographer/ai/Art;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Art_moveAbove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    moveBelow
 * Signature: (Lcom/scriptographer/ai/Art;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Art_moveBelow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_ai_Art
 * Method:    transform
 * Signature: (Ljava/awt/geom/AffineTransform;I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Art_transform
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
