/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_Item */

#ifndef _Included_com_scriptographer_adm_Item
#define _Included_com_scriptographer_adm_Item
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_Item_POPUP_MENU_RIGHT
#define com_scriptographer_adm_Item_POPUP_MENU_RIGHT 0L
#undef com_scriptographer_adm_Item_POPUP_MENU_BOTTOM
#define com_scriptographer_adm_Item_POPUP_MENU_BOTTOM 1L
#undef com_scriptographer_adm_Item_POPUP_MENU_ROUND
#define com_scriptographer_adm_Item_POPUP_MENU_ROUND 2L
#undef com_scriptographer_adm_Item_POPUP_MENU_ROUND_HIERARCHY
#define com_scriptographer_adm_Item_POPUP_MENU_ROUND_HIERARCHY 4L
#undef com_scriptographer_adm_Item_SPINEDIT_VERTICAL
#define com_scriptographer_adm_Item_SPINEDIT_VERTICAL 0L
#undef com_scriptographer_adm_Item_SPINEDIT_HORIZONTAL
#define com_scriptographer_adm_Item_SPINEDIT_HORIZONTAL 1L
#undef com_scriptographer_adm_Item_SPINEDIT_POPUP_VERTICAL
#define com_scriptographer_adm_Item_SPINEDIT_POPUP_VERTICAL 0L
#undef com_scriptographer_adm_Item_SPINEDIT_POPUP_HORIZONTAL
#define com_scriptographer_adm_Item_SPINEDIT_POPUP_HORIZONTAL 4L
/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeCreate
 * Signature: (Lcom/scriptographer/adm/Dialog;Ljava/lang/String;Ljava/awt/Rectangle;I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Item_nativeCreate
  (JNIEnv *, jobject, jobject, jstring, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetTrackCallbackEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetTrackCallbackEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetDrawCallbackEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetDrawCallbackEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetStyle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    isKnown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_isKnown
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setKnown
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setKnown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    wantsFocus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_wantsFocus
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setWantsFocus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setWantsFocus
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeGetSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_nativeGetSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeGetBounds
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_nativeGetBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetBounds
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetBounds
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setLocation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setLocation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    getLocation
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    getPreferredSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_getPreferredSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    localToScreen
 * Signature: (II)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_localToScreen__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    screenToLocal
 * Signature: (II)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_screenToLocal__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    localToScreen
 * Signature: (IIII)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_localToScreen__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    screenToLocal
 * Signature: (IIII)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Item_screenToLocal__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_invalidate__
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    invalidate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_invalidate__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_update
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    getCursor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Item_getCursor
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setCursor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setCursor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    nativeSetTooltip
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_nativeSetTooltip
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    isToolTipEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Item_isToolTipEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    setToolTipEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_setToolTipEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    showToolTip
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_showToolTip
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Item
 * Method:    hideToolTip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Item_hideToolTip
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
