/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_SegmentList */

#ifndef _Included_com_scriptographer_ai_SegmentList
#define _Included_com_scriptographer_ai_SegmentList
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_ai_SegmentList_VALUES_PER_SEGMENT
#define com_scriptographer_ai_SegmentList_VALUES_PER_SEGMENT 7L
/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeGetLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_SegmentList_nativeGetLength
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeFetch
 * Signature: (III[F)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeFetch
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeCommit
 * Signature: (IIFFFFFFZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeCommit__IIFFFFFFZ
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeCommit
 * Signature: (III[F)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeCommit__III_3F
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeInsert
 * Signature: (IIFFFFFFZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeInsert__IIFFFFFFZ
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeInsert
 * Signature: (III[F)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeInsert__III_3F
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeRemove
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_SegmentList_nativeRemove
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_scriptographer_ai_SegmentList
 * Method:    nativeReverse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_SegmentList_nativeReverse
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
