/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_Drawer */

#ifndef _Included_com_scriptographer_adm_Drawer
#define _Included_com_scriptographer_adm_Drawer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_Drawer_COLOR_BLACK
#define com_scriptographer_adm_Drawer_COLOR_BLACK 0L
#undef com_scriptographer_adm_Drawer_COLOR_WHITE
#define com_scriptographer_adm_Drawer_COLOR_WHITE 1L
#undef com_scriptographer_adm_Drawer_COLOR_HILITE
#define com_scriptographer_adm_Drawer_COLOR_HILITE 2L
#undef com_scriptographer_adm_Drawer_COLOR_HILITE_TEXT
#define com_scriptographer_adm_Drawer_COLOR_HILITE_TEXT 3L
#undef com_scriptographer_adm_Drawer_COLOR_LIGHT
#define com_scriptographer_adm_Drawer_COLOR_LIGHT 4L
#undef com_scriptographer_adm_Drawer_COLOR_BACKGROUND
#define com_scriptographer_adm_Drawer_COLOR_BACKGROUND 5L
#undef com_scriptographer_adm_Drawer_COLOR_SHADOW
#define com_scriptographer_adm_Drawer_COLOR_SHADOW 6L
#undef com_scriptographer_adm_Drawer_COLOR_DISABLED
#define com_scriptographer_adm_Drawer_COLOR_DISABLED 7L
#undef com_scriptographer_adm_Drawer_COLOR_BUTTON_UP
#define com_scriptographer_adm_Drawer_COLOR_BUTTON_UP 8L
#undef com_scriptographer_adm_Drawer_COLOR_BUTTON_DOWN
#define com_scriptographer_adm_Drawer_COLOR_BUTTON_DOWN 9L
#undef com_scriptographer_adm_Drawer_COLOR_BUTTON_DOWN_SHADOW
#define com_scriptographer_adm_Drawer_COLOR_BUTTON_DOWN_SHADOW 10L
#undef com_scriptographer_adm_Drawer_COLOR_TOOLTIP_BACKGROUND
#define com_scriptographer_adm_Drawer_COLOR_TOOLTIP_BACKGROUND 11L
#undef com_scriptographer_adm_Drawer_COLOR_TOOLTIP_FOREGROUND
#define com_scriptographer_adm_Drawer_COLOR_TOOLTIP_FOREGROUND 12L
#undef com_scriptographer_adm_Drawer_COLOR_WINDOW
#define com_scriptographer_adm_Drawer_COLOR_WINDOW 13L
#undef com_scriptographer_adm_Drawer_COLOR_FOREGROUND
#define com_scriptographer_adm_Drawer_COLOR_FOREGROUND 14L
#undef com_scriptographer_adm_Drawer_COLOR_TEXT
#define com_scriptographer_adm_Drawer_COLOR_TEXT 15L
#undef com_scriptographer_adm_Drawer_COLOR_RED
#define com_scriptographer_adm_Drawer_COLOR_RED 16L
#undef com_scriptographer_adm_Drawer_COLOR_TAB_BACKGROUND
#define com_scriptographer_adm_Drawer_COLOR_TAB_BACKGROUND 17L
#undef com_scriptographer_adm_Drawer_COLOR_ACTIVE_TAB
#define com_scriptographer_adm_Drawer_COLOR_ACTIVE_TAB 18L
#undef com_scriptographer_adm_Drawer_COLOR_INACTIVE_TAB
#define com_scriptographer_adm_Drawer_COLOR_INACTIVE_TAB 19L
#undef com_scriptographer_adm_Drawer_MODE_NORMAL
#define com_scriptographer_adm_Drawer_MODE_NORMAL 0L
#undef com_scriptographer_adm_Drawer_MODE_XOR
#define com_scriptographer_adm_Drawer_MODE_XOR 1L
#undef com_scriptographer_adm_Drawer_RECOLOR_NO
#define com_scriptographer_adm_Drawer_RECOLOR_NO 0L
#undef com_scriptographer_adm_Drawer_RECOLOR_ACTIVE
#define com_scriptographer_adm_Drawer_RECOLOR_ACTIVE 1L
#undef com_scriptographer_adm_Drawer_RECOLOR_INACTIVE
#define com_scriptographer_adm_Drawer_RECOLOR_INACTIVE 2L
#undef com_scriptographer_adm_Drawer_RECOLOR_DISABLED
#define com_scriptographer_adm_Drawer_RECOLOR_DISABLED 3L
/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getBoundsRect
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getBoundsRect
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getClipRect
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getClipRect
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setClipRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setClipRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    intersectClipRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_intersectClipRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    unionClipRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_unionClipRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    subtractClipRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_subtractClipRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setClipPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setClipPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    intersectClipPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_intersectClipPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    unionClipPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_unionClipPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    subtractClipPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_subtractClipPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getOrigin
 * Signature: ()Lcom/scriptographer/ai/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getOrigin
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setOrigin
 * Signature: (Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setOrigin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getColor
 * Signature: ()Ljava/awt/Color;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setColor
 * Signature: (Ljava/awt/Color;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setColor__Ljava_awt_Color_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setColor__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getDrawMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Drawer_getDrawMode
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setDrawMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setDrawMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getFont
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Drawer_getFont
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    setFont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_setFont
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawLine
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawLine
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    fillPolygon
 * Signature: ([Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_fillPolygon
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    fillRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_fillRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    clearRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_clearRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawSunkenRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawSunkenRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawRaisedRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawRaisedRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    invertRect
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_invertRect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawOval
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawOval
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    fillOval
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_fillOval
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawImage
 * Signature: (Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawImage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawImageCentered
 * Signature: (Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawImageCentered
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawRecoloredImage
 * Signature: (Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Point;I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawRecoloredImage
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawRecoloredImageCentered
 * Signature: (Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Rectangle;I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawRecoloredImageCentered
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getTextWidth
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Drawer_getTextWidth
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawText
 * Signature: (Ljava/lang/String;Lcom/scriptographer/ai/Point;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawText
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawTextLeft
 * Signature: (Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawTextLeft
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawTextCentered
 * Signature: (Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawTextCentered
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawTextRight
 * Signature: (Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawTextRight
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawTextInABox
 * Signature: (Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawTextInABox
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawUpArrow
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawUpArrow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawDownArrow
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawDownArrow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawLeftArrow
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawLeftArrow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    drawRightArrow
 * Signature: (Lcom/scriptographer/ai/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Drawer_drawRightArrow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getFontInfo
 * Signature: ()Lcom/scriptographer/adm/Drawer$FontInfo;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getFontInfo__
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getFontInfo
 * Signature: (I)Lcom/scriptographer/adm/Drawer$FontInfo;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getFontInfo__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getUpdateRect
 * Signature: ()Lcom/scriptographer/ai/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Drawer_getUpdateRect
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Drawer
 * Method:    getTextRectHeight
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Drawer_getTextRectHeight
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
