/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_MenuItem */

#ifndef _Included_com_scriptographer_ai_MenuItem
#define _Included_com_scriptographer_ai_MenuItem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_ai_MenuItem_OPTION_WANTS_UPDATE
#define com_scriptographer_ai_MenuItem_OPTION_WANTS_UPDATE 1L
#undef com_scriptographer_ai_MenuItem_OPTION_ALWAYS_ENABLED
#define com_scriptographer_ai_MenuItem_OPTION_ALWAYS_ENABLED 2L
/* Inaccessible static: items */
/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_MenuItem_nativeCreate
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    nativeRemove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_MenuItem_nativeRemove
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    nativeSetText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_MenuItem_nativeSetText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    setOption
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_MenuItem_setOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    getOptions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_MenuItem_getOptions
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_MenuItem_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_MenuItem_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    setChecked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_MenuItem_setChecked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_ai_MenuItem
 * Method:    isChecked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_MenuItem_isChecked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
