/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_adm_Dialog */

#ifndef _Included_com_scriptographer_adm_Dialog
#define _Included_com_scriptographer_adm_Dialog
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_adm_Dialog_OPTION_TABBED_DIALOG_SHOWS_CYCLE
#define com_scriptographer_adm_Dialog_OPTION_TABBED_DIALOG_SHOWS_CYCLE 1L
#undef com_scriptographer_adm_Dialog_OPTION_PASS_MOUSEDOWNEVENT
#define com_scriptographer_adm_Dialog_OPTION_PASS_MOUSEDOWNEVENT 2L
#undef com_scriptographer_adm_Dialog_OPTION_IGNORE_KEYPAD_ENTER
#define com_scriptographer_adm_Dialog_OPTION_IGNORE_KEYPAD_ENTER 8L
#undef com_scriptographer_adm_Dialog_OPTION_DIALOGITEMS_HIDDEN
#define com_scriptographer_adm_Dialog_OPTION_DIALOGITEMS_HIDDEN 16L
#undef com_scriptographer_adm_Dialog_OPTION_FORCE_ROMAN
#define com_scriptographer_adm_Dialog_OPTION_FORCE_ROMAN 32L
#undef com_scriptographer_adm_Dialog_OPTION_TRACK_ENTER_BEFORE_OK
#define com_scriptographer_adm_Dialog_OPTION_TRACK_ENTER_BEFORE_OK 64L
#undef com_scriptographer_adm_Dialog_OPTION_MODAL_DIALOG_HAS_SYSTEM_CONTROLS
#define com_scriptographer_adm_Dialog_OPTION_MODAL_DIALOG_HAS_SYSTEM_CONTROLS 128L
#undef com_scriptographer_adm_Dialog_OPTION_POPUP_DIALOG_AS_FLOATING
#define com_scriptographer_adm_Dialog_OPTION_POPUP_DIALOG_AS_FLOATING 256L
#undef com_scriptographer_adm_Dialog_STYLE_MODAL
#define com_scriptographer_adm_Dialog_STYLE_MODAL 0L
#undef com_scriptographer_adm_Dialog_STYLE_ALERT
#define com_scriptographer_adm_Dialog_STYLE_ALERT 1L
#undef com_scriptographer_adm_Dialog_STYLE_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_FLOATING 2L
#undef com_scriptographer_adm_Dialog_STYLE_TABBED_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_TABBED_FLOATING 3L
#undef com_scriptographer_adm_Dialog_STYLE_RESIZING_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_RESIZING_FLOATING 4L
#undef com_scriptographer_adm_Dialog_STYLE_TABBED_RESIZING_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_TABBED_RESIZING_FLOATING 5L
#undef com_scriptographer_adm_Dialog_STYLE_POPUP
#define com_scriptographer_adm_Dialog_STYLE_POPUP 6L
#undef com_scriptographer_adm_Dialog_STYLE_NOCLOSE_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_NOCLOSE_FLOATING 7L
#undef com_scriptographer_adm_Dialog_STYLE_SYSTEM_ALERT
#define com_scriptographer_adm_Dialog_STYLE_SYSTEM_ALERT 8L
#undef com_scriptographer_adm_Dialog_STYLE_POPUP_CONTROL
#define com_scriptographer_adm_Dialog_STYLE_POPUP_CONTROL 9L
#undef com_scriptographer_adm_Dialog_STYLE_RESIZING_MODAL
#define com_scriptographer_adm_Dialog_STYLE_RESIZING_MODAL 10L
#undef com_scriptographer_adm_Dialog_STYLE_LEFTSIDED_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_LEFTSIDED_FLOATING 11L
#undef com_scriptographer_adm_Dialog_STYLE_LEFTSIDED_NOCLOSE_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_LEFTSIDED_NOCLOSE_FLOATING 12L
#undef com_scriptographer_adm_Dialog_STYLE_NOTITLE_DOCK_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_NOTITLE_DOCK_FLOATING 13L
#undef com_scriptographer_adm_Dialog_STYLE_TABBED_HIERARCHY_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_TABBED_HIERARCHY_FLOATING 14L
#undef com_scriptographer_adm_Dialog_STYLE_TABBED_RESIZING_HIERARCHY_FLOATING
#define com_scriptographer_adm_Dialog_STYLE_TABBED_RESIZING_HIERARCHY_FLOATING 15L
#undef com_scriptographer_adm_Dialog_STYLE_HOST_DEFINED
#define com_scriptographer_adm_Dialog_STYLE_HOST_DEFINED 65536L
#undef com_scriptographer_adm_Dialog_ITEM_UNIQUE
#define com_scriptographer_adm_Dialog_ITEM_UNIQUE 0L
#undef com_scriptographer_adm_Dialog_ITEM_FIRST
#define com_scriptographer_adm_Dialog_ITEM_FIRST -1L
#undef com_scriptographer_adm_Dialog_ITEM_LAST
#define com_scriptographer_adm_Dialog_ITEM_LAST -2L
#undef com_scriptographer_adm_Dialog_ITEM_DEFAULT
#define com_scriptographer_adm_Dialog_ITEM_DEFAULT -3L
#undef com_scriptographer_adm_Dialog_ITEM_CANCEL
#define com_scriptographer_adm_Dialog_ITEM_CANCEL -4L
#undef com_scriptographer_adm_Dialog_ITEM_MENU
#define com_scriptographer_adm_Dialog_ITEM_MENU -5L
#undef com_scriptographer_adm_Dialog_ITEM_RESIZE
#define com_scriptographer_adm_Dialog_ITEM_RESIZE -6L
#undef com_scriptographer_adm_Dialog_ITEM_PRIVATE_UNIQUE
#define com_scriptographer_adm_Dialog_ITEM_PRIVATE_UNIQUE -7L
#undef com_scriptographer_adm_Dialog_ITEM_FIRST_UNUSED_PRIVATE
#define com_scriptographer_adm_Dialog_ITEM_FIRST_UNUSED_PRIVATE -8L
#undef com_scriptographer_adm_Dialog_CURSOR_IBEAM
#define com_scriptographer_adm_Dialog_CURSOR_IBEAM -1L
#undef com_scriptographer_adm_Dialog_CURSOR_CROSS
#define com_scriptographer_adm_Dialog_CURSOR_CROSS -2L
#undef com_scriptographer_adm_Dialog_CURSOR_WAIT
#define com_scriptographer_adm_Dialog_CURSOR_WAIT -3L
#undef com_scriptographer_adm_Dialog_CURSOR_ARROW
#define com_scriptographer_adm_Dialog_CURSOR_ARROW -4L
#undef com_scriptographer_adm_Dialog_CURSOR_CANCEL
#define com_scriptographer_adm_Dialog_CURSOR_CANCEL -5L
#undef com_scriptographer_adm_Dialog_CURSOR_FINGER
#define com_scriptographer_adm_Dialog_CURSOR_FINGER -6L
#undef com_scriptographer_adm_Dialog_CURSOR_FIST
#define com_scriptographer_adm_Dialog_CURSOR_FIST -7L
#undef com_scriptographer_adm_Dialog_CURSOR_FISTPLUS
#define com_scriptographer_adm_Dialog_CURSOR_FISTPLUS -8L
#undef com_scriptographer_adm_Dialog_CURSOR_HOSTCONTROLS
#define com_scriptographer_adm_Dialog_CURSOR_HOSTCONTROLS -9L
#undef com_scriptographer_adm_Dialog_FONT_DEFAULT
#define com_scriptographer_adm_Dialog_FONT_DEFAULT 0L
#undef com_scriptographer_adm_Dialog_FONT_DIALOG
#define com_scriptographer_adm_Dialog_FONT_DIALOG 1L
#undef com_scriptographer_adm_Dialog_FONT_PALETTE
#define com_scriptographer_adm_Dialog_FONT_PALETTE 2L
#undef com_scriptographer_adm_Dialog_FONT_ITALIC_DIALOG
#define com_scriptographer_adm_Dialog_FONT_ITALIC_DIALOG 3L
#undef com_scriptographer_adm_Dialog_FONT_ITALIC_PALETTE
#define com_scriptographer_adm_Dialog_FONT_ITALIC_PALETTE 4L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_DIALOG
#define com_scriptographer_adm_Dialog_FONT_BOLD_DIALOG 5L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_PALETTE
#define com_scriptographer_adm_Dialog_FONT_BOLD_PALETTE 6L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_DIALOG
#define com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_DIALOG 7L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_PALETTE
#define com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_PALETTE 8L
#undef com_scriptographer_adm_Dialog_FONT_FIXEDWIDTH
#define com_scriptographer_adm_Dialog_FONT_FIXEDWIDTH 9L
#undef com_scriptographer_adm_Dialog_FONT_ITALIC_FIXEDWIDTH
#define com_scriptographer_adm_Dialog_FONT_ITALIC_FIXEDWIDTH 10L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_FIXEDWIDTH
#define com_scriptographer_adm_Dialog_FONT_BOLD_FIXEDWIDTH 11L
#undef com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_FIXEDWIDTH
#define com_scriptographer_adm_Dialog_FONT_BOLD_ITALIC_FIXEDWIDTH 12L
/* Inaccessible static: dialogs */
/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeCreate
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeSetTrackCallbackEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeSetTrackCallbackEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeSetDrawCallbackEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeSetDrawCallbackEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    doModal
 * Signature: (Z)Lcom/scriptographer/adm/Item;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_doModal
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    endModal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_endModal
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeGetSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_nativeGetSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeSetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeGetBounds
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_nativeGetBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeSetBounds
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeSetBounds
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setLocation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setLocation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getLocation
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    localToScreen
 * Signature: (II)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_localToScreen__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    screenToLocal
 * Signature: (II)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_screenToLocal__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    localToScreen
 * Signature: (IIII)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_localToScreen__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    screenToLocal
 * Signature: (IIII)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_screenToLocal__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_invalidate__
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    invalidate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_invalidate__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_update
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getCursor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Dialog_getCursor
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setCursor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setCursor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeGetTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scriptographer_adm_Dialog_nativeGetTitle
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    nativeSetTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_nativeSetTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getFont
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_adm_Dialog_getFont
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setFont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setFont
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getMinimumSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getMinimumSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setMinimumSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setMinimumSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getMaximumSize
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getMaximumSize
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setMaximumSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setMaximumSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getIncrement
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getIncrement
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setIncrement
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setIncrement
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getDefaultItem
 * Signature: ()Lcom/scriptographer/adm/Item;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getDefaultItem
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setDefaultItem
 * Signature: (Lcom/scriptographer/adm/Item;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setDefaultItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    getCancelItem
 * Signature: ()Lcom/scriptographer/adm/Item;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_adm_Dialog_getCancelItem
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setCancelItem
 * Signature: (Lcom/scriptographer/adm/Item;)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setCancelItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isCollapsed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isUpdateEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isUpdateEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setUpdateEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setUpdateEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    isForcedOnScreen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_adm_Dialog_isForcedOnScreen
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_adm_Dialog
 * Method:    setForcedOnScreen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_adm_Dialog_setForcedOnScreen
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
