/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Tool */

#ifndef _Included_com_scriptographer_ai_Tool
#define _Included_com_scriptographer_ai_Tool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scriptographer_ai_Tool
 * Method:    hasPressure
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_scriptographer_ai_Tool_hasPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
