/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_Pathfinder */

#ifndef _Included_com_scriptographer_ai_Pathfinder
#define _Included_com_scriptographer_ai_Pathfinder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scriptographer_ai_Pathfinder_DEFAULT_PRECISION
#define com_scriptographer_ai_Pathfinder_DEFAULT_PRECISION 10.0f
#undef com_scriptographer_ai_Pathfinder_DEFAULT_REMOVE_POINTS
#define com_scriptographer_ai_Pathfinder_DEFAULT_REMOVE_POINTS 0L
#undef com_scriptographer_ai_Pathfinder_DEFAULT_EXTRACT_UNPAINTED
#define com_scriptographer_ai_Pathfinder_DEFAULT_EXTRACT_UNPAINTED 0L
/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    unite
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_unite
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    intersect
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_intersect
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    exclude
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_exclude
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    backMinusFront
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_backMinusFront
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    frontMinusBack
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_frontMinusBack
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    divide
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_divide
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    outline
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_outline
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    trim
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_trim
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    merge
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_merge
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

/*
 * Class:     com_scriptographer_ai_Pathfinder
 * Method:    crop
 * Signature: ([Ljava/lang/Object;FZZ)V
 */
JNIEXPORT void JNICALL Java_com_scriptographer_ai_Pathfinder_crop
  (JNIEnv *, jclass, jobjectArray, jfloat, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
