/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scriptographer_ai_LayerList */

#ifndef _Included_com_scriptographer_ai_LayerList
#define _Included_com_scriptographer_ai_LayerList
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: layerList */
/*
 * Class:     com_scriptographer_ai_LayerList
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_scriptographer_ai_LayerList_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_scriptographer_ai_LayerList
 * Method:    get
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_LayerList_get__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_scriptographer_ai_LayerList
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_scriptographer_ai_LayerList_get__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
