/* DO NOT EDIT THIS FILE - it is machine generated */
#include "stdHeaders.h"
#include <jni.h>
#include "ScriptographerEngine.h"

/* Include headers for all classes */
#include "com_scriptographer_adm_List.h"
#include "com_scriptographer_adm_Item.h"
#include "com_scriptographer_ai_Document.h"
#include "com_scriptographer_ai_PathStyle.h"
#include "com_scriptographer_ai_SegmentList.h"
#include "com_scriptographer_ai_Raster.h"
#include "com_scriptographer_ai_Art.h"
#include "com_scriptographer_ai_Tool.h"
#include "com_scriptographer_ai_Group.h"
#include "com_scriptographer_adm_ListEntry.h"
#include "com_scriptographer_adm_PictureItem.h"
#include "com_scriptographer_ConsoleOutputStream.h"
#include "com_scriptographer_adm_TextItem.h"
#include "com_scriptographer_ai_MenuItem.h"
#include "com_scriptographer_adm_HierarchyList.h"
#include "com_scriptographer_adm_HierarchyListEntry.h"
#include "com_scriptographer_ai_LiveEffect.h"
#include "com_scriptographer_ai_Pathfinder.h"
#include "com_scriptographer_ai_Layer.h"
#include "com_scriptographer_adm_ListBox.h"
#include "com_scriptographer_adm_TextEdit.h"
#include "com_scriptographer_adm_Image.h"
#include "com_scriptographer_ai_DocumentList.h"
#include "com_scriptographer_adm_Tracker.h"
#include "com_scriptographer_adm_Dialog.h"
#include "com_scriptographer_adm_Drawer.h"
#include "com_scriptographer_ai_LayerList.h"
#include "com_scriptographer_adm_ValueItem.h"
#include "com_scriptographer_ai_Path.h"
#include "com_scriptographer_ai_MenuGroup.h"
#include "com_scriptographer_ai_Color.h"
#include "com_scriptographer_adm_ItemGroup.h"
#include "com_scriptographer_ai_ArtSet.h"
#include "com_scriptographer_ai_Curve.h"
#include "com_scriptographer_adm_ScrollBar.h"

/* Native methods for class com_scriptographer_adm_List */
const JNINativeMethod com_scriptographer_adm_List_methods[] = {
	{ "nativeSetTrackCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_List_nativeSetTrackCallbackEnabled },
	{ "nativeSetDrawCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_List_nativeSetDrawCallbackEnabled },
	{ "setEntrySize", "(II)V", &Java_com_scriptographer_adm_List_setEntrySize },
	{ "getEntrySize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_List_getEntrySize },
	{ "setEntryTextRect", "(IIII)V", &Java_com_scriptographer_adm_List_setEntryTextRect },
	{ "getEntryTextRect", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_List_getEntryTextRect },
	{ "createEntry", "(I)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_createEntry },
	{ "removeEntry", "(I)V", &Java_com_scriptographer_adm_List_removeEntry },
	{ "getEntry", "(I)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getEntry__I },
	{ "getEntry", "(Ljava/lang/String;)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getEntry__Ljava_lang_String_2 },
	{ "getEntry", "(II)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getEntry__II },
	{ "getActiveEntry", "()Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getActiveEntry },
	{ "getEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getEntries },
	{ "getSelectedEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_List_getSelectedEntries },
	{ "getNumEntries", "()I", &Java_com_scriptographer_adm_List_getNumEntries },
	{ "setTrackMask", "(I)V", &Java_com_scriptographer_adm_List_setTrackMask },
	{ "getTrackMask", "()I", &Java_com_scriptographer_adm_List_getTrackMask },
	{ "nativeSetBGColor", "(I)V", &Java_com_scriptographer_adm_List_nativeSetBGColor },
	{ "selectByText", "(Ljava/lang/String;)V", &Java_com_scriptographer_adm_List_selectByText }
};

/* Native methods for class com_scriptographer_adm_Item */
const JNINativeMethod com_scriptographer_adm_Item_methods[] = {
	{ "nativeCreate", "(Lcom/scriptographer/adm/Dialog;Ljava/lang/String;Ljava/awt/Rectangle;I)I", &Java_com_scriptographer_adm_Item_nativeCreate },
	{ "nativeDestroy", "()V", &Java_com_scriptographer_adm_Item_nativeDestroy },
	{ "nativeSetTrackCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_Item_nativeSetTrackCallbackEnabled },
	{ "nativeSetDrawCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_Item_nativeSetDrawCallbackEnabled },
	{ "nativeSetStyle", "(I)V", &Java_com_scriptographer_adm_Item_nativeSetStyle },
	{ "isVisible", "()Z", &Java_com_scriptographer_adm_Item_isVisible },
	{ "setVisible", "(Z)V", &Java_com_scriptographer_adm_Item_setVisible },
	{ "isEnabled", "()Z", &Java_com_scriptographer_adm_Item_isEnabled },
	{ "setEnabled", "(Z)V", &Java_com_scriptographer_adm_Item_setEnabled },
	{ "isActive", "()Z", &Java_com_scriptographer_adm_Item_isActive },
	{ "setActive", "(Z)V", &Java_com_scriptographer_adm_Item_setActive },
	{ "isKnown", "()Z", &Java_com_scriptographer_adm_Item_isKnown },
	{ "setKnown", "(Z)V", &Java_com_scriptographer_adm_Item_setKnown },
	{ "wantsFocus", "()Z", &Java_com_scriptographer_adm_Item_wantsFocus },
	{ "setWantsFocus", "(Z)V", &Java_com_scriptographer_adm_Item_setWantsFocus },
	{ "nativeGetSize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Item_nativeGetSize },
	{ "nativeSetSize", "(II)V", &Java_com_scriptographer_adm_Item_nativeSetSize },
	{ "nativeGetBounds", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Item_nativeGetBounds },
	{ "nativeSetBounds", "(IIII)V", &Java_com_scriptographer_adm_Item_nativeSetBounds },
	{ "setLocation", "(II)V", &Java_com_scriptographer_adm_Item_setLocation },
	{ "getLocation", "()Ljava/awt/Point;", &Java_com_scriptographer_adm_Item_getLocation },
	{ "getPreferredSize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Item_getPreferredSize },
	{ "localToScreen", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_Item_localToScreen__II },
	{ "screenToLocal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_Item_screenToLocal__II },
	{ "localToScreen", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Item_localToScreen__IIII },
	{ "screenToLocal", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Item_screenToLocal__IIII },
	{ "invalidate", "()V", &Java_com_scriptographer_adm_Item_invalidate__ },
	{ "invalidate", "(IIII)V", &Java_com_scriptographer_adm_Item_invalidate__IIII },
	{ "update", "()V", &Java_com_scriptographer_adm_Item_update },
	{ "getCursor", "()I", &Java_com_scriptographer_adm_Item_getCursor },
	{ "setCursor", "(I)V", &Java_com_scriptographer_adm_Item_setCursor },
	{ "nativeSetTooltip", "(Ljava/lang/String;)V", &Java_com_scriptographer_adm_Item_nativeSetTooltip },
	{ "isToolTipEnabled", "()Z", &Java_com_scriptographer_adm_Item_isToolTipEnabled },
	{ "setToolTipEnabled", "(Z)V", &Java_com_scriptographer_adm_Item_setToolTipEnabled },
	{ "showToolTip", "(II)V", &Java_com_scriptographer_adm_Item_showToolTip },
	{ "hideToolTip", "()V", &Java_com_scriptographer_adm_Item_hideToolTip }
};

/* Native methods for class com_scriptographer_ai_Document */
const JNINativeMethod com_scriptographer_ai_Document_methods[] = {
	{ "nativeCreate", "(Ljava/io/File;II)I", &Java_com_scriptographer_ai_Document_nativeCreate__Ljava_io_File_2II },
	{ "nativeCreate", "(Ljava/lang/String;FFII)I", &Java_com_scriptographer_ai_Document_nativeCreate__Ljava_lang_String_2FFII },
	{ "getPageOrigin", "()Lcom/scriptographer/ai/Point;", &Java_com_scriptographer_ai_Document_getPageOrigin },
	{ "setPageOrigin", "(Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_ai_Document_setPageOrigin },
	{ "getRulerOrigin", "()Lcom/scriptographer/ai/Point;", &Java_com_scriptographer_ai_Document_getRulerOrigin },
	{ "setRulerOrigin", "(Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_ai_Document_setRulerOrigin },
	{ "getSize", "()Lcom/scriptographer/ai/Point;", &Java_com_scriptographer_ai_Document_getSize },
	{ "setSize", "(FF)V", &Java_com_scriptographer_ai_Document_setSize },
	{ "getCropBox", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_ai_Document_getCropBox },
	{ "setCropBox", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_ai_Document_setCropBox },
	{ "isModified", "()Z", &Java_com_scriptographer_ai_Document_isModified },
	{ "setModified", "(Z)V", &Java_com_scriptographer_ai_Document_setModified },
	{ "getFile", "()Ljava/io/File;", &Java_com_scriptographer_ai_Document_getFile },
	{ "nativeGetFormats", "()[Ljava/lang/String;", &Java_com_scriptographer_ai_Document_nativeGetFormats },
	{ "activate", "()V", &Java_com_scriptographer_ai_Document_activate },
	{ "print", "(I)V", &Java_com_scriptographer_ai_Document_print },
	{ "save", "()V", &Java_com_scriptographer_ai_Document_save },
	{ "close", "()V", &Java_com_scriptographer_ai_Document_close },
	{ "redraw", "()V", &Java_com_scriptographer_ai_Document_redraw },
	{ "copy", "()V", &Java_com_scriptographer_ai_Document_copy },
	{ "cut", "()V", &Java_com_scriptographer_ai_Document_cut },
	{ "paste", "()V", &Java_com_scriptographer_ai_Document_paste },
	{ "write", "(Ljava/io/File;Ljava/lang/String;Z)Z", &Java_com_scriptographer_ai_Document_write }
};

/* Native methods for class com_scriptographer_ai_PathStyle */
const JNINativeMethod com_scriptographer_ai_PathStyle_methods[] = {
	{ "nativeFetch", "(I)V", &Java_com_scriptographer_ai_PathStyle_nativeFetch },
	{ "nativeCommit", "(I[FZ[FZFF[FSSFZZZF)V", &Java_com_scriptographer_ai_PathStyle_nativeCommit }
};

/* Native methods for class com_scriptographer_ai_SegmentList */
const JNINativeMethod com_scriptographer_ai_SegmentList_methods[] = {
	{ "nativeGetLength", "(I)I", &Java_com_scriptographer_ai_SegmentList_nativeGetLength },
	{ "nativeFetch", "(III[F)V", &Java_com_scriptographer_ai_SegmentList_nativeFetch },
	{ "nativeCommit", "(IIFFFFFFZ)V", &Java_com_scriptographer_ai_SegmentList_nativeCommit__IIFFFFFFZ },
	{ "nativeCommit", "(III[F)V", &Java_com_scriptographer_ai_SegmentList_nativeCommit__III_3F },
	{ "nativeInsert", "(IIFFFFFFZ)V", &Java_com_scriptographer_ai_SegmentList_nativeInsert__IIFFFFFFZ },
	{ "nativeInsert", "(III[F)V", &Java_com_scriptographer_ai_SegmentList_nativeInsert__III_3F },
	{ "nativeRemove", "(III)I", &Java_com_scriptographer_ai_SegmentList_nativeRemove },
	{ "nativeReverse", "(I)V", &Java_com_scriptographer_ai_SegmentList_nativeReverse }
};

/* Native methods for class com_scriptographer_ai_Raster */
const JNINativeMethod com_scriptographer_ai_Raster_methods[] = {
	{ "getWidth", "()I", &Java_com_scriptographer_ai_Raster_getWidth },
	{ "setWidth", "(I)V", &Java_com_scriptographer_ai_Raster_setWidth },
	{ "getHeight", "()I", &Java_com_scriptographer_ai_Raster_getHeight },
	{ "setHeight", "(I)V", &Java_com_scriptographer_ai_Raster_setHeight },
	{ "getType", "()I", &Java_com_scriptographer_ai_Raster_getType },
	{ "setType", "(I)V", &Java_com_scriptographer_ai_Raster_setType },
	{ "getPixel", "(II)Lcom/scriptographer/ai/Color;", &Java_com_scriptographer_ai_Raster_getPixel },
	{ "setPixel", "(IILcom/scriptographer/ai/Color;)V", &Java_com_scriptographer_ai_Raster_setPixel },
	{ "finalize", "()V", &Java_com_scriptographer_ai_Raster_finalize }
};

/* Native methods for class com_scriptographer_ai_Art */
const JNINativeMethod com_scriptographer_ai_Art_methods[] = {
	{ "clone", "()Ljava/lang/Object;", &Java_com_scriptographer_ai_Art_clone },
	{ "nativeCreate", "(I)I", &Java_com_scriptographer_ai_Art_nativeCreate },
	{ "nativeRemove", "(I)Z", &Java_com_scriptographer_ai_Art_nativeRemove },
	{ "getFirstChild", "()Lcom/scriptographer/ai/Art;", &Java_com_scriptographer_ai_Art_getFirstChild },
	{ "getLastChild", "()Lcom/scriptographer/ai/Art;", &Java_com_scriptographer_ai_Art_getLastChild },
	{ "getNextSibling", "()Lcom/scriptographer/ai/Art;", &Java_com_scriptographer_ai_Art_getNextSibling },
	{ "getPreviousSibling", "()Lcom/scriptographer/ai/Art;", &Java_com_scriptographer_ai_Art_getPreviousSibling },
	{ "getParent", "()Lcom/scriptographer/ai/Art;", &Java_com_scriptographer_ai_Art_getParent },
	{ "getBounds", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_ai_Art_getBounds },
	{ "setName", "(Ljava/lang/String;)V", &Java_com_scriptographer_ai_Art_setName },
	{ "getName", "()Ljava/lang/String;", &Java_com_scriptographer_ai_Art_getName },
	{ "isCenterVisible", "()Z", &Java_com_scriptographer_ai_Art_isCenterVisible },
	{ "setCenterVisible", "(Z)V", &Java_com_scriptographer_ai_Art_setCenterVisible },
	{ "setUserAttributes", "(II)V", &Java_com_scriptographer_ai_Art_setUserAttributes },
	{ "getUserAttributes", "(I)I", &Java_com_scriptographer_ai_Art_getUserAttributes },
	{ "append", "(Lcom/scriptographer/ai/Art;)Z", &Java_com_scriptographer_ai_Art_append },
	{ "moveAbove", "(Lcom/scriptographer/ai/Art;)Z", &Java_com_scriptographer_ai_Art_moveAbove },
	{ "moveBelow", "(Lcom/scriptographer/ai/Art;)Z", &Java_com_scriptographer_ai_Art_moveBelow },
	{ "transform", "(Ljava/awt/geom/AffineTransform;I)V", &Java_com_scriptographer_ai_Art_transform }
};

/* Native methods for class com_scriptographer_ai_Tool */
const JNINativeMethod com_scriptographer_ai_Tool_methods[] = {
	{ "hasPressure", "()Z", &Java_com_scriptographer_ai_Tool_hasPressure }
};

/* Native methods for class com_scriptographer_ai_Group */
const JNINativeMethod com_scriptographer_ai_Group_methods[] = {
	{ "isClipped", "()Z", &Java_com_scriptographer_ai_Group_isClipped },
	{ "setClipped", "(Z)V", &Java_com_scriptographer_ai_Group_setClipped }
};

/* Native methods for class com_scriptographer_adm_ListEntry */
const JNINativeMethod com_scriptographer_adm_ListEntry_methods[] = {
	{ "nativeCreate", "(Lcom/scriptographer/adm/List;)I", &Java_com_scriptographer_adm_ListEntry_nativeCreate },
	{ "nativeDestroy", "()V", &Java_com_scriptographer_adm_ListEntry_nativeDestroy },
	{ "getIndex", "()I", &Java_com_scriptographer_adm_ListEntry_getIndex },
	{ "getList", "()Lcom/scriptographer/adm/List;", &Java_com_scriptographer_adm_ListEntry_getList },
	{ "setSelected", "(Z)V", &Java_com_scriptographer_adm_ListEntry_setSelected },
	{ "isSelected", "()Z", &Java_com_scriptographer_adm_ListEntry_isSelected },
	{ "makeInBounds", "()V", &Java_com_scriptographer_adm_ListEntry_makeInBounds },
	{ "isInBounds", "()Z", &Java_com_scriptographer_adm_ListEntry_isInBounds },
	{ "setEnabled", "(Z)V", &Java_com_scriptographer_adm_ListEntry_setEnabled },
	{ "isEnabled", "()Z", &Java_com_scriptographer_adm_ListEntry_isEnabled },
	{ "setActive", "(Z)V", &Java_com_scriptographer_adm_ListEntry_setActive },
	{ "isActive", "()Z", &Java_com_scriptographer_adm_ListEntry_isActive },
	{ "setChecked", "(Z)V", &Java_com_scriptographer_adm_ListEntry_setChecked },
	{ "isChecked", "()Z", &Java_com_scriptographer_adm_ListEntry_isChecked },
	{ "setSeparator", "(Z)V", &Java_com_scriptographer_adm_ListEntry_setSeparator },
	{ "isSeparator", "()Z", &Java_com_scriptographer_adm_ListEntry_isSeparator },
	{ "getLocalRect", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_ListEntry_getLocalRect },
	{ "getBounds", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_ListEntry_getBounds },
	{ "localToScreen", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_ListEntry_localToScreen__II },
	{ "screenToLocal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_ListEntry_screenToLocal__II },
	{ "localToScreen", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_ListEntry_localToScreen__IIII },
	{ "screenToLocal", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_ListEntry_screenToLocal__IIII },
	{ "invalidate", "()V", &Java_com_scriptographer_adm_ListEntry_invalidate__ },
	{ "invalidate", "(IIII)V", &Java_com_scriptographer_adm_ListEntry_invalidate__IIII },
	{ "update", "()V", &Java_com_scriptographer_adm_ListEntry_update },
	{ "nativeSetPicture", "(I)V", &Java_com_scriptographer_adm_ListEntry_nativeSetPicture },
	{ "nativeSetSelectedPicture", "(I)V", &Java_com_scriptographer_adm_ListEntry_nativeSetSelectedPicture },
	{ "nativeSetDisabledPicture", "(I)V", &Java_com_scriptographer_adm_ListEntry_nativeSetDisabledPicture },
	{ "nativeSetText", "(Ljava/lang/String;)V", &Java_com_scriptographer_adm_ListEntry_nativeSetText }
};

/* Native methods for class com_scriptographer_adm_PictureItem */
const JNINativeMethod com_scriptographer_adm_PictureItem_methods[] = {
	{ "nativeSetPicture", "(I)V", &Java_com_scriptographer_adm_PictureItem_nativeSetPicture },
	{ "nativeSetRolloverPicture", "(I)V", &Java_com_scriptographer_adm_PictureItem_nativeSetRolloverPicture },
	{ "nativeSetSelectedPicture", "(I)V", &Java_com_scriptographer_adm_PictureItem_nativeSetSelectedPicture },
	{ "nativeSetDisabledPicture", "(I)V", &Java_com_scriptographer_adm_PictureItem_nativeSetDisabledPicture }
};

/* Native methods for class com_scriptographer_ConsoleOutputStream */
const JNINativeMethod com_scriptographer_ConsoleOutputStream_methods[] = {
	{ "writeLine", "(Ljava/lang/String;)V", &Java_com_scriptographer_ConsoleOutputStream_writeLine }
};

/* Native methods for class com_scriptographer_adm_TextItem */
const JNINativeMethod com_scriptographer_adm_TextItem_methods[] = {
	{ "getFont", "()I", &Java_com_scriptographer_adm_TextItem_getFont },
	{ "setFont", "(I)V", &Java_com_scriptographer_adm_TextItem_setFont },
	{ "nativeSetText", "(Ljava/lang/String;)V", &Java_com_scriptographer_adm_TextItem_nativeSetText },
	{ "setJustify", "(I)V", &Java_com_scriptographer_adm_TextItem_setJustify },
	{ "getJustify", "()I", &Java_com_scriptographer_adm_TextItem_getJustify },
	{ "setUnits", "(I)V", &Java_com_scriptographer_adm_TextItem_setUnits },
	{ "getUnits", "()I", &Java_com_scriptographer_adm_TextItem_getUnits },
	{ "setShowUnits", "(Z)V", &Java_com_scriptographer_adm_TextItem_setShowUnits },
	{ "getShowUnits", "()Z", &Java_com_scriptographer_adm_TextItem_getShowUnits }
};

/* Native methods for class com_scriptographer_ai_MenuItem */
const JNINativeMethod com_scriptographer_ai_MenuItem_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I", &Java_com_scriptographer_ai_MenuItem_nativeCreate },
	{ "nativeRemove", "(I)I", &Java_com_scriptographer_ai_MenuItem_nativeRemove },
	{ "nativeSetText", "(Ljava/lang/String;)V", &Java_com_scriptographer_ai_MenuItem_nativeSetText },
	{ "setOption", "(I)V", &Java_com_scriptographer_ai_MenuItem_setOption },
	{ "getOptions", "()I", &Java_com_scriptographer_ai_MenuItem_getOptions },
	{ "setEnabled", "(Z)V", &Java_com_scriptographer_ai_MenuItem_setEnabled },
	{ "isEnabled", "()Z", &Java_com_scriptographer_ai_MenuItem_isEnabled },
	{ "setChecked", "(Z)V", &Java_com_scriptographer_ai_MenuItem_setChecked },
	{ "isChecked", "()Z", &Java_com_scriptographer_ai_MenuItem_isChecked }
};

/* Native methods for class com_scriptographer_adm_HierarchyList */
const JNINativeMethod com_scriptographer_adm_HierarchyList_methods[] = {
	{ "setEntrySize", "(IIZ)V", &Java_com_scriptographer_adm_HierarchyList_setEntrySize },
	{ "setEntryTextRect", "(IIIIZ)V", &Java_com_scriptographer_adm_HierarchyList_setEntryTextRect },
	{ "getNonLeafEntryWidth", "()I", &Java_com_scriptographer_adm_HierarchyList_getNonLeafEntryWidth },
	{ "setNonLeafEntryTextRect", "(IIIIZ)V", &Java_com_scriptographer_adm_HierarchyList_setNonLeafEntryTextRect },
	{ "getNonLeafEntryTextRect", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_HierarchyList_getNonLeafEntryTextRect },
	{ "getLeafEntry", "(II)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getLeafEntry },
	{ "getActiveLeafEntry", "()Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getActiveLeafEntry },
	{ "getAllSelectedEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getAllSelectedEntries },
	{ "getAllUnnestedSelectedEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getAllUnnestedSelectedEntries },
	{ "getParentEntry", "()Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getParentEntry },
	{ "getLocalRect", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_HierarchyList_getLocalRect },
	{ "localToScreen", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_HierarchyList_localToScreen },
	{ "screenToLocal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_HierarchyList_screenToLocal },
	{ "localToGlobal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_HierarchyList_localToGlobal__II },
	{ "globalToLocal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_HierarchyList_globalToLocal__II },
	{ "localToGlobal", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_HierarchyList_localToGlobal__IIII },
	{ "globalToLocal", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_HierarchyList_globalToLocal__IIII },
	{ "setIndentationWidth", "(IZ)V", &Java_com_scriptographer_adm_HierarchyList_setIndentationWidth },
	{ "getIndentationWidth", "()I", &Java_com_scriptographer_adm_HierarchyList_getIndentationWidth },
	{ "setLocalLeftMargin", "(I)V", &Java_com_scriptographer_adm_HierarchyList_setLocalLeftMargin },
	{ "getLocalLeftMargin", "()I", &Java_com_scriptographer_adm_HierarchyList_getLocalLeftMargin },
	{ "getGlobalLeftMargin", "()I", &Java_com_scriptographer_adm_HierarchyList_getGlobalLeftMargin },
	{ "setDivided", "(ZZ)V", &Java_com_scriptographer_adm_HierarchyList_setDivided },
	{ "isDivided", "()Z", &Java_com_scriptographer_adm_HierarchyList_isDivided },
	{ "setFlags", "(IZ)V", &Java_com_scriptographer_adm_HierarchyList_setFlags },
	{ "getFlags", "()I", &Java_com_scriptographer_adm_HierarchyList_getFlags },
	{ "invalidate", "()V", &Java_com_scriptographer_adm_HierarchyList_invalidate },
	{ "getLeafEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getLeafEntries },
	{ "getLeafIndex", "(Lcom/scriptographer/adm/ListEntry;)I", &Java_com_scriptographer_adm_HierarchyList_getLeafIndex },
	{ "swapEntries", "(II)V", &Java_com_scriptographer_adm_HierarchyList_swapEntries },
	{ "insertEntry", "(Lcom/scriptographer/adm/ListEntry;I)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_insertEntry },
	{ "unlinkEntry", "(I)Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_unlinkEntry },
	{ "deselectAll", "()V", &Java_com_scriptographer_adm_HierarchyList_deselectAll },
	{ "getExpandedEntries", "()[Lcom/scriptographer/adm/ListEntry;", &Java_com_scriptographer_adm_HierarchyList_getExpandedEntries },
	{ "getExpandedIndex", "(Lcom/scriptographer/adm/ListEntry;)I", &Java_com_scriptographer_adm_HierarchyList_getExpandedIndex }
};

/* Native methods for class com_scriptographer_adm_HierarchyListEntry */
const JNINativeMethod com_scriptographer_adm_HierarchyListEntry_methods[] = {
	{ "getItem", "()Lcom/scriptographer/adm/Item;", &Java_com_scriptographer_adm_HierarchyListEntry_getItem },
	{ "getChildList", "()Lcom/scriptographer/adm/HierarchyList;", &Java_com_scriptographer_adm_HierarchyListEntry_getChildList },
	{ "createChildList", "()Lcom/scriptographer/adm/HierarchyList;", &Java_com_scriptographer_adm_HierarchyListEntry_createChildList },
	{ "deleteChildList", "()V", &Java_com_scriptographer_adm_HierarchyListEntry_deleteChildList },
	{ "setExpanded", "(Z)V", &Java_com_scriptographer_adm_HierarchyListEntry_setExpanded },
	{ "isExpanded", "()Z", &Java_com_scriptographer_adm_HierarchyListEntry_isExpanded },
	{ "setEntryNameHidden", "(Z)V", &Java_com_scriptographer_adm_HierarchyListEntry_setEntryNameHidden },
	{ "isEntryNameHidden", "()Z", &Java_com_scriptographer_adm_HierarchyListEntry_isEntryNameHidden },
	{ "setChildSelectable", "(Z)V", &Java_com_scriptographer_adm_HierarchyListEntry_setChildSelectable },
	{ "isChildSelectable", "()Z", &Java_com_scriptographer_adm_HierarchyListEntry_isChildSelectable },
	{ "getDepth", "()I", &Java_com_scriptographer_adm_HierarchyListEntry_getDepth },
	{ "getVisualDepth", "()I", &Java_com_scriptographer_adm_HierarchyListEntry_getVisualDepth },
	{ "areChildrenSelected", "()Z", &Java_com_scriptographer_adm_HierarchyListEntry_areChildrenSelected },
	{ "getExpandArrowRect", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_adm_HierarchyListEntry_getExpandArrowRect },
	{ "setTextRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_HierarchyListEntry_setTextRect },
	{ "getEntryItem", "()Lcom/scriptographer/adm/Item;", &Java_com_scriptographer_adm_HierarchyListEntry_getEntryItem },
	{ "setEntryItem", "(Lcom/scriptographer/adm/Item;)V", &Java_com_scriptographer_adm_HierarchyListEntry_setEntryItem },
	{ "nativeSetFont", "(I)V", &Java_com_scriptographer_adm_HierarchyListEntry_nativeSetFont },
	{ "nativeSetTextColor", "(I)V", &Java_com_scriptographer_adm_HierarchyListEntry_nativeSetTextColor },
	{ "nativeSetBGColor", "(I)V", &Java_com_scriptographer_adm_HierarchyListEntry_nativeSetBGColor },
	{ "nativeSetDividerColor", "(I)V", &Java_com_scriptographer_adm_HierarchyListEntry_nativeSetDividerColor }
};

/* Native methods for class com_scriptographer_ai_LiveEffect */
const JNINativeMethod com_scriptographer_ai_LiveEffect_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;IIIII)I", &Java_com_scriptographer_ai_LiveEffect_nativeCreate },
	{ "nativeAddMenuItem", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/scriptographer/ai/MenuItem;", &Java_com_scriptographer_ai_LiveEffect_nativeAddMenuItem },
	{ "updateParameters", "(Ljava/util/Map;)Z", &Java_com_scriptographer_ai_LiveEffect_updateParameters },
	{ "getMenuItem", "(Ljava/util/Map;)Ljava/lang/Object;", &Java_com_scriptographer_ai_LiveEffect_getMenuItem }
};

/* Native methods for class com_scriptographer_ai_Pathfinder */
const JNINativeMethod com_scriptographer_ai_Pathfinder_methods[] = {
	{ "unite", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_unite },
	{ "intersect", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_intersect },
	{ "exclude", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_exclude },
	{ "backMinusFront", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_backMinusFront },
	{ "frontMinusBack", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_frontMinusBack },
	{ "divide", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_divide },
	{ "outline", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_outline },
	{ "trim", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_trim },
	{ "merge", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_merge },
	{ "crop", "([Ljava/lang/Object;FZZ)V", &Java_com_scriptographer_ai_Pathfinder_crop }
};

/* Native methods for class com_scriptographer_ai_Layer */
const JNINativeMethod com_scriptographer_ai_Layer_methods[] = {
	{ "setVisible", "(Z)V", &Java_com_scriptographer_ai_Layer_setVisible },
	{ "isVisible", "()Z", &Java_com_scriptographer_ai_Layer_isVisible },
	{ "setPreview", "(Z)V", &Java_com_scriptographer_ai_Layer_setPreview },
	{ "getPreview", "()Z", &Java_com_scriptographer_ai_Layer_getPreview },
	{ "setEditable", "(Z)V", &Java_com_scriptographer_ai_Layer_setEditable },
	{ "isEditable", "()Z", &Java_com_scriptographer_ai_Layer_isEditable },
	{ "setPrinted", "(Z)V", &Java_com_scriptographer_ai_Layer_setPrinted },
	{ "isPrinted", "()Z", &Java_com_scriptographer_ai_Layer_isPrinted },
	{ "setSelected", "(Z)V", &Java_com_scriptographer_ai_Layer_setSelected },
	{ "isSelected", "()Z", &Java_com_scriptographer_ai_Layer_isSelected },
	{ "setColor", "(Lcom/scriptographer/ai/Color;)V", &Java_com_scriptographer_ai_Layer_setColor },
	{ "getColor", "()Lcom/scriptographer/ai/RGBColor;", &Java_com_scriptographer_ai_Layer_getColor }
};

/* Native methods for class com_scriptographer_adm_ListBox */
const JNINativeMethod com_scriptographer_adm_ListBox_methods[] = {
	{ "nativeGetList", "()Lcom/scriptographer/adm/List;", &Java_com_scriptographer_adm_ListBox_nativeGetList }
};

/* Native methods for class com_scriptographer_adm_TextEdit */
const JNINativeMethod com_scriptographer_adm_TextEdit_methods[] = {
	{ "setMaxLength", "(I)V", &Java_com_scriptographer_adm_TextEdit_setMaxLength },
	{ "getMaxLength", "()I", &Java_com_scriptographer_adm_TextEdit_getMaxLength },
	{ "setSelectionRange", "(II)V", &Java_com_scriptographer_adm_TextEdit_setSelectionRange },
	{ "getSelectionRange", "()[I", &Java_com_scriptographer_adm_TextEdit_getSelectionRange },
	{ "selectAll", "()V", &Java_com_scriptographer_adm_TextEdit_selectAll },
	{ "setAllowMath", "(Z)V", &Java_com_scriptographer_adm_TextEdit_setAllowMath },
	{ "getAllowMath", "()Z", &Java_com_scriptographer_adm_TextEdit_getAllowMath },
	{ "setAllowUnits", "(Z)V", &Java_com_scriptographer_adm_TextEdit_setAllowUnits },
	{ "getAllowUnits", "()Z", &Java_com_scriptographer_adm_TextEdit_getAllowUnits }
};

/* Native methods for class com_scriptographer_adm_Image */
const JNINativeMethod com_scriptographer_adm_Image_methods[] = {
	{ "nativeCreate", "(III)I", &Java_com_scriptographer_adm_Image_nativeCreate },
	{ "nativeDestroy", "(II)V", &Java_com_scriptographer_adm_Image_nativeDestroy },
	{ "nativeSetPixels", "([IIII)V", &Java_com_scriptographer_adm_Image_nativeSetPixels___3IIII },
	{ "nativeGetPixels", "([IIII)V", &Java_com_scriptographer_adm_Image_nativeGetPixels },
	{ "nativeSetPixels", "(II)V", &Java_com_scriptographer_adm_Image_nativeSetPixels__II },
	{ "nativeCreateIcon", "()I", &Java_com_scriptographer_adm_Image_nativeCreateIcon },
	{ "nativeBeginDrawer", "()I", &Java_com_scriptographer_adm_Image_nativeBeginDrawer },
	{ "nativeEndDrawer", "()V", &Java_com_scriptographer_adm_Image_nativeEndDrawer }
};

/* Native methods for class com_scriptographer_ai_DocumentList */
const JNINativeMethod com_scriptographer_ai_DocumentList_methods[] = {
	{ "getLength", "()I", &Java_com_scriptographer_ai_DocumentList_getLength },
	{ "getDocumentHandle", "(I)I", &Java_com_scriptographer_ai_DocumentList_getDocumentHandle }
};

/* Native methods for class com_scriptographer_adm_Tracker */
const JNINativeMethod com_scriptographer_adm_Tracker_methods[] = {
	{ "getCurrentModifiers", "()I", &Java_com_scriptographer_adm_Tracker_getCurrentModifiers },
	{ "abort", "()V", &Java_com_scriptographer_adm_Tracker_abort },
	{ "releaseMouseCapture", "()V", &Java_com_scriptographer_adm_Tracker_releaseMouseCapture }
};

/* Native methods for class com_scriptographer_adm_Dialog */
const JNINativeMethod com_scriptographer_adm_Dialog_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;II)V", &Java_com_scriptographer_adm_Dialog_nativeCreate },
	{ "nativeDestroy", "()V", &Java_com_scriptographer_adm_Dialog_nativeDestroy },
	{ "nativeSetTrackCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_Dialog_nativeSetTrackCallbackEnabled },
	{ "nativeSetDrawCallbackEnabled", "(Z)V", &Java_com_scriptographer_adm_Dialog_nativeSetDrawCallbackEnabled },
	{ "doModal", "(Z)Lcom/scriptographer/adm/Item;", &Java_com_scriptographer_adm_Dialog_doModal },
	{ "endModal", "()V", &Java_com_scriptographer_adm_Dialog_endModal },
	{ "isVisible", "()Z", &Java_com_scriptographer_adm_Dialog_isVisible },
	{ "setVisible", "(Z)V", &Java_com_scriptographer_adm_Dialog_setVisible },
	{ "isEnabled", "()Z", &Java_com_scriptographer_adm_Dialog_isEnabled },
	{ "setEnabled", "(Z)V", &Java_com_scriptographer_adm_Dialog_setEnabled },
	{ "isActive", "()Z", &Java_com_scriptographer_adm_Dialog_isActive },
	{ "setActive", "(Z)V", &Java_com_scriptographer_adm_Dialog_setActive },
	{ "nativeGetSize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Dialog_nativeGetSize },
	{ "nativeSetSize", "(II)V", &Java_com_scriptographer_adm_Dialog_nativeSetSize },
	{ "nativeGetBounds", "()Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Dialog_nativeGetBounds },
	{ "nativeSetBounds", "(IIII)V", &Java_com_scriptographer_adm_Dialog_nativeSetBounds },
	{ "setLocation", "(II)V", &Java_com_scriptographer_adm_Dialog_setLocation },
	{ "getLocation", "()Ljava/awt/Point;", &Java_com_scriptographer_adm_Dialog_getLocation },
	{ "localToScreen", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_Dialog_localToScreen__II },
	{ "screenToLocal", "(II)Ljava/awt/Point;", &Java_com_scriptographer_adm_Dialog_screenToLocal__II },
	{ "localToScreen", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Dialog_localToScreen__IIII },
	{ "screenToLocal", "(IIII)Ljava/awt/Rectangle;", &Java_com_scriptographer_adm_Dialog_screenToLocal__IIII },
	{ "invalidate", "()V", &Java_com_scriptographer_adm_Dialog_invalidate__ },
	{ "invalidate", "(IIII)V", &Java_com_scriptographer_adm_Dialog_invalidate__IIII },
	{ "update", "()V", &Java_com_scriptographer_adm_Dialog_update },
	{ "getCursor", "()I", &Java_com_scriptographer_adm_Dialog_getCursor },
	{ "setCursor", "(I)V", &Java_com_scriptographer_adm_Dialog_setCursor },
	{ "nativeGetTitle", "()Ljava/lang/String;", &Java_com_scriptographer_adm_Dialog_nativeGetTitle },
	{ "nativeSetTitle", "(Ljava/lang/String;)V", &Java_com_scriptographer_adm_Dialog_nativeSetTitle },
	{ "getFont", "()I", &Java_com_scriptographer_adm_Dialog_getFont },
	{ "setFont", "(I)V", &Java_com_scriptographer_adm_Dialog_setFont },
	{ "getMinimumSize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Dialog_getMinimumSize },
	{ "setMinimumSize", "(II)V", &Java_com_scriptographer_adm_Dialog_setMinimumSize },
	{ "getMaximumSize", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Dialog_getMaximumSize },
	{ "setMaximumSize", "(II)V", &Java_com_scriptographer_adm_Dialog_setMaximumSize },
	{ "getIncrement", "()Ljava/awt/Dimension;", &Java_com_scriptographer_adm_Dialog_getIncrement },
	{ "setIncrement", "(II)V", &Java_com_scriptographer_adm_Dialog_setIncrement },
	{ "getDefaultItem", "()Lcom/scriptographer/adm/Item;", &Java_com_scriptographer_adm_Dialog_getDefaultItem },
	{ "setDefaultItem", "(Lcom/scriptographer/adm/Item;)V", &Java_com_scriptographer_adm_Dialog_setDefaultItem },
	{ "getCancelItem", "()Lcom/scriptographer/adm/Item;", &Java_com_scriptographer_adm_Dialog_getCancelItem },
	{ "setCancelItem", "(Lcom/scriptographer/adm/Item;)V", &Java_com_scriptographer_adm_Dialog_setCancelItem },
	{ "isCollapsed", "()Z", &Java_com_scriptographer_adm_Dialog_isCollapsed },
	{ "isUpdateEnabled", "()Z", &Java_com_scriptographer_adm_Dialog_isUpdateEnabled },
	{ "setUpdateEnabled", "(Z)V", &Java_com_scriptographer_adm_Dialog_setUpdateEnabled },
	{ "isForcedOnScreen", "()Z", &Java_com_scriptographer_adm_Dialog_isForcedOnScreen },
	{ "setForcedOnScreen", "(Z)V", &Java_com_scriptographer_adm_Dialog_setForcedOnScreen }
};

/* Native methods for class com_scriptographer_adm_Drawer */
const JNINativeMethod com_scriptographer_adm_Drawer_methods[] = {
	{ "clear", "()V", &Java_com_scriptographer_adm_Drawer_clear },
	{ "getBoundsRect", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_adm_Drawer_getBoundsRect },
	{ "getClipRect", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_adm_Drawer_getClipRect },
	{ "setClipRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_setClipRect },
	{ "intersectClipRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_intersectClipRect },
	{ "unionClipRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_unionClipRect },
	{ "subtractClipRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_subtractClipRect },
	{ "setClipPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_setClipPolygon },
	{ "intersectClipPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_intersectClipPolygon },
	{ "unionClipPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_unionClipPolygon },
	{ "subtractClipPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_subtractClipPolygon },
	{ "getOrigin", "()Lcom/scriptographer/ai/Point;", &Java_com_scriptographer_adm_Drawer_getOrigin },
	{ "setOrigin", "(Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_setOrigin },
	{ "getColor", "()Ljava/awt/Color;", &Java_com_scriptographer_adm_Drawer_getColor },
	{ "setColor", "(Ljava/awt/Color;)V", &Java_com_scriptographer_adm_Drawer_setColor__Ljava_awt_Color_2 },
	{ "setColor", "(I)V", &Java_com_scriptographer_adm_Drawer_setColor__I },
	{ "getDrawMode", "()I", &Java_com_scriptographer_adm_Drawer_getDrawMode },
	{ "setDrawMode", "(I)V", &Java_com_scriptographer_adm_Drawer_setDrawMode },
	{ "getFont", "()I", &Java_com_scriptographer_adm_Drawer_getFont },
	{ "setFont", "(I)V", &Java_com_scriptographer_adm_Drawer_setFont },
	{ "drawLine", "(IIII)V", &Java_com_scriptographer_adm_Drawer_drawLine },
	{ "drawPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_drawPolygon },
	{ "fillPolygon", "([Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_fillPolygon },
	{ "drawRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawRect },
	{ "fillRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_fillRect },
	{ "clearRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_clearRect },
	{ "drawSunkenRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawSunkenRect },
	{ "drawRaisedRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawRaisedRect },
	{ "invertRect", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_invertRect },
	{ "drawOval", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawOval },
	{ "fillOval", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_fillOval },
	{ "drawImage", "(Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_drawImage },
	{ "drawImageCentered", "(Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawImageCentered },
	{ "drawRecoloredImage", "(Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Point;I)V", &Java_com_scriptographer_adm_Drawer_drawRecoloredImage },
	{ "drawRecoloredImageCentered", "(Lcom/scriptographer/adm/Image;Lcom/scriptographer/ai/Rectangle;I)V", &Java_com_scriptographer_adm_Drawer_drawRecoloredImageCentered },
	{ "getTextWidth", "(Ljava/lang/String;)I", &Java_com_scriptographer_adm_Drawer_getTextWidth },
	{ "drawText", "(Ljava/lang/String;Lcom/scriptographer/ai/Point;)V", &Java_com_scriptographer_adm_Drawer_drawText },
	{ "drawTextLeft", "(Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawTextLeft },
	{ "drawTextCentered", "(Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawTextCentered },
	{ "drawTextRight", "(Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawTextRight },
	{ "drawTextInABox", "(Ljava/lang/String;Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawTextInABox },
	{ "drawUpArrow", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawUpArrow },
	{ "drawDownArrow", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawDownArrow },
	{ "drawLeftArrow", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawLeftArrow },
	{ "drawRightArrow", "(Lcom/scriptographer/ai/Rectangle;)V", &Java_com_scriptographer_adm_Drawer_drawRightArrow },
	{ "getFontInfo", "()Lcom/scriptographer/adm/Drawer$FontInfo;", &Java_com_scriptographer_adm_Drawer_getFontInfo__ },
	{ "getFontInfo", "(I)Lcom/scriptographer/adm/Drawer$FontInfo;", &Java_com_scriptographer_adm_Drawer_getFontInfo__I },
	{ "getUpdateRect", "()Lcom/scriptographer/ai/Rectangle;", &Java_com_scriptographer_adm_Drawer_getUpdateRect },
	{ "getTextRectHeight", "(ILjava/lang/String;)I", &Java_com_scriptographer_adm_Drawer_getTextRectHeight }
};

/* Native methods for class com_scriptographer_ai_LayerList */
const JNINativeMethod com_scriptographer_ai_LayerList_methods[] = {
	{ "getLength", "()I", &Java_com_scriptographer_ai_LayerList_getLength },
	{ "get", "(I)Ljava/lang/Object;", &Java_com_scriptographer_ai_LayerList_get__I },
	{ "get", "(Ljava/lang/String;)Ljava/lang/Object;", &Java_com_scriptographer_ai_LayerList_get__Ljava_lang_String_2 }
};

/* Native methods for class com_scriptographer_adm_ValueItem */
const JNINativeMethod com_scriptographer_adm_ValueItem_methods[] = {
	{ "getValueRange", "()[F", &Java_com_scriptographer_adm_ValueItem_getValueRange },
	{ "setValueRange", "(FF)V", &Java_com_scriptographer_adm_ValueItem_setValueRange },
	{ "getPrecision", "()I", &Java_com_scriptographer_adm_ValueItem_getPrecision },
	{ "setPrecision", "(I)V", &Java_com_scriptographer_adm_ValueItem_setPrecision },
	{ "getBooleanValue", "()Z", &Java_com_scriptographer_adm_ValueItem_getBooleanValue },
	{ "setBooleanValue", "(Z)V", &Java_com_scriptographer_adm_ValueItem_setBooleanValue },
	{ "getFloatValue", "()F", &Java_com_scriptographer_adm_ValueItem_getFloatValue },
	{ "setFloatValue", "(F)V", &Java_com_scriptographer_adm_ValueItem_setFloatValue }
};

/* Native methods for class com_scriptographer_ai_Path */
const JNINativeMethod com_scriptographer_ai_Path_methods[] = {
	{ "createRectangle", "(Lcom/scriptographer/ai/Rectangle;)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createRectangle },
	{ "createRoundRectangle", "(Lcom/scriptographer/ai/Rectangle;FF)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createRoundRectangle },
	{ "createOval", "(Lcom/scriptographer/ai/Rectangle;Z)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createOval },
	{ "createRegularPolygon", "(ILcom/scriptographer/ai/Point;F)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createRegularPolygon },
	{ "createStar", "(ILcom/scriptographer/ai/Point;FF)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createStar },
	{ "createSpiral", "(Lcom/scriptographer/ai/Point;Lcom/scriptographer/ai/Point;FIZ)Lcom/scriptographer/ai/Path;", &Java_com_scriptographer_ai_Path_createSpiral },
	{ "getClosed", "()Z", &Java_com_scriptographer_ai_Path_getClosed },
	{ "setClosed", "(Z)V", &Java_com_scriptographer_ai_Path_setClosed },
	{ "getGuide", "()Z", &Java_com_scriptographer_ai_Path_getGuide },
	{ "setGuide", "(Z)V", &Java_com_scriptographer_ai_Path_setGuide },
	{ "getTabletData", "()[Lcom/scriptographer/ai/TabletValue;", &Java_com_scriptographer_ai_Path_getTabletData },
	{ "setTabletData", "([Lcom/scriptographer/ai/TabletValue;)V", &Java_com_scriptographer_ai_Path_setTabletData },
	{ "getLength", "(F)F", &Java_com_scriptographer_ai_Path_getLength },
	{ "getArea", "()F", &Java_com_scriptographer_ai_Path_getArea },
	{ "nativePointsToCurves", "(IFFIF)I", &Java_com_scriptographer_ai_Path_nativePointsToCurves },
	{ "nativeCurvesToPoints", "(IFF)I", &Java_com_scriptographer_ai_Path_nativeCurvesToPoints },
	{ "nativeReduceSegments", "(IF)V", &Java_com_scriptographer_ai_Path_nativeReduceSegments },
	{ "nativeSplit", "(IIF)I", &Java_com_scriptographer_ai_Path_nativeSplit },
	{ "hitTest", "(Lcom/scriptographer/ai/Point;F)Lcom/scriptographer/ai/SegmentPosition;", &Java_com_scriptographer_ai_Path_hitTest },
	{ "getPositionWithLength", "(FF)Lcom/scriptographer/ai/SegmentPosition;", &Java_com_scriptographer_ai_Path_getPositionWithLength }
};

/* Native methods for class com_scriptographer_ai_MenuGroup */
const JNINativeMethod com_scriptographer_ai_MenuGroup_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;II)I", &Java_com_scriptographer_ai_MenuGroup_nativeCreate },
	{ "setOption", "(I)V", &Java_com_scriptographer_ai_MenuGroup_setOption },
	{ "getOptions", "()I", &Java_com_scriptographer_ai_MenuGroup_getOptions }
};

/* Native methods for class com_scriptographer_ai_Color */
const JNINativeMethod com_scriptographer_ai_Color_methods[] = {
	{ "convert", "(I)Lcom/scriptographer/ai/Color;", &Java_com_scriptographer_ai_Color_convert },
	{ "getWSProfile", "(I)Ljava/awt/color/ICC_Profile;", &Java_com_scriptographer_ai_Color_getWSProfile }
};

/* Native methods for class com_scriptographer_adm_ItemGroup */
const JNINativeMethod com_scriptographer_adm_ItemGroup_methods[] = {
	{ "addItem", "(Lcom/scriptographer/adm/Item;)V", &Java_com_scriptographer_adm_ItemGroup_addItem }
};

/* Native methods for class com_scriptographer_ai_ArtSet */
const JNINativeMethod com_scriptographer_ai_ArtSet_methods[] = {
	{ "nativeGetSelected", "()[Ljava/lang/Object;", &Java_com_scriptographer_ai_ArtSet_nativeGetSelected },
	{ "nativeGetMatching", "(Ljava/lang/Class;Ljava/util/Map;)[Ljava/lang/Object;", &Java_com_scriptographer_ai_ArtSet_nativeGetMatching },
	{ "nativeGetLayer", "(I)[Ljava/lang/Object;", &Java_com_scriptographer_ai_ArtSet_nativeGetLayer },
	{ "nativeInvert", "([Ljava/lang/Object;)[Ljava/lang/Object;", &Java_com_scriptographer_ai_ArtSet_nativeInvert }
};

/* Native methods for class com_scriptographer_ai_Curve */
const JNINativeMethod com_scriptographer_ai_Curve_methods[] = {
	{ "nativeGetLength", "(FFFFFFFFF)F", &Java_com_scriptographer_ai_Curve_nativeGetLength },
	{ "nativeGetPartLength", "(FFFFFFFFFFF)F", &Java_com_scriptographer_ai_Curve_nativeGetPartLength },
	{ "nativeGetPositionWithLength", "(FFFFFFFFFF)F", &Java_com_scriptographer_ai_Curve_nativeGetPositionWithLength },
	{ "nativeAdjustThroughPoint", "([FFFF)V", &Java_com_scriptographer_ai_Curve_nativeAdjustThroughPoint }
};

/* Native methods for class com_scriptographer_adm_ScrollBar */
const JNINativeMethod com_scriptographer_adm_ScrollBar_methods[] = {
	{ "getIncrements", "()[F", &Java_com_scriptographer_adm_ScrollBar_getIncrements },
	{ "setIncrements", "(FF)V", &Java_com_scriptographer_adm_ScrollBar_setIncrements }
};

/* Registers natives for a given class an methods array */
void ScriptographerEngine::registerClassNatives(JNIEnv *env, const char *className, const JNINativeMethod *methods, int count) {
	jclass cls = findClass(env, className);
	if (cls == NULL) {
		char msg[64];
		sprintf(msg, "Cannot register natives for class %s: Class not found.", className);
		throw new StringException(msg);
	}
	jint err = env->RegisterNatives(cls, methods, count);
	if (err != 0) {
		char msg[64];
		sprintf(msg, "Cannot register natives for class %s.", className);
		throw new StringException(msg);
	}
}

/* Registers natives for all classes, to be called from outside */
void ScriptographerEngine::registerNatives(JNIEnv *env) {
	registerClassNatives(env, "com/scriptographer/adm/List", com_scriptographer_adm_List_methods,
		sizeof(com_scriptographer_adm_List_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/Item", com_scriptographer_adm_Item_methods,
		sizeof(com_scriptographer_adm_Item_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Document", com_scriptographer_ai_Document_methods,
		sizeof(com_scriptographer_ai_Document_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PathStyle", com_scriptographer_ai_PathStyle_methods,
		sizeof(com_scriptographer_ai_PathStyle_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/SegmentList", com_scriptographer_ai_SegmentList_methods,
		sizeof(com_scriptographer_ai_SegmentList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Raster", com_scriptographer_ai_Raster_methods,
		sizeof(com_scriptographer_ai_Raster_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Art", com_scriptographer_ai_Art_methods,
		sizeof(com_scriptographer_ai_Art_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Tool", com_scriptographer_ai_Tool_methods,
		sizeof(com_scriptographer_ai_Tool_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Group", com_scriptographer_ai_Group_methods,
		sizeof(com_scriptographer_ai_Group_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/ListEntry", com_scriptographer_adm_ListEntry_methods,
		sizeof(com_scriptographer_adm_ListEntry_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/PictureItem", com_scriptographer_adm_PictureItem_methods,
		sizeof(com_scriptographer_adm_PictureItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ConsoleOutputStream", com_scriptographer_ConsoleOutputStream_methods,
		sizeof(com_scriptographer_ConsoleOutputStream_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/TextItem", com_scriptographer_adm_TextItem_methods,
		sizeof(com_scriptographer_adm_TextItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/MenuItem", com_scriptographer_ai_MenuItem_methods,
		sizeof(com_scriptographer_ai_MenuItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/HierarchyList", com_scriptographer_adm_HierarchyList_methods,
		sizeof(com_scriptographer_adm_HierarchyList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/HierarchyListEntry", com_scriptographer_adm_HierarchyListEntry_methods,
		sizeof(com_scriptographer_adm_HierarchyListEntry_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/LiveEffect", com_scriptographer_ai_LiveEffect_methods,
		sizeof(com_scriptographer_ai_LiveEffect_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Pathfinder", com_scriptographer_ai_Pathfinder_methods,
		sizeof(com_scriptographer_ai_Pathfinder_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Layer", com_scriptographer_ai_Layer_methods,
		sizeof(com_scriptographer_ai_Layer_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/ListBox", com_scriptographer_adm_ListBox_methods,
		sizeof(com_scriptographer_adm_ListBox_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/TextEdit", com_scriptographer_adm_TextEdit_methods,
		sizeof(com_scriptographer_adm_TextEdit_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/Image", com_scriptographer_adm_Image_methods,
		sizeof(com_scriptographer_adm_Image_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/DocumentList", com_scriptographer_ai_DocumentList_methods,
		sizeof(com_scriptographer_ai_DocumentList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/Tracker", com_scriptographer_adm_Tracker_methods,
		sizeof(com_scriptographer_adm_Tracker_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/Dialog", com_scriptographer_adm_Dialog_methods,
		sizeof(com_scriptographer_adm_Dialog_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/Drawer", com_scriptographer_adm_Drawer_methods,
		sizeof(com_scriptographer_adm_Drawer_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/LayerList", com_scriptographer_ai_LayerList_methods,
		sizeof(com_scriptographer_ai_LayerList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/ValueItem", com_scriptographer_adm_ValueItem_methods,
		sizeof(com_scriptographer_adm_ValueItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Path", com_scriptographer_ai_Path_methods,
		sizeof(com_scriptographer_ai_Path_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/MenuGroup", com_scriptographer_ai_MenuGroup_methods,
		sizeof(com_scriptographer_ai_MenuGroup_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Color", com_scriptographer_ai_Color_methods,
		sizeof(com_scriptographer_ai_Color_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/ItemGroup", com_scriptographer_adm_ItemGroup_methods,
		sizeof(com_scriptographer_adm_ItemGroup_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/ArtSet", com_scriptographer_ai_ArtSet_methods,
		sizeof(com_scriptographer_ai_ArtSet_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Curve", com_scriptographer_ai_Curve_methods,
		sizeof(com_scriptographer_ai_Curve_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/adm/ScrollBar", com_scriptographer_adm_ScrollBar_methods,
		sizeof(com_scriptographer_adm_ScrollBar_methods) / sizeof(JNINativeMethod));

}
