/* DO NOT EDIT THIS FILE - it is machine generated */
#include "stdHeaders.h"
#include "ScriptographerEngine.h"
#include <jni.h>

/* Include headers for all classes */
#include "com_scriptographer_adm_Button.h"
#include "com_scriptographer_adm_Dialog.h"
#include "com_scriptographer_adm_Drawer.h"
#include "com_scriptographer_adm_HierarchyListBox.h"
#include "com_scriptographer_adm_HierarchyListEntry.h"
#include "com_scriptographer_adm_Image.h"
#include "com_scriptographer_adm_ImagePane.h"
#include "com_scriptographer_adm_Item.h"
#include "com_scriptographer_adm_ItemGroup.h"
#include "com_scriptographer_adm_ListEntry.h"
#include "com_scriptographer_adm_ListItem.h"
#include "com_scriptographer_adm_ModalDialog.h"
#include "com_scriptographer_adm_TextEditItem.h"
#include "com_scriptographer_adm_TextItem.h"
#include "com_scriptographer_adm_TextValueItem.h"
#include "com_scriptographer_adm_ToggleItem.h"
#include "com_scriptographer_adm_Tracker.h"
#include "com_scriptographer_adm_ValueItem.h"
#include "com_scriptographer_ai_Annotator.h"
#include "com_scriptographer_ai_AreaText.h"
#include "com_scriptographer_ai_ArtboardList.h"
#include "com_scriptographer_ai_CharacterStyle.h"
#include "com_scriptographer_ai_Color.h"
#include "com_scriptographer_ai_Curve.h"
#include "com_scriptographer_ai_Dictionary.h"
#include "com_scriptographer_ai_Document.h"
#include "com_scriptographer_ai_DocumentList.h"
#include "com_scriptographer_ai_DocumentView.h"
#include "com_scriptographer_ai_DocumentViewList.h"
#include "com_scriptographer_ai_FileFormat.h"
#include "com_scriptographer_ai_FontFamily.h"
#include "com_scriptographer_ai_FontList.h"
#include "com_scriptographer_ai_FontWeight.h"
#include "com_scriptographer_ai_Gradient.h"
#include "com_scriptographer_ai_GradientStopList.h"
#include "com_scriptographer_ai_Group.h"
#include "com_scriptographer_ai_Item.h"
#include "com_scriptographer_ai_Layer.h"
#include "com_scriptographer_ai_LayerList.h"
#include "com_scriptographer_ai_LiveEffect.h"
#include "com_scriptographer_ai_ParagraphStyle.h"
#include "com_scriptographer_ai_Path.h"
#include "com_scriptographer_ai_Pathfinder.h"
#include "com_scriptographer_ai_PathStyle.h"
#include "com_scriptographer_ai_PathText.h"
#include "com_scriptographer_ai_Pattern.h"
#include "com_scriptographer_ai_PlacedFile.h"
#include "com_scriptographer_ai_PlacedSymbol.h"
#include "com_scriptographer_ai_PointText.h"
#include "com_scriptographer_ai_Raster.h"
#include "com_scriptographer_ai_SegmentList.h"
#include "com_scriptographer_ai_Swatch.h"
#include "com_scriptographer_ai_SwatchList.h"
#include "com_scriptographer_ai_Symbol.h"
#include "com_scriptographer_ai_SymbolList.h"
#include "com_scriptographer_ai_TextItem.h"
#include "com_scriptographer_ai_TextRange.h"
#include "com_scriptographer_ai_TextStory.h"
#include "com_scriptographer_ai_TextStoryList.h"
#include "com_scriptographer_ai_Timer.h"
#include "com_scriptographer_ai_Tool.h"
#include "com_scriptographer_ai_Tracing.h"
#include "com_scriptographer_ScriptographerEngine.h"
#include "com_scriptographer_ui_MenuGroup.h"
#include "com_scriptographer_ui_MenuItem.h"
#include "com_scriptographer_widget_Button.h"
#include "com_scriptographer_widget_Dialog.h"
#include "com_scriptographer_widget_Item.h"
#include "com_scriptographer_widget_TextEditItem.h"
#include "com_scriptographer_widget_TextItem.h"
#include "com_scriptographer_widget_TextValueItem.h"
#include "com_scriptographer_widget_ValueItem.h"

/* Native methods for class com_scriptographer_ai_Annotator */
static const JNINativeMethod com_scriptographer_ai_Annotator_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;)I", (void *) &Java_com_scriptographer_ai_Annotator_nativeCreate },
	{ "nativeSetActive", "(IZ)Z", (void *) &Java_com_scriptographer_ai_Annotator_nativeSetActive },
	{ "nativeInvalidate", "(IIIII)V", (void *) &Java_com_scriptographer_ai_Annotator_nativeInvalidate },
	{ "nativeGetAnnotators", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ai_Annotator_nativeGetAnnotators },
	{ "nativeCreateDrawer", "(I)Lcom/scriptographer/adm/Drawer;", (void *) &Java_com_scriptographer_ai_Annotator_nativeCreateDrawer }
};

/* Native methods for class com_scriptographer_ai_AreaText */
static const JNINativeMethod com_scriptographer_ai_AreaText_methods[] = {
	{ "nativeCreate", "(II)I", (void *) &Java_com_scriptographer_ai_AreaText_nativeCreate },
	{ "getPadding", "()F", (void *) &Java_com_scriptographer_ai_AreaText_getPadding },
	{ "setPadding", "(F)V", (void *) &Java_com_scriptographer_ai_AreaText_setPadding },
	{ "getRowCount", "()I", (void *) &Java_com_scriptographer_ai_AreaText_getRowCount },
	{ "setRowCount", "(I)V", (void *) &Java_com_scriptographer_ai_AreaText_setRowCount },
	{ "getColumnCount", "()I", (void *) &Java_com_scriptographer_ai_AreaText_getColumnCount },
	{ "setColumnCount", "(I)V", (void *) &Java_com_scriptographer_ai_AreaText_setColumnCount },
	{ "getRowMajorOrder", "()Z", (void *) &Java_com_scriptographer_ai_AreaText_getRowMajorOrder },
	{ "setRowMajorOrder", "(Z)V", (void *) &Java_com_scriptographer_ai_AreaText_setRowMajorOrder },
	{ "getRowGutter", "()F", (void *) &Java_com_scriptographer_ai_AreaText_getRowGutter },
	{ "setRowGutter", "(F)V", (void *) &Java_com_scriptographer_ai_AreaText_setRowGutter },
	{ "getColumnGutter", "()F", (void *) &Java_com_scriptographer_ai_AreaText_getColumnGutter },
	{ "setColumnGutter", "(F)V", (void *) &Java_com_scriptographer_ai_AreaText_setColumnGutter }
};

/* Native methods for class com_scriptographer_ai_ArtboardList */
static const JNINativeMethod com_scriptographer_ai_ArtboardList_methods[] = {
	{ "nativeGetSize", "(I)I", (void *) &Java_com_scriptographer_ai_ArtboardList_nativeGetSize },
	{ "nativeRemove", "(III)I", (void *) &Java_com_scriptographer_ai_ArtboardList_nativeRemove },
	{ "nativeGet", "(IILcom/scriptographer/ai/Artboard;)Z", (void *) &Java_com_scriptographer_ai_ArtboardList_nativeGet },
	{ "nativeInsert", "(IILcom/scriptographer/ai/Rectangle;ZZZD)Z", (void *) &Java_com_scriptographer_ai_ArtboardList_nativeInsert },
	{ "nativeSet", "(IILcom/scriptographer/ai/Rectangle;ZZZD)Z", (void *) &Java_com_scriptographer_ai_ArtboardList_nativeSet }
};

/* Native methods for class com_scriptographer_ai_CharacterStyle */
static const JNINativeMethod com_scriptographer_ai_CharacterStyle_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeCreate },
	{ "nativeClone", "()I", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeClone },
	{ "nativeGet", "(II)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGet },
	{ "nativeSet", "(IILcom/scriptographer/ai/Color;ZSLcom/scriptographer/ai/Color;ZSFIIFF[FSSIF)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSet },
	{ "nativeSetStyle", "(III)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetStyle },
	{ "nativeGetFont", "()I", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetFont },
	{ "nativeSetFont", "(I)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetFont },
	{ "getFontSize", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getFontSize },
	{ "setFontSize", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setFontSize },
	{ "getHorizontalScale", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getHorizontalScale },
	{ "setHorizontalScale", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setHorizontalScale },
	{ "getVerticalScale", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getVerticalScale },
	{ "setVerticalScale", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setVerticalScale },
	{ "getAutoLeading", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getAutoLeading },
	{ "nativeSetAutoLeading", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetAutoLeading },
	{ "getLeading", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getLeading },
	{ "nativeSetLeading", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetLeading },
	{ "getTracking", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getTracking },
	{ "setTracking", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setTracking },
	{ "getBaselineShift", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getBaselineShift },
	{ "setBaselineShift", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setBaselineShift },
	{ "nativeGetRotation", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetRotation },
	{ "nativeSetRotation", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetRotation },
	{ "nativeGetKerning", "(I)I", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetKerning },
	{ "nativeSetKerning", "(II)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetKerning },
	{ "nativeGetKerningType", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetKerningType },
	{ "nativeSetKerningType", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetKerningType },
	{ "nativeGetCapitalization", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetCapitalization },
	{ "nativeSetCapitalization", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetCapitalization },
	{ "nativeGetBaselineOption", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetBaselineOption },
	{ "nativeSetBaselineOption", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetBaselineOption },
	{ "nativeGetOpenTypePosition", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetOpenTypePosition },
	{ "nativeSetOpenTypePosition", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetOpenTypePosition },
	{ "nativeGetStrikethroughPosition", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetStrikethroughPosition },
	{ "nativeSetStrikethroughPosition", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetStrikethroughPosition },
	{ "nativeGetUnderlinePosition", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetUnderlinePosition },
	{ "nativeSetUnderlinePosition", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetUnderlinePosition },
	{ "getUnderlineOffset", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getUnderlineOffset },
	{ "setUnderlineOffset", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setUnderlineOffset },
	{ "getLigature", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getLigature },
	{ "setLigature", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setLigature },
	{ "getDiscretionaryLigature", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getDiscretionaryLigature },
	{ "setDiscretionaryLigature", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setDiscretionaryLigature },
	{ "getContextualLigature", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getContextualLigature },
	{ "setContextualLigature", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setContextualLigature },
	{ "getAlternateLigatures", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getAlternateLigatures },
	{ "setAlternateLigatures", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setAlternateLigatures },
	{ "getOldStyle", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getOldStyle },
	{ "setOldStyle", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setOldStyle },
	{ "getFractions", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getFractions },
	{ "setFractions", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setFractions },
	{ "getOrdinals", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getOrdinals },
	{ "setOrdinals", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setOrdinals },
	{ "getSwash", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getSwash },
	{ "setSwash", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setSwash },
	{ "getTitling", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getTitling },
	{ "setTitling", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setTitling },
	{ "getConnectionForms", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getConnectionForms },
	{ "setConnectionForms", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setConnectionForms },
	{ "getStylisticAlternates", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getStylisticAlternates },
	{ "setStylisticAlternates", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setStylisticAlternates },
	{ "getOrnaments", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getOrnaments },
	{ "setOrnaments", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setOrnaments },
	{ "nativeGetFigureStyle", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeGetFigureStyle },
	{ "nativeSetFigureStyle", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeSetFigureStyle },
	{ "getNoBreak", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_CharacterStyle_getNoBreak },
	{ "setNoBreak", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_setNoBreak },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_CharacterStyle_nativeRelease }
};

/* Native methods for class com_scriptographer_ai_Color */
static const JNINativeMethod com_scriptographer_ai_Color_methods[] = {
	{ "nativeConvert", "(I)Lcom/scriptographer/ai/Color;", (void *) &Java_com_scriptographer_ai_Color_nativeConvert },
	{ "nativeGetProfile", "(I)Ljava/awt/color/ICC_Profile;", (void *) &Java_com_scriptographer_ai_Color_nativeGetProfile },
	{ "nativeSetGradient", "(IILcom/scriptographer/ai/Point;DDLcom/scriptographer/ai/Matrix;DD)V", (void *) &Java_com_scriptographer_ai_Color_nativeSetGradient },
	{ "nativeSetPattern", "(IILcom/scriptographer/ai/Matrix;)V", (void *) &Java_com_scriptographer_ai_Color_nativeSetPattern }
};

/* Native methods for class com_scriptographer_ai_Curve */
static const JNINativeMethod com_scriptographer_ai_Curve_methods[] = {
	{ "nativeGetLength", "(DDDDDDDD)D", (void *) &Java_com_scriptographer_ai_Curve_nativeGetLength },
	{ "nativeAdjustThroughPoint", "([FFFF)V", (void *) &Java_com_scriptographer_ai_Curve_nativeAdjustThroughPoint }
};

/* Native methods for class com_scriptographer_ai_Dictionary */
static const JNINativeMethod com_scriptographer_ai_Dictionary_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_Dictionary_nativeCreate },
	{ "nativeCreateLiveEffectParameters", "()I", (void *) &Java_com_scriptographer_ai_Dictionary_nativeCreateLiveEffectParameters },
	{ "nativeGet", "(IILjava/lang/Object;)Ljava/lang/Object;", (void *) &Java_com_scriptographer_ai_Dictionary_nativeGet },
	{ "nativePut", "(ILjava/lang/String;Ljava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_Dictionary_nativePut },
	{ "nativeRemove", "(ILjava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_Dictionary_nativeRemove },
	{ "containsKey", "(Ljava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_Dictionary_containsKey },
	{ "size", "()I", (void *) &Java_com_scriptographer_ai_Dictionary_size },
	{ "keys", "()[Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Dictionary_keys },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_Dictionary_nativeRelease }
};

/* Native methods for class com_scriptographer_ai_Document */
static const JNINativeMethod com_scriptographer_ai_Document_methods[] = {
	{ "nativeCreate", "(Ljava/io/File;II)I", (void *) &Java_com_scriptographer_ai_Document_nativeCreate__Ljava_io_File_2II },
	{ "nativeCreate", "(Ljava/lang/String;FFII)I", (void *) &Java_com_scriptographer_ai_Document_nativeCreate__Ljava_lang_String_2FFII },
	{ "nativeGetActiveDocumentHandle", "()I", (void *) &Java_com_scriptographer_ai_Document_nativeGetActiveDocumentHandle },
	{ "nativeGetWorkingDocumentHandle", "()I", (void *) &Java_com_scriptographer_ai_Document_nativeGetWorkingDocumentHandle },
	{ "nativeBeginExecution", "(ZZ[I)V", (void *) &Java_com_scriptographer_ai_Document_nativeBeginExecution },
	{ "endExecution", "()V", (void *) &Java_com_scriptographer_ai_Document_endExecution },
	{ "setUndoType", "(I)V", (void *) &Java_com_scriptographer_ai_Document_setUndoType },
	{ "nativeActivate", "(ZZ)V", (void *) &Java_com_scriptographer_ai_Document_nativeActivate },
	{ "hasSelectedItems", "()Z", (void *) &Java_com_scriptographer_ai_Document_hasSelectedItems },
	{ "getSelectedItems", "()Lcom/scriptographer/ai/ItemList;", (void *) &Java_com_scriptographer_ai_Document_getSelectedItems },
	{ "getMatchingItems", "(Ljava/lang/Class;II)Lcom/scriptographer/ai/ItemList;", (void *) &Java_com_scriptographer_ai_Document_getMatchingItems },
	{ "getPageOrigin", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_Document_getPageOrigin },
	{ "setPageOrigin", "(Lcom/scriptographer/ai/Point;)V", (void *) &Java_com_scriptographer_ai_Document_setPageOrigin },
	{ "getRulerOrigin", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_Document_getRulerOrigin },
	{ "setRulerOrigin", "(Lcom/scriptographer/ai/Point;)V", (void *) &Java_com_scriptographer_ai_Document_setRulerOrigin },
	{ "getSize", "()Lcom/scriptographer/ai/Size;", (void *) &Java_com_scriptographer_ai_Document_getSize },
	{ "setSize", "(DD)V", (void *) &Java_com_scriptographer_ai_Document_setSize },
	{ "nativeGetColormodel", "()I", (void *) &Java_com_scriptographer_ai_Document_nativeGetColormodel },
	{ "nativeSetColormodel", "(I)V", (void *) &Java_com_scriptographer_ai_Document_nativeSetColormodel },
	{ "isModified", "()Z", (void *) &Java_com_scriptographer_ai_Document_isModified },
	{ "setModified", "(Z)V", (void *) &Java_com_scriptographer_ai_Document_setModified },
	{ "getFile", "()Ljava/io/File;", (void *) &Java_com_scriptographer_ai_Document_getFile },
	{ "nativeGetFileFormat", "()I", (void *) &Java_com_scriptographer_ai_Document_nativeGetFileFormat },
	{ "nativeSetFileFormat", "(I)V", (void *) &Java_com_scriptographer_ai_Document_nativeSetFileFormat },
	{ "nativeGetData", "()I", (void *) &Java_com_scriptographer_ai_Document_nativeGetData },
	{ "getActiveLayer", "()Lcom/scriptographer/ai/Layer;", (void *) &Java_com_scriptographer_ai_Document_getActiveLayer },
	{ "getActiveSymbolHandle", "()I", (void *) &Java_com_scriptographer_ai_Document_getActiveSymbolHandle },
	{ "getActiveArtboardIndex", "()I", (void *) &Java_com_scriptographer_ai_Document_getActiveArtboardIndex },
	{ "setActiveArtboardIndex", "(I)V", (void *) &Java_com_scriptographer_ai_Document_setActiveArtboardIndex },
	{ "getActiveViewHandle", "()I", (void *) &Java_com_scriptographer_ai_Document_getActiveViewHandle },
	{ "nativeGetStories", "(IZ)I", (void *) &Java_com_scriptographer_ai_Document_nativeGetStories },
	{ "nativePrint", "(I)V", (void *) &Java_com_scriptographer_ai_Document_nativePrint },
	{ "save", "()V", (void *) &Java_com_scriptographer_ai_Document_save },
	{ "close", "()V", (void *) &Java_com_scriptographer_ai_Document_close },
	{ "redraw", "()V", (void *) &Java_com_scriptographer_ai_Document_redraw },
	{ "undo", "()V", (void *) &Java_com_scriptographer_ai_Document_undo },
	{ "redo", "()V", (void *) &Java_com_scriptographer_ai_Document_redo },
	{ "place", "(Ljava/io/File;Z)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Document_place },
	{ "invalidate", "(Lcom/scriptographer/ai/Rectangle;)V", (void *) &Java_com_scriptographer_ai_Document_invalidate },
	{ "nativeWrite", "(Ljava/io/File;IZ)Z", (void *) &Java_com_scriptographer_ai_Document_nativeWrite },
	{ "getSelectedTextRange", "()Lcom/scriptographer/ai/TextRange;", (void *) &Java_com_scriptographer_ai_Document_getSelectedTextRange },
	{ "nativeSelectAll", "()V", (void *) &Java_com_scriptographer_ai_Document_nativeSelectAll },
	{ "nativeDeselectAll", "()V", (void *) &Java_com_scriptographer_ai_Document_nativeDeselectAll },
	{ "nativeCreateRectangle", "(Lcom/scriptographer/ai/Rectangle;)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateRectangle },
	{ "nativeCreateRoundRectangle", "(Lcom/scriptographer/ai/Rectangle;Lcom/scriptographer/ai/Size;)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateRoundRectangle },
	{ "nativeCreateOval", "(Lcom/scriptographer/ai/Rectangle;Z)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateOval },
	{ "nativeCreateRegularPolygon", "(Lcom/scriptographer/ai/Point;IF)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateRegularPolygon },
	{ "nativeCreateStar", "(Lcom/scriptographer/ai/Point;IFF)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateStar },
	{ "nativeCreateSpiral", "(Lcom/scriptographer/ai/Point;Lcom/scriptographer/ai/Point;FIZ)Lcom/scriptographer/ai/Path;", (void *) &Java_com_scriptographer_ai_Document_nativeCreateSpiral },
	{ "nativeHitTest", "(Lcom/scriptographer/ai/Point;IFLcom/scriptographer/ai/Item;)Lcom/scriptographer/ai/HitResult;", (void *) &Java_com_scriptographer_ai_Document_nativeHitTest },
	{ "reflowText", "()V", (void *) &Java_com_scriptographer_ai_Document_reflowText },
	{ "cut", "()V", (void *) &Java_com_scriptographer_ai_Document_cut },
	{ "copy", "()V", (void *) &Java_com_scriptographer_ai_Document_copy },
	{ "paste", "()V", (void *) &Java_com_scriptographer_ai_Document_paste }
};

/* Native methods for class com_scriptographer_ai_DocumentList */
static const JNINativeMethod com_scriptographer_ai_DocumentList_methods[] = {
	{ "size", "()I", (void *) &Java_com_scriptographer_ai_DocumentList_size },
	{ "nativeGet", "(I)I", (void *) &Java_com_scriptographer_ai_DocumentList_nativeGet }
};

/* Native methods for class com_scriptographer_ai_DocumentView */
static const JNINativeMethod com_scriptographer_ai_DocumentView_methods[] = {
	{ "getBounds", "()Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_DocumentView_getBounds },
	{ "getCenter", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_DocumentView_getCenter },
	{ "setCenter", "(FF)V", (void *) &Java_com_scriptographer_ai_DocumentView_setCenter },
	{ "getZoom", "()F", (void *) &Java_com_scriptographer_ai_DocumentView_getZoom },
	{ "setZoom", "(F)V", (void *) &Java_com_scriptographer_ai_DocumentView_setZoom },
	{ "artworkToView", "(FF)Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_DocumentView_artworkToView__FF },
	{ "artworkToView", "(FFFF)Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_DocumentView_artworkToView__FFFF },
	{ "viewToArtwork", "(FF)Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_DocumentView_viewToArtwork__FF },
	{ "viewToArtwork", "(FFFF)Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_DocumentView_viewToArtwork__FFFF },
	{ "nativeSetScreenMode", "(I)V", (void *) &Java_com_scriptographer_ai_DocumentView_nativeSetScreenMode },
	{ "nativeGetScreenMode", "()I", (void *) &Java_com_scriptographer_ai_DocumentView_nativeGetScreenMode },
	{ "isTemplateVisible", "()Z", (void *) &Java_com_scriptographer_ai_DocumentView_isTemplateVisible },
	{ "scrollBy", "(FF)V", (void *) &Java_com_scriptographer_ai_DocumentView_scrollBy },
	{ "getInvalidBounds", "()Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_DocumentView_getInvalidBounds },
	{ "invalidate", "(Lcom/scriptographer/ai/Rectangle;)V", (void *) &Java_com_scriptographer_ai_DocumentView_invalidate },
	{ "nativeGetStyle", "()I", (void *) &Java_com_scriptographer_ai_DocumentView_nativeGetStyle },
	{ "getShowPageTiling", "()Z", (void *) &Java_com_scriptographer_ai_DocumentView_getShowPageTiling },
	{ "setShowPageTiling", "(Z)V", (void *) &Java_com_scriptographer_ai_DocumentView_setShowPageTiling },
	{ "getShowGrid", "()Z", (void *) &Java_com_scriptographer_ai_DocumentView_getShowGrid },
	{ "getSnapGrid", "()Z", (void *) &Java_com_scriptographer_ai_DocumentView_getSnapGrid },
	{ "setShowGrid", "(Z)V", (void *) &Java_com_scriptographer_ai_DocumentView_setShowGrid },
	{ "setSnapGrid", "(Z)V", (void *) &Java_com_scriptographer_ai_DocumentView_setSnapGrid },
	{ "getShowTransparencyGrid", "()Z", (void *) &Java_com_scriptographer_ai_DocumentView_getShowTransparencyGrid },
	{ "setShowTransparencyGrid", "(Z)V", (void *) &Java_com_scriptographer_ai_DocumentView_setShowTransparencyGrid },
	{ "getMousePoint", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_DocumentView_getMousePoint }
};

/* Native methods for class com_scriptographer_ai_DocumentViewList */
static const JNINativeMethod com_scriptographer_ai_DocumentViewList_methods[] = {
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_DocumentViewList_nativeSize },
	{ "nativeGet", "(II)I", (void *) &Java_com_scriptographer_ai_DocumentViewList_nativeGet }
};

/* Native methods for class com_scriptographer_ai_FileFormat */
static const JNINativeMethod com_scriptographer_ai_FileFormat_methods[] = {
	{ "getFileFormats", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ai_FileFormat_getFileFormats }
};

/* Native methods for class com_scriptographer_ai_FontFamily */
static const JNINativeMethod com_scriptographer_ai_FontFamily_methods[] = {
	{ "nativeGetName", "(I)Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_FontFamily_nativeGetName },
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_FontFamily_nativeSize },
	{ "nativeGet", "(II)I", (void *) &Java_com_scriptographer_ai_FontFamily_nativeGet }
};

/* Native methods for class com_scriptographer_ai_FontList */
static const JNINativeMethod com_scriptographer_ai_FontList_methods[] = {
	{ "size", "()I", (void *) &Java_com_scriptographer_ai_FontList_size },
	{ "nativeGet", "(I)I", (void *) &Java_com_scriptographer_ai_FontList_nativeGet }
};

/* Native methods for class com_scriptographer_ai_FontWeight */
static const JNINativeMethod com_scriptographer_ai_FontWeight_methods[] = {
	{ "nativeGetName", "(I)Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_FontWeight_nativeGetName },
	{ "nativeGetFamily", "(I)I", (void *) &Java_com_scriptographer_ai_FontWeight_nativeGetFamily },
	{ "nativeGetIndex", "(I)I", (void *) &Java_com_scriptographer_ai_FontWeight_nativeGetIndex },
	{ "nativeIsValid", "(I)Z", (void *) &Java_com_scriptographer_ai_FontWeight_nativeIsValid }
};

/* Native methods for class com_scriptographer_ai_Gradient */
static const JNINativeMethod com_scriptographer_ai_Gradient_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_Gradient_nativeCreate },
	{ "nativeGetType", "()I", (void *) &Java_com_scriptographer_ai_Gradient_nativeGetType },
	{ "nativeSetType", "(I)V", (void *) &Java_com_scriptographer_ai_Gradient_nativeSetType },
	{ "isValid", "()Z", (void *) &Java_com_scriptographer_ai_Gradient_isValid },
	{ "nativeRemove", "()Z", (void *) &Java_com_scriptographer_ai_Gradient_nativeRemove }
};

/* Native methods for class com_scriptographer_ai_GradientStopList */
static const JNINativeMethod com_scriptographer_ai_GradientStopList_methods[] = {
	{ "nativeGetSize", "(I)I", (void *) &Java_com_scriptographer_ai_GradientStopList_nativeGetSize },
	{ "nativeRemove", "(IIII)I", (void *) &Java_com_scriptographer_ai_GradientStopList_nativeRemove },
	{ "nativeGet", "(IILcom/scriptographer/ai/GradientStop;)Z", (void *) &Java_com_scriptographer_ai_GradientStopList_nativeGet },
	{ "nativeSet", "(IIIDD[F)Z", (void *) &Java_com_scriptographer_ai_GradientStopList_nativeSet },
	{ "nativeInsert", "(IIIDD[F)Z", (void *) &Java_com_scriptographer_ai_GradientStopList_nativeInsert }
};

/* Native methods for class com_scriptographer_ai_Group */
static const JNINativeMethod com_scriptographer_ai_Group_methods[] = {
	{ "isClipped", "()Z", (void *) &Java_com_scriptographer_ai_Group_isClipped },
	{ "nativeSetClipped", "(Z)V", (void *) &Java_com_scriptographer_ai_Group_nativeSetClipped }
};

/* Native methods for class com_scriptographer_ai_Item */
static const JNINativeMethod com_scriptographer_ai_Item_methods[] = {
	{ "nativeCreate", "(S)I", (void *) &Java_com_scriptographer_ai_Item_nativeCreate },
	{ "wrapHandle", "(IIZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_wrapHandle },
	{ "nativeRemove", "(III)Z", (void *) &Java_com_scriptographer_ai_Item_nativeRemove },
	{ "finalize", "()V", (void *) &Java_com_scriptographer_ai_Item_finalize },
	{ "copyTo", "(Lcom/scriptographer/ai/Document;)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_copyTo__Lcom_scriptographer_ai_Document_2 },
	{ "copyTo", "(Lcom/scriptographer/ai/Item;)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_copyTo__Lcom_scriptographer_ai_Item_2 },
	{ "getName", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Item_getName },
	{ "setName", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ai_Item_setName },
	{ "getPosition", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_Item_getPosition },
	{ "isCenterVisible", "()Z", (void *) &Java_com_scriptographer_ai_Item_isCenterVisible },
	{ "setCenterVisible", "(Z)V", (void *) &Java_com_scriptographer_ai_Item_setCenterVisible },
	{ "nativeGetAttributes", "(I)I", (void *) &Java_com_scriptographer_ai_Item_nativeGetAttributes },
	{ "nativeSetAttributes", "(II)V", (void *) &Java_com_scriptographer_ai_Item_nativeSetAttributes },
	{ "nativeGetBlendMode", "()I", (void *) &Java_com_scriptographer_ai_Item_nativeGetBlendMode },
	{ "nativeSetBlendMode", "(I)V", (void *) &Java_com_scriptographer_ai_Item_nativeSetBlendMode },
	{ "getOpacity", "()F", (void *) &Java_com_scriptographer_ai_Item_getOpacity },
	{ "setOpacity", "(F)V", (void *) &Java_com_scriptographer_ai_Item_setOpacity },
	{ "getIsolated", "()Z", (void *) &Java_com_scriptographer_ai_Item_getIsolated },
	{ "setIsolated", "(Z)V", (void *) &Java_com_scriptographer_ai_Item_setIsolated },
	{ "nativeGetKnockout", "(Z)I", (void *) &Java_com_scriptographer_ai_Item_nativeGetKnockout },
	{ "nativeSetKnockout", "(I)V", (void *) &Java_com_scriptographer_ai_Item_nativeSetKnockout },
	{ "getAlphaIsShape", "()Z", (void *) &Java_com_scriptographer_ai_Item_getAlphaIsShape },
	{ "setAlphaIsShape", "(Z)V", (void *) &Java_com_scriptographer_ai_Item_setAlphaIsShape },
	{ "nativeGetData", "()I", (void *) &Java_com_scriptographer_ai_Item_nativeGetData },
	{ "nativeGetEffectPosition", "(Lcom/scriptographer/ai/LiveEffect;Ljava/util/Map;)I", (void *) &Java_com_scriptographer_ai_Item_nativeGetEffectPosition },
	{ "nativeAddEffect", "(Lcom/scriptographer/ai/LiveEffect;Lcom/scriptographer/ai/LiveEffectParameters;I)Z", (void *) &Java_com_scriptographer_ai_Item_nativeAddEffect },
	{ "editEffect", "(Lcom/scriptographer/ai/LiveEffect;Ljava/util/Map;)Z", (void *) &Java_com_scriptographer_ai_Item_editEffect },
	{ "removeEffect", "(Lcom/scriptographer/ai/LiveEffect;Ljava/util/Map;)Z", (void *) &Java_com_scriptographer_ai_Item_removeEffect },
	{ "getLayer", "()Lcom/scriptographer/ai/Layer;", (void *) &Java_com_scriptographer_ai_Item_getLayer },
	{ "getParent", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_getParent },
	{ "getFirstChild", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_getFirstChild },
	{ "getLastChild", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_getLastChild },
	{ "getNextSibling", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_getNextSibling },
	{ "getPreviousSibling", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_getPreviousSibling },
	{ "getBounds", "()Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_Item_getBounds },
	{ "getStrokeBounds", "()Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_Item_getStrokeBounds },
	{ "getControlBounds", "()Lcom/scriptographer/ai/Rectangle;", (void *) &Java_com_scriptographer_ai_Item_getControlBounds },
	{ "nativeExpand", "(II)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Item_nativeExpand },
	{ "nativeRasterize", "(IFIFF)Lcom/scriptographer/ai/Raster;", (void *) &Java_com_scriptographer_ai_Item_nativeRasterize__IFIFF },
	{ "nativeRasterize", "([Lcom/scriptographer/ai/Item;IFIFF)Lcom/scriptographer/ai/Raster;", (void *) &Java_com_scriptographer_ai_Item_nativeRasterize___3Lcom_scriptographer_ai_Item_2IFIFF },
	{ "nativeDraw", "(Lcom/scriptographer/adm/Image;II)V", (void *) &Java_com_scriptographer_ai_Item_nativeDraw },
	{ "isEditable", "()Z", (void *) &Java_com_scriptographer_ai_Item_isEditable },
	{ "nativeCheckItems", "([II)[Z", (void *) &Java_com_scriptographer_ai_Item_nativeCheckItems },
	{ "appendTop", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_appendTop },
	{ "appendBottom", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_appendBottom },
	{ "moveAbove", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_moveAbove },
	{ "moveBelow", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_moveBelow },
	{ "isAbove", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_isAbove },
	{ "isBelow", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_isBelow },
	{ "isDescendant", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_isDescendant },
	{ "isAncestor", "(Lcom/scriptographer/ai/Item;)Z", (void *) &Java_com_scriptographer_ai_Item_isAncestor },
	{ "nativeTransform", "(Lcom/scriptographer/ai/Matrix;I)V", (void *) &Java_com_scriptographer_ai_Item_nativeTransform },
	{ "getItemType", "()I", (void *) &Java_com_scriptographer_ai_Item_getItemType__ },
	{ "getItemType", "(Ljava/lang/Class;)I", (void *) &Java_com_scriptographer_ai_Item_getItemType__Ljava_lang_Class_2 },
	{ "isValid", "(I)Z", (void *) &Java_com_scriptographer_ai_Item_isValid }
};

/* Native methods for class com_scriptographer_ai_Layer */
static const JNINativeMethod com_scriptographer_ai_Layer_methods[] = {
	{ "setLocked", "(Z)V", (void *) &Java_com_scriptographer_ai_Layer_setLocked },
	{ "isVisible", "()Z", (void *) &Java_com_scriptographer_ai_Layer_isVisible },
	{ "setVisible", "(Z)V", (void *) &Java_com_scriptographer_ai_Layer_setVisible },
	{ "getPreview", "()Z", (void *) &Java_com_scriptographer_ai_Layer_getPreview },
	{ "setPreview", "(Z)V", (void *) &Java_com_scriptographer_ai_Layer_setPreview },
	{ "isPrinted", "()Z", (void *) &Java_com_scriptographer_ai_Layer_isPrinted },
	{ "setPrinted", "(Z)V", (void *) &Java_com_scriptographer_ai_Layer_setPrinted },
	{ "getColor", "()Lcom/scriptographer/ai/RGBColor;", (void *) &Java_com_scriptographer_ai_Layer_getColor },
	{ "setColor", "(Lcom/scriptographer/ai/Color;)V", (void *) &Java_com_scriptographer_ai_Layer_setColor },
	{ "getItems", "()Lcom/scriptographer/ai/ItemList;", (void *) &Java_com_scriptographer_ai_Layer_getItems },
	{ "isActive", "()Z", (void *) &Java_com_scriptographer_ai_Layer_isActive },
	{ "activate", "()V", (void *) &Java_com_scriptographer_ai_Layer_activate },
	{ "nativeGetNextLayer", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Layer_nativeGetNextLayer },
	{ "nativeGetPreviousLayer", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Layer_nativeGetPreviousLayer }
};

/* Native methods for class com_scriptographer_ai_LayerList */
static const JNINativeMethod com_scriptographer_ai_LayerList_methods[] = {
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_LayerList_nativeSize },
	{ "nativeGet", "(II)Lcom/scriptographer/ai/Layer;", (void *) &Java_com_scriptographer_ai_LayerList_nativeGet__II },
	{ "nativeGet", "(ILjava/lang/String;)Lcom/scriptographer/ai/Layer;", (void *) &Java_com_scriptographer_ai_LayerList_nativeGet__ILjava_lang_String_2 }
};

/* Native methods for class com_scriptographer_ai_LiveEffect */
static const JNINativeMethod com_scriptographer_ai_LiveEffect_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;IIIII)I", (void *) &Java_com_scriptographer_ai_LiveEffect_nativeCreate },
	{ "nativeAddMenuItem", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/scriptographer/ui/MenuItem;", (void *) &Java_com_scriptographer_ai_LiveEffect_nativeAddMenuItem },
	{ "nativeGetEffects", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ai_LiveEffect_nativeGetEffects }
};

/* Native methods for class com_scriptographer_ai_ParagraphStyle */
static const JNINativeMethod com_scriptographer_ai_ParagraphStyle_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeCreate },
	{ "nativeClone", "()I", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeClone },
	{ "nativeSetStyle", "(II)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeSetStyle },
	{ "nativeGetJustification", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeGetJustification },
	{ "nativeSetJustification", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeSetJustification },
	{ "nativeGetSingleWordJustification", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeGetSingleWordJustification },
	{ "nativeSetSingleWordJustification", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeSetSingleWordJustification },
	{ "getFirstLineIndent", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getFirstLineIndent },
	{ "setFirstLineIndent", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setFirstLineIndent },
	{ "getStartIndent", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getStartIndent },
	{ "setStartIndent", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setStartIndent },
	{ "getEndIndent", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getEndIndent },
	{ "setEndIndent", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setEndIndent },
	{ "getSpaceBefore", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getSpaceBefore },
	{ "setSpaceBefore", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setSpaceBefore },
	{ "getSpaceAfter", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getSpaceAfter },
	{ "setSpaceAfter", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setSpaceAfter },
	{ "getHyphenation", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getHyphenation },
	{ "setHyphenation", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setHyphenation },
	{ "getHyphenatedWordSize", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getHyphenatedWordSize },
	{ "setHyphenatedWordSize", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setHyphenatedWordSize },
	{ "getPreHyphenSize", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getPreHyphenSize },
	{ "setPreHyphenSize", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setPreHyphenSize },
	{ "getPostHyphenSize", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getPostHyphenSize },
	{ "setPostHyphenSize", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setPostHyphenSize },
	{ "getConsecutiveHyphenLimit", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getConsecutiveHyphenLimit },
	{ "setConsecutiveHyphenLimit", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setConsecutiveHyphenLimit },
	{ "getHyphenationZone", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getHyphenationZone },
	{ "setHyphenationZone", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setHyphenationZone },
	{ "getHyphenateCapitalized", "()Ljava/lang/Boolean;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getHyphenateCapitalized },
	{ "setHyphenateCapitalized", "(Ljava/lang/Boolean;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setHyphenateCapitalized },
	{ "getHyphenationPreference", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getHyphenationPreference },
	{ "setHyphenationPreference", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setHyphenationPreference },
	{ "getDesiredWordSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getDesiredWordSpacing },
	{ "setDesiredWordSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setDesiredWordSpacing },
	{ "getMaxWordSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMaxWordSpacing },
	{ "setMaxWordSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMaxWordSpacing },
	{ "getMinWordSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMinWordSpacing },
	{ "setMinWordSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMinWordSpacing },
	{ "getDesiredLetterSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getDesiredLetterSpacing },
	{ "setDesiredLetterSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setDesiredLetterSpacing },
	{ "getMaxLetterSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMaxLetterSpacing },
	{ "setMaxLetterSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMaxLetterSpacing },
	{ "getMinLetterSpacing", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMinLetterSpacing },
	{ "setMinLetterSpacing", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMinLetterSpacing },
	{ "getDesiredGlyphScaling", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getDesiredGlyphScaling },
	{ "setDesiredGlyphScaling", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setDesiredGlyphScaling },
	{ "getMaxGlyphScaling", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMaxGlyphScaling },
	{ "setMaxGlyphScaling", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMaxGlyphScaling },
	{ "getMinGlyphScaling", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getMinGlyphScaling },
	{ "setMinGlyphScaling", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setMinGlyphScaling },
	{ "getAutoLeadingPercentage", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getAutoLeadingPercentage },
	{ "setAutoLeadingPercentage", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setAutoLeadingPercentage },
	{ "nativeGetLeading", "()Ljava/lang/Integer;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeGetLeading },
	{ "nativeSetLeading", "(Ljava/lang/Integer;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeSetLeading },
	{ "getDefaultTabWidth", "()Ljava/lang/Float;", (void *) &Java_com_scriptographer_ai_ParagraphStyle_getDefaultTabWidth },
	{ "setDefaultTabWidth", "(Ljava/lang/Float;)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_setDefaultTabWidth },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_ParagraphStyle_nativeRelease }
};

/* Native methods for class com_scriptographer_ai_Path */
static const JNINativeMethod com_scriptographer_ai_Path_methods[] = {
	{ "isClosed", "()Z", (void *) &Java_com_scriptographer_ai_Path_isClosed },
	{ "nativeSetClosed", "(Z)V", (void *) &Java_com_scriptographer_ai_Path_nativeSetClosed },
	{ "isGuide", "()Z", (void *) &Java_com_scriptographer_ai_Path_isGuide },
	{ "setGuide", "(Z)V", (void *) &Java_com_scriptographer_ai_Path_setGuide },
	{ "getLength", "()D", (void *) &Java_com_scriptographer_ai_Path_getLength },
	{ "getArea", "()F", (void *) &Java_com_scriptographer_ai_Path_getArea },
	{ "nativeReverse", "()V", (void *) &Java_com_scriptographer_ai_Path_nativeReverse },
	{ "nativePointsToCurves", "(FFIF)I", (void *) &Java_com_scriptographer_ai_Path_nativePointsToCurves },
	{ "nativeCurvesToPoints", "(FF)I", (void *) &Java_com_scriptographer_ai_Path_nativeCurvesToPoints },
	{ "nativeReduceSegments", "(F)V", (void *) &Java_com_scriptographer_ai_Path_nativeReduceSegments },
	{ "nativeGetTabletData", "(I)[[F", (void *) &Java_com_scriptographer_ai_Path_nativeGetTabletData },
	{ "nativeSetTabletData", "(I[[F)V", (void *) &Java_com_scriptographer_ai_Path_nativeSetTabletData },
	{ "nativeSplitTabletData", "(DLcom/scriptographer/ai/Path;)Z", (void *) &Java_com_scriptographer_ai_Path_nativeSplitTabletData },
	{ "nativeSwapTabletData", "(D)Z", (void *) &Java_com_scriptographer_ai_Path_nativeSwapTabletData },
	{ "hasTabletData", "()Z", (void *) &Java_com_scriptographer_ai_Path_hasTabletData }
};

/* Native methods for class com_scriptographer_ai_Pathfinder */
static const JNINativeMethod com_scriptographer_ai_Pathfinder_methods[] = {
	{ "unite", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_unite },
	{ "intersect", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_intersect },
	{ "exclude", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_exclude },
	{ "backMinusFront", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_backMinusFront },
	{ "frontMinusBack", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_frontMinusBack },
	{ "divide", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_divide },
	{ "outline", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_outline },
	{ "trim", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_trim },
	{ "merge", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_merge },
	{ "crop", "([Ljava/lang/Object;FZZ)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pathfinder_crop }
};

/* Native methods for class com_scriptographer_ai_PathStyle */
static const JNINativeMethod com_scriptographer_ai_PathStyle_methods[] = {
	{ "nativeGet", "(II)V", (void *) &Java_com_scriptographer_ai_PathStyle_nativeGet },
	{ "nativeSet", "(IILcom/scriptographer/ai/Color;ZSLcom/scriptographer/ai/Color;ZSFIIFF[FSSIF)V", (void *) &Java_com_scriptographer_ai_PathStyle_nativeSet },
	{ "nativeInitStrokeStyle", "(ILcom/scriptographer/ai/Color;ZSFIIFF[F)V", (void *) &Java_com_scriptographer_ai_PathStyle_nativeInitStrokeStyle },
	{ "nativeInitFillStyle", "(ILcom/scriptographer/ai/Color;ZS)V", (void *) &Java_com_scriptographer_ai_PathStyle_nativeInitFillStyle }
};

/* Native methods for class com_scriptographer_ai_PathText */
static const JNINativeMethod com_scriptographer_ai_PathText_methods[] = {
	{ "nativeCreate", "(II)I", (void *) &Java_com_scriptographer_ai_PathText_nativeCreate },
	{ "nativeGetPathOffsets", "()[D", (void *) &Java_com_scriptographer_ai_PathText_nativeGetPathOffsets },
	{ "nativeSetPathOffsets", "(DD)V", (void *) &Java_com_scriptographer_ai_PathText_nativeSetPathOffsets }
};

/* Native methods for class com_scriptographer_ai_Pattern */
static const JNINativeMethod com_scriptographer_ai_Pattern_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_Pattern_nativeCreate },
	{ "getDefinition", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Pattern_getDefinition },
	{ "setDefinition", "(Lcom/scriptographer/ai/Item;)V", (void *) &Java_com_scriptographer_ai_Pattern_setDefinition },
	{ "isValid", "()Z", (void *) &Java_com_scriptographer_ai_Pattern_isValid }
};

/* Native methods for class com_scriptographer_ai_PlacedFile */
static const JNINativeMethod com_scriptographer_ai_PlacedFile_methods[] = {
	{ "nativeCreate", "(Ljava/io/File;)I", (void *) &Java_com_scriptographer_ai_PlacedFile_nativeCreate },
	{ "getSize", "()Lcom/scriptographer/ai/Size;", (void *) &Java_com_scriptographer_ai_PlacedFile_getSize },
	{ "getMatrix", "()Lcom/scriptographer/ai/Matrix;", (void *) &Java_com_scriptographer_ai_PlacedFile_getMatrix },
	{ "setMatrix", "(Lcom/scriptographer/ai/Matrix;)V", (void *) &Java_com_scriptographer_ai_PlacedFile_setMatrix },
	{ "getFile", "()Ljava/io/File;", (void *) &Java_com_scriptographer_ai_PlacedFile_getFile },
	{ "isEps", "()Z", (void *) &Java_com_scriptographer_ai_PlacedFile_isEps },
	{ "embed", "(Z)Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_PlacedFile_embed }
};

/* Native methods for class com_scriptographer_ai_PlacedSymbol */
static const JNINativeMethod com_scriptographer_ai_PlacedSymbol_methods[] = {
	{ "nativeCreate", "(ILcom/scriptographer/ai/Matrix;)I", (void *) &Java_com_scriptographer_ai_PlacedSymbol_nativeCreate },
	{ "nativeGetSymbol", "()I", (void *) &Java_com_scriptographer_ai_PlacedSymbol_nativeGetSymbol },
	{ "setSymbol", "(Lcom/scriptographer/ai/Symbol;)V", (void *) &Java_com_scriptographer_ai_PlacedSymbol_setSymbol },
	{ "getMatrix", "()Lcom/scriptographer/ai/Matrix;", (void *) &Java_com_scriptographer_ai_PlacedSymbol_getMatrix },
	{ "setMatrix", "(Lcom/scriptographer/ai/Matrix;)V", (void *) &Java_com_scriptographer_ai_PlacedSymbol_setMatrix },
	{ "embed", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_PlacedSymbol_embed }
};

/* Native methods for class com_scriptographer_ai_PointText */
static const JNINativeMethod com_scriptographer_ai_PointText_methods[] = {
	{ "nativeCreate", "(IDD)I", (void *) &Java_com_scriptographer_ai_PointText_nativeCreate },
	{ "getPoint", "()Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_PointText_getPoint }
};

/* Native methods for class com_scriptographer_ai_Raster */
static const JNINativeMethod com_scriptographer_ai_Raster_methods[] = {
	{ "nativeConvert", "(III)I", (void *) &Java_com_scriptographer_ai_Raster_nativeConvert },
	{ "nativeCreate", "(Ljava/io/File;)I", (void *) &Java_com_scriptographer_ai_Raster_nativeCreate },
	{ "getMatrix", "()Lcom/scriptographer/ai/Matrix;", (void *) &Java_com_scriptographer_ai_Raster_getMatrix },
	{ "setMatrix", "(Lcom/scriptographer/ai/Matrix;)V", (void *) &Java_com_scriptographer_ai_Raster_setMatrix },
	{ "getSize", "()Lcom/scriptographer/ai/Size;", (void *) &Java_com_scriptographer_ai_Raster_getSize },
	{ "nativeGetType", "()I", (void *) &Java_com_scriptographer_ai_Raster_nativeGetType },
	{ "getPixel", "(II)Lcom/scriptographer/ai/Color;", (void *) &Java_com_scriptographer_ai_Raster_getPixel },
	{ "setPixel", "(IILcom/scriptographer/ai/Color;)V", (void *) &Java_com_scriptographer_ai_Raster_setPixel },
	{ "nativeSetPixels", "([BIIIII)V", (void *) &Java_com_scriptographer_ai_Raster_nativeSetPixels },
	{ "nativeGetPixels", "([BIIIII)V", (void *) &Java_com_scriptographer_ai_Raster_nativeGetPixels },
	{ "finalize", "()V", (void *) &Java_com_scriptographer_ai_Raster_finalize }
};

/* Native methods for class com_scriptographer_ai_SegmentList */
static const JNINativeMethod com_scriptographer_ai_SegmentList_methods[] = {
	{ "nativeGetSize", "(I)I", (void *) &Java_com_scriptographer_ai_SegmentList_nativeGetSize },
	{ "nativeGet", "(III[F)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeGet },
	{ "nativeSet", "(IIIFFFFFFZ)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeSet__IIIFFFFFFZ },
	{ "nativeSet", "(IIII[F)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeSet__IIII_3F },
	{ "nativeInsert", "(IIIFFFFFFZ)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeInsert__IIIFFFFFFZ },
	{ "nativeInsert", "(IIII[F)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeInsert__IIII_3F },
	{ "nativeGetSelectionState", "(II)S", (void *) &Java_com_scriptographer_ai_SegmentList_nativeGetSelectionState },
	{ "nativeSetSelectionState", "(IIIS)V", (void *) &Java_com_scriptographer_ai_SegmentList_nativeSetSelectionState },
	{ "nativeRemove", "(IIII)I", (void *) &Java_com_scriptographer_ai_SegmentList_nativeRemove }
};

/* Native methods for class com_scriptographer_ai_Swatch */
static const JNINativeMethod com_scriptographer_ai_Swatch_methods[] = {
	{ "nativeCreate", "()I", (void *) &Java_com_scriptographer_ai_Swatch_nativeCreate },
	{ "getName", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Swatch_getName },
	{ "setName", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ai_Swatch_setName },
	{ "getColor", "()Lcom/scriptographer/ai/Color;", (void *) &Java_com_scriptographer_ai_Swatch_getColor },
	{ "setColor", "(Lcom/scriptographer/ai/Color;)V", (void *) &Java_com_scriptographer_ai_Swatch_setColor },
	{ "nativeRemove", "()Z", (void *) &Java_com_scriptographer_ai_Swatch_nativeRemove }
};

/* Native methods for class com_scriptographer_ai_SwatchList */
static const JNINativeMethod com_scriptographer_ai_SwatchList_methods[] = {
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_SwatchList_nativeSize },
	{ "nativeGet", "(II)I", (void *) &Java_com_scriptographer_ai_SwatchList_nativeGet__II },
	{ "nativeGet", "(ILjava/lang/String;)I", (void *) &Java_com_scriptographer_ai_SwatchList_nativeGet__ILjava_lang_String_2 }
};

/* Native methods for class com_scriptographer_ai_Symbol */
static const JNINativeMethod com_scriptographer_ai_Symbol_methods[] = {
	{ "nativeCreate", "(I)I", (void *) &Java_com_scriptographer_ai_Symbol_nativeCreate },
	{ "getName", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Symbol_getName },
	{ "setName", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ai_Symbol_setName },
	{ "getDefinition", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_Symbol_getDefinition },
	{ "setDefinition", "(Lcom/scriptographer/ai/Item;)V", (void *) &Java_com_scriptographer_ai_Symbol_setDefinition },
	{ "isValid", "()Z", (void *) &Java_com_scriptographer_ai_Symbol_isValid },
	{ "isListed", "()Z", (void *) &Java_com_scriptographer_ai_Symbol_isListed },
	{ "setListed", "(Z)V", (void *) &Java_com_scriptographer_ai_Symbol_setListed },
	{ "isSelected", "()Z", (void *) &Java_com_scriptographer_ai_Symbol_isSelected },
	{ "activate", "()V", (void *) &Java_com_scriptographer_ai_Symbol_activate },
	{ "setIndex", "(I)V", (void *) &Java_com_scriptographer_ai_Symbol_setIndex },
	{ "nativeRemove", "()Z", (void *) &Java_com_scriptographer_ai_Symbol_nativeRemove }
};

/* Native methods for class com_scriptographer_ai_SymbolList */
static const JNINativeMethod com_scriptographer_ai_SymbolList_methods[] = {
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_SymbolList_nativeSize },
	{ "nativeGet", "(II)I", (void *) &Java_com_scriptographer_ai_SymbolList_nativeGet__II },
	{ "nativeGet", "(ILjava/lang/String;)I", (void *) &Java_com_scriptographer_ai_SymbolList_nativeGet__ILjava_lang_String_2 }
};

/* Native methods for class com_scriptographer_ai_TextItem */
static const JNINativeMethod com_scriptographer_ai_TextItem_methods[] = {
	{ "nativeGetOrientation", "()I", (void *) &Java_com_scriptographer_ai_TextItem_nativeGetOrientation },
	{ "nativeSetOrientation", "(I)V", (void *) &Java_com_scriptographer_ai_TextItem_nativeSetOrientation },
	{ "getOpticalAlignment", "()Z", (void *) &Java_com_scriptographer_ai_TextItem_getOpticalAlignment },
	{ "setOpticalAlignment", "(Z)V", (void *) &Java_com_scriptographer_ai_TextItem_setOpticalAlignment },
	{ "nativeCreateOutline", "()Lcom/scriptographer/ai/Item;", (void *) &Java_com_scriptographer_ai_TextItem_nativeCreateOutline },
	{ "link", "(Lcom/scriptographer/ai/TextItem;)Z", (void *) &Java_com_scriptographer_ai_TextItem_link },
	{ "isLinked", "()Z", (void *) &Java_com_scriptographer_ai_TextItem_isLinked },
	{ "nativeUnlink", "(ZZ)Z", (void *) &Java_com_scriptographer_ai_TextItem_nativeUnlink },
	{ "getIndex", "()I", (void *) &Java_com_scriptographer_ai_TextItem_getIndex },
	{ "getStoryIndex", "()I", (void *) &Java_com_scriptographer_ai_TextItem_getStoryIndex },
	{ "getStoryHandle", "()I", (void *) &Java_com_scriptographer_ai_TextItem_getStoryHandle },
	{ "nativeGetRange", "(Z)I", (void *) &Java_com_scriptographer_ai_TextItem_nativeGetRange },
	{ "getSelectedRange", "()Lcom/scriptographer/ai/TextRange;", (void *) &Java_com_scriptographer_ai_TextItem_getSelectedRange },
	{ "equals", "(Ljava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_TextItem_equals }
};

/* Native methods for class com_scriptographer_ai_TextRange */
static const JNINativeMethod com_scriptographer_ai_TextRange_methods[] = {
	{ "getContent", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_TextRange_getContent },
	{ "getStart", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getStart },
	{ "getEnd", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getEnd },
	{ "getLength", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getLength },
	{ "getStoryIndex", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getStoryIndex },
	{ "getStoryHandle", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getStoryHandle },
	{ "getFirstTextItem", "()Lcom/scriptographer/ai/TextItem;", (void *) &Java_com_scriptographer_ai_TextRange_getFirstTextItem },
	{ "getLastTextItem", "()Lcom/scriptographer/ai/TextItem;", (void *) &Java_com_scriptographer_ai_TextRange_getLastTextItem },
	{ "setRange", "(II)V", (void *) &Java_com_scriptographer_ai_TextRange_setRange },
	{ "nativePrepend", "(ILjava/lang/String;)I", (void *) &Java_com_scriptographer_ai_TextRange_nativePrepend__ILjava_lang_String_2 },
	{ "nativeAppend", "(ILjava/lang/String;)I", (void *) &Java_com_scriptographer_ai_TextRange_nativeAppend__ILjava_lang_String_2 },
	{ "nativePrepend", "(II)I", (void *) &Java_com_scriptographer_ai_TextRange_nativePrepend__II },
	{ "nativeAppend", "(II)I", (void *) &Java_com_scriptographer_ai_TextRange_nativeAppend__II },
	{ "nativeRemove", "(I)Z", (void *) &Java_com_scriptographer_ai_TextRange_nativeRemove },
	{ "nativeGetCharacterStyle", "(I)I", (void *) &Java_com_scriptographer_ai_TextRange_nativeGetCharacterStyle },
	{ "nativeGetParagraphStyle", "(I)I", (void *) &Java_com_scriptographer_ai_TextRange_nativeGetParagraphStyle },
	{ "getOrigins", "()[Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_TextRange_getOrigins },
	{ "getTransformations", "()[Lcom/scriptographer/ai/Matrix;", (void *) &Java_com_scriptographer_ai_TextRange_getTransformations },
	{ "getSingleGlyph", "()I", (void *) &Java_com_scriptographer_ai_TextRange_getSingleGlyph },
	{ "select", "(Z)V", (void *) &Java_com_scriptographer_ai_TextRange_select },
	{ "deselect", "()V", (void *) &Java_com_scriptographer_ai_TextRange_deselect },
	{ "nativeChangeCase", "(I)Z", (void *) &Java_com_scriptographer_ai_TextRange_nativeChangeCase },
	{ "fitHeadlines", "()V", (void *) &Java_com_scriptographer_ai_TextRange_fitHeadlines },
	{ "nativeGetCharacterType", "()I", (void *) &Java_com_scriptographer_ai_TextRange_nativeGetCharacterType },
	{ "equals", "(Ljava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_TextRange_equals },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_TextRange_nativeRelease }
};

/* Native methods for class com_scriptographer_ai_TextStory */
static const JNINativeMethod com_scriptographer_ai_TextStory_methods[] = {
	{ "getLength", "()I", (void *) &Java_com_scriptographer_ai_TextStory_getLength },
	{ "nativeGetRange", "()I", (void *) &Java_com_scriptographer_ai_TextStory_nativeGetRange },
	{ "getRange", "(II)Lcom/scriptographer/ai/TextRange;", (void *) &Java_com_scriptographer_ai_TextStory_getRange },
	{ "getSelectedRange", "()Lcom/scriptographer/ai/TextRange;", (void *) &Java_com_scriptographer_ai_TextStory_getSelectedRange },
	{ "getIndex", "()I", (void *) &Java_com_scriptographer_ai_TextStory_getIndex },
	{ "reflow", "()V", (void *) &Java_com_scriptographer_ai_TextStory_reflow },
	{ "equals", "(Ljava/lang/Object;)Z", (void *) &Java_com_scriptographer_ai_TextStory_equals },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_TextStory_nativeRelease },
	{ "nativeGetTexListLength", "(I)I", (void *) &Java_com_scriptographer_ai_TextStory_nativeGetTexListLength },
	{ "nativeGetTextItem", "(III)Lcom/scriptographer/ai/TextItem;", (void *) &Java_com_scriptographer_ai_TextStory_nativeGetTextItem }
};

/* Native methods for class com_scriptographer_ai_TextStoryList */
static const JNINativeMethod com_scriptographer_ai_TextStoryList_methods[] = {
	{ "nativeSize", "(I)I", (void *) &Java_com_scriptographer_ai_TextStoryList_nativeSize },
	{ "nativeGet", "(III)I", (void *) &Java_com_scriptographer_ai_TextStoryList_nativeGet },
	{ "nativeRelease", "(I)V", (void *) &Java_com_scriptographer_ai_TextStoryList_nativeRelease }
};

/* Native methods for class com_scriptographer_ai_Timer */
static const JNINativeMethod com_scriptographer_ai_Timer_methods[] = {
	{ "nativeCreate", "(I)I", (void *) &Java_com_scriptographer_ai_Timer_nativeCreate },
	{ "nativeAbort", "(I)V", (void *) &Java_com_scriptographer_ai_Timer_nativeAbort }
};

/* Native methods for class com_scriptographer_ai_Tool */
static const JNINativeMethod com_scriptographer_ai_Tool_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;IIII)I", (void *) &Java_com_scriptographer_ai_Tool_nativeCreate },
	{ "hasPressure", "()Z", (void *) &Java_com_scriptographer_ai_Tool_hasPressure },
	{ "getEventInterval", "()I", (void *) &Java_com_scriptographer_ai_Tool_getEventInterval },
	{ "setEventInterval", "(I)V", (void *) &Java_com_scriptographer_ai_Tool_setEventInterval },
	{ "getTitle", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Tool_getTitle },
	{ "setTitle", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ai_Tool_setTitle },
	{ "getTooltip", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ai_Tool_getTooltip },
	{ "nativeSetTooltip", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ai_Tool_nativeSetTooltip },
	{ "nativeGetOptions", "()I", (void *) &Java_com_scriptographer_ai_Tool_nativeGetOptions },
	{ "nativeSetOptions", "(I)V", (void *) &Java_com_scriptographer_ai_Tool_nativeSetOptions },
	{ "getSelected", "()Z", (void *) &Java_com_scriptographer_ai_Tool_getSelected },
	{ "setSelected", "(Z)V", (void *) &Java_com_scriptographer_ai_Tool_setSelected },
	{ "nativeSetImage", "(I)V", (void *) &Java_com_scriptographer_ai_Tool_nativeSetImage },
	{ "nativeSetRolloverImage", "(I)V", (void *) &Java_com_scriptographer_ai_Tool_nativeSetRolloverImage },
	{ "convertPoint", "(ZZZDD)Lcom/scriptographer/ai/Point;", (void *) &Java_com_scriptographer_ai_Tool_convertPoint },
	{ "nativeGetTools", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ai_Tool_nativeGetTools }
};

/* Native methods for class com_scriptographer_ai_Tracing */
static const JNINativeMethod com_scriptographer_ai_Tracing_methods[] = {
	{ "nativeCreate", "(II)I", (void *) &Java_com_scriptographer_ai_Tracing_nativeCreate },
	{ "update", "()V", (void *) &Java_com_scriptographer_ai_Tracing_update },
	{ "getResample", "()Z", (void *) &Java_com_scriptographer_ai_Tracing_getResample },
	{ "setResample", "(Z)V", (void *) &Java_com_scriptographer_ai_Tracing_setResample },
	{ "getResampleResolution", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getResampleResolution },
	{ "setResampleResolution", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setResampleResolution },
	{ "nativeGetMode", "()I", (void *) &Java_com_scriptographer_ai_Tracing_nativeGetMode },
	{ "nativeSetMode", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_nativeSetMode },
	{ "getBlur", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getBlur },
	{ "setBlur", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setBlur },
	{ "getThreshold", "()I", (void *) &Java_com_scriptographer_ai_Tracing_getThreshold },
	{ "setThreshold", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_setThreshold },
	{ "getMaxColors", "()I", (void *) &Java_com_scriptographer_ai_Tracing_getMaxColors },
	{ "setMaxColors", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_setMaxColors },
	{ "getFills", "()Z", (void *) &Java_com_scriptographer_ai_Tracing_getFills },
	{ "setFills", "(Z)V", (void *) &Java_com_scriptographer_ai_Tracing_setFills },
	{ "getStrokes", "()Z", (void *) &Java_com_scriptographer_ai_Tracing_getStrokes },
	{ "setStrokes", "(Z)V", (void *) &Java_com_scriptographer_ai_Tracing_setStrokes },
	{ "getMaxStrokeWeight", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getMaxStrokeWeight },
	{ "setMaxStrokeWeight", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setMaxStrokeWeight },
	{ "getMinStrokeLength", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getMinStrokeLength },
	{ "setMinStrokeLength", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setMinStrokeLength },
	{ "getPathTightness", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getPathTightness },
	{ "setPathTightness", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setPathTightness },
	{ "getCornerAngle", "()F", (void *) &Java_com_scriptographer_ai_Tracing_getCornerAngle },
	{ "setCornerAngle", "(F)V", (void *) &Java_com_scriptographer_ai_Tracing_setCornerAngle },
	{ "getMinArea", "()I", (void *) &Java_com_scriptographer_ai_Tracing_getMinArea },
	{ "setMinArea", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_setMinArea },
	{ "nativeGetVectorDisplay", "()I", (void *) &Java_com_scriptographer_ai_Tracing_nativeGetVectorDisplay },
	{ "nativeSetVectorDisplay", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_nativeSetVectorDisplay },
	{ "nativeGetRasterDisplay", "()I", (void *) &Java_com_scriptographer_ai_Tracing_nativeGetRasterDisplay },
	{ "nativeSetRasterDisplay", "(I)V", (void *) &Java_com_scriptographer_ai_Tracing_nativeSetRasterDisplay },
	{ "getLivePaint", "()Z", (void *) &Java_com_scriptographer_ai_Tracing_getLivePaint },
	{ "setLivePaint", "(Z)V", (void *) &Java_com_scriptographer_ai_Tracing_setLivePaint }
};

/* Native methods for class com_scriptographer_ScriptographerEngine */
static const JNINativeMethod com_scriptographer_ScriptographerEngine_methods[] = {
	{ "nativeReload", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeReload },
	{ "nativeSetTopDownCoordinates", "(Z)V", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeSetTopDownCoordinates },
	{ "launch", "(Ljava/lang/String;)Z", (void *) &Java_com_scriptographer_ScriptographerEngine_launch },
	{ "getNanoTime", "()J", (void *) &Java_com_scriptographer_ScriptographerEngine_getNanoTime },
	{ "nativeIsDown", "(I)Z", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeIsDown },
	{ "nativeSetProgressText", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeSetProgressText },
	{ "nativeUpdateProgress", "(JJZ)Z", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeUpdateProgress },
	{ "nativeCloseProgress", "()V", (void *) &Java_com_scriptographer_ScriptographerEngine_nativeCloseProgress },
	{ "dispatchNextEvent", "()V", (void *) &Java_com_scriptographer_ScriptographerEngine_dispatchNextEvent },
	{ "isActive", "()Z", (void *) &Java_com_scriptographer_ScriptographerEngine_isActive },
	{ "getIllustratorVersion", "()D", (void *) &Java_com_scriptographer_ScriptographerEngine_getIllustratorVersion },
	{ "getIllustratorRevision", "()I", (void *) &Java_com_scriptographer_ScriptographerEngine_getIllustratorRevision }
};

/* Native methods for class com_scriptographer_ui_MenuGroup */
static const JNINativeMethod com_scriptographer_ui_MenuGroup_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;II)I", (void *) &Java_com_scriptographer_ui_MenuGroup_nativeCreate },
	{ "setOptions", "(I)V", (void *) &Java_com_scriptographer_ui_MenuGroup_setOptions },
	{ "getOptions", "()I", (void *) &Java_com_scriptographer_ui_MenuGroup_getOptions },
	{ "nativeGetGroups", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ui_MenuGroup_nativeGetGroups }
};

/* Native methods for class com_scriptographer_ui_MenuItem */
static const JNINativeMethod com_scriptographer_ui_MenuItem_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I", (void *) &Java_com_scriptographer_ui_MenuItem_nativeCreate },
	{ "nativeRemove", "(I)I", (void *) &Java_com_scriptographer_ui_MenuItem_nativeRemove },
	{ "getText", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_ui_MenuItem_getText },
	{ "setText", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_ui_MenuItem_setText },
	{ "setOptions", "(I)V", (void *) &Java_com_scriptographer_ui_MenuItem_setOptions },
	{ "getOptions", "()I", (void *) &Java_com_scriptographer_ui_MenuItem_getOptions },
	{ "setEnabled", "(Z)V", (void *) &Java_com_scriptographer_ui_MenuItem_setEnabled },
	{ "isEnabled", "()Z", (void *) &Java_com_scriptographer_ui_MenuItem_isEnabled },
	{ "setChecked", "(Z)V", (void *) &Java_com_scriptographer_ui_MenuItem_setChecked },
	{ "isChecked", "()Z", (void *) &Java_com_scriptographer_ui_MenuItem_isChecked },
	{ "nativeGetItems", "()Ljava/util/ArrayList;", (void *) &Java_com_scriptographer_ui_MenuItem_nativeGetItems },
	{ "setCommand", "(Ljava/lang/String;I)Z", (void *) &Java_com_scriptographer_ui_MenuItem_setCommand }
};

/* Native methods for class com_scriptographer_widget_Button */
static const JNINativeMethod com_scriptographer_widget_Button_methods[] = {
	{ "nativeSetImage", "(I)V", (void *) &Java_com_scriptographer_widget_Button_nativeSetImage },
	{ "nativeSetRolloverImage", "(I)V", (void *) &Java_com_scriptographer_widget_Button_nativeSetRolloverImage },
	{ "nativeSetSelectedImage", "(I)V", (void *) &Java_com_scriptographer_widget_Button_nativeSetSelectedImage },
	{ "nativeSetDisabledImage", "(I)V", (void *) &Java_com_scriptographer_widget_Button_nativeSetDisabledImage }
};

/* Native methods for class com_scriptographer_widget_Dialog */
static const JNINativeMethod com_scriptographer_widget_Dialog_methods[] = {
	{ "nativeCreate", "(Ljava/lang/String;II)I", (void *) &Java_com_scriptographer_widget_Dialog_nativeCreate },
	{ "nativeDestroy", "(I)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeDestroy },
	{ "nativeIsVisible", "()Z", (void *) &Java_com_scriptographer_widget_Dialog_nativeIsVisible },
	{ "nativeSetVisible", "(Z)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetVisible },
	{ "isEnabled", "()Z", (void *) &Java_com_scriptographer_widget_Dialog_isEnabled },
	{ "setEnabled", "(Z)V", (void *) &Java_com_scriptographer_widget_Dialog_setEnabled },
	{ "nativeSetActive", "(Z)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetActive },
	{ "nativeGetSize", "()Lcom/scriptographer/ui/Size;", (void *) &Java_com_scriptographer_widget_Dialog_nativeGetSize },
	{ "nativeSetSize", "(II)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetSize },
	{ "nativeGetBounds", "()Lcom/scriptographer/ui/Rectangle;", (void *) &Java_com_scriptographer_widget_Dialog_nativeGetBounds },
	{ "nativeSetBounds", "(IIII)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetBounds },
	{ "getPosition", "()Lcom/scriptographer/ui/Point;", (void *) &Java_com_scriptographer_widget_Dialog_getPosition },
	{ "setPosition", "(II)V", (void *) &Java_com_scriptographer_widget_Dialog_setPosition },
	{ "invalidate", "()V", (void *) &Java_com_scriptographer_widget_Dialog_invalidate__ },
	{ "invalidate", "(IIII)V", (void *) &Java_com_scriptographer_widget_Dialog_invalidate__IIII },
	{ "update", "()V", (void *) &Java_com_scriptographer_widget_Dialog_update },
	{ "nativeGetFont", "()I", (void *) &Java_com_scriptographer_widget_Dialog_nativeGetFont },
	{ "nativeSetFont", "(I)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetFont },
	{ "nativeSetTitle", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetTitle },
	{ "nativeSetName", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetName },
	{ "nativeSetMinimumSize", "(II)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetMinimumSize },
	{ "nativeSetMaximumSize", "(II)V", (void *) &Java_com_scriptographer_widget_Dialog_nativeSetMaximumSize }
};

/* Native methods for class com_scriptographer_widget_Item */
static const JNINativeMethod com_scriptographer_widget_Item_methods[] = {
	{ "nativeCreate", "(Lcom/scriptographer/widget/Dialog;Ljava/lang/String;I)I", (void *) &Java_com_scriptographer_widget_Item_nativeCreate },
	{ "nativeInit", "(IZ)Ljava/lang/String;", (void *) &Java_com_scriptographer_widget_Item_nativeInit },
	{ "nativeDestroy", "(I)V", (void *) &Java_com_scriptographer_widget_Item_nativeDestroy },
	{ "nativeSetTrackCallback", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetTrackCallback },
	{ "nativeSetDrawCallback", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetDrawCallback },
	{ "getTrackMask", "()I", (void *) &Java_com_scriptographer_widget_Item_getTrackMask },
	{ "setTrackMask", "(I)V", (void *) &Java_com_scriptographer_widget_Item_setTrackMask },
	{ "nativeSetStyle", "(I)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetStyle },
	{ "nativeGetStyle", "()I", (void *) &Java_com_scriptographer_widget_Item_nativeGetStyle },
	{ "getChildItemHandle", "(I)I", (void *) &Java_com_scriptographer_widget_Item_getChildItemHandle },
	{ "isVisible", "()Z", (void *) &Java_com_scriptographer_widget_Item_isVisible },
	{ "setVisible", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setVisible },
	{ "isEnabled", "()Z", (void *) &Java_com_scriptographer_widget_Item_isEnabled },
	{ "setEnabled", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setEnabled },
	{ "isActive", "()Z", (void *) &Java_com_scriptographer_widget_Item_isActive },
	{ "setActive", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setActive },
	{ "isKnown", "()Z", (void *) &Java_com_scriptographer_widget_Item_isKnown },
	{ "setKnown", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setKnown },
	{ "wantsFocus", "()Z", (void *) &Java_com_scriptographer_widget_Item_wantsFocus },
	{ "setWantsFocus", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setWantsFocus },
	{ "nativeGetBounds", "()Lcom/scriptographer/ui/Rectangle;", (void *) &Java_com_scriptographer_widget_Item_nativeGetBounds },
	{ "nativeSetBounds", "(IIII)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetBounds },
	{ "nativeSetSize", "(II)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetSize },
	{ "localToScreen", "(II)Lcom/scriptographer/ui/Point;", (void *) &Java_com_scriptographer_widget_Item_localToScreen__II },
	{ "screenToLocal", "(II)Lcom/scriptographer/ui/Point;", (void *) &Java_com_scriptographer_widget_Item_screenToLocal__II },
	{ "localToScreen", "(IIII)Lcom/scriptographer/ui/Rectangle;", (void *) &Java_com_scriptographer_widget_Item_localToScreen__IIII },
	{ "screenToLocal", "(IIII)Lcom/scriptographer/ui/Rectangle;", (void *) &Java_com_scriptographer_widget_Item_screenToLocal__IIII },
	{ "invalidate", "()V", (void *) &Java_com_scriptographer_widget_Item_invalidate__ },
	{ "invalidate", "(IIII)V", (void *) &Java_com_scriptographer_widget_Item_invalidate__IIII },
	{ "update", "()V", (void *) &Java_com_scriptographer_widget_Item_update },
	{ "nativeGetFont", "()I", (void *) &Java_com_scriptographer_widget_Item_nativeGetFont },
	{ "nativeSetFont", "(I)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetFont },
	{ "nativeSetBackgroundColor", "(I)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetBackgroundColor },
	{ "nativeGetBackgroundColor", "()I", (void *) &Java_com_scriptographer_widget_Item_nativeGetBackgroundColor },
	{ "nativeGetCursor", "()I", (void *) &Java_com_scriptographer_widget_Item_nativeGetCursor },
	{ "nativeSetCursor", "(I)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetCursor },
	{ "nativeSetTooltip", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_widget_Item_nativeSetTooltip },
	{ "isToolTipEnabled", "()Z", (void *) &Java_com_scriptographer_widget_Item_isToolTipEnabled },
	{ "setToolTipEnabled", "(Z)V", (void *) &Java_com_scriptographer_widget_Item_setToolTipEnabled },
	{ "showToolTip", "(II)V", (void *) &Java_com_scriptographer_widget_Item_showToolTip },
	{ "hideToolTip", "()V", (void *) &Java_com_scriptographer_widget_Item_hideToolTip }
};

/* Native methods for class com_scriptographer_widget_TextEditItem */
static const JNINativeMethod com_scriptographer_widget_TextEditItem_methods[] = {
	{ "getFractionDigits", "()I", (void *) &Java_com_scriptographer_widget_TextEditItem_getFractionDigits },
	{ "setFractionDigits", "(I)V", (void *) &Java_com_scriptographer_widget_TextEditItem_setFractionDigits },
	{ "setMaxLength", "(I)V", (void *) &Java_com_scriptographer_widget_TextEditItem_setMaxLength },
	{ "getMaxLength", "()I", (void *) &Java_com_scriptographer_widget_TextEditItem_getMaxLength },
	{ "setSelection", "(II)V", (void *) &Java_com_scriptographer_widget_TextEditItem_setSelection },
	{ "getSelection", "()[I", (void *) &Java_com_scriptographer_widget_TextEditItem_getSelection },
	{ "selectAll", "()V", (void *) &Java_com_scriptographer_widget_TextEditItem_selectAll },
	{ "setAllowMath", "(Z)V", (void *) &Java_com_scriptographer_widget_TextEditItem_setAllowMath },
	{ "getAllowMath", "()Z", (void *) &Java_com_scriptographer_widget_TextEditItem_getAllowMath },
	{ "setAllowUnits", "(Z)V", (void *) &Java_com_scriptographer_widget_TextEditItem_setAllowUnits },
	{ "getAllowUnits", "()Z", (void *) &Java_com_scriptographer_widget_TextEditItem_getAllowUnits }
};

/* Native methods for class com_scriptographer_widget_TextItem */
static const JNINativeMethod com_scriptographer_widget_TextItem_methods[] = {
	{ "nativeSetText", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_widget_TextItem_nativeSetText }
};

/* Native methods for class com_scriptographer_widget_TextValueItem */
static const JNINativeMethod com_scriptographer_widget_TextValueItem_methods[] = {
	{ "setText", "(Ljava/lang/String;)V", (void *) &Java_com_scriptographer_widget_TextValueItem_setText },
	{ "getText", "()Ljava/lang/String;", (void *) &Java_com_scriptographer_widget_TextValueItem_getText },
	{ "nativeSetJustification", "(I)V", (void *) &Java_com_scriptographer_widget_TextValueItem_nativeSetJustification },
	{ "nativeGetJustification", "()I", (void *) &Java_com_scriptographer_widget_TextValueItem_nativeGetJustification },
	{ "nativeSetUnits", "(I)V", (void *) &Java_com_scriptographer_widget_TextValueItem_nativeSetUnits },
	{ "nativeGetUnits", "()I", (void *) &Java_com_scriptographer_widget_TextValueItem_nativeGetUnits },
	{ "setShowUnits", "(Z)V", (void *) &Java_com_scriptographer_widget_TextValueItem_setShowUnits },
	{ "getShowUnits", "()Z", (void *) &Java_com_scriptographer_widget_TextValueItem_getShowUnits }
};

/* Native methods for class com_scriptographer_widget_ValueItem */
static const JNINativeMethod com_scriptographer_widget_ValueItem_methods[] = {
	{ "getRange", "()[F", (void *) &Java_com_scriptographer_widget_ValueItem_getRange },
	{ "setRange", "(FF)V", (void *) &Java_com_scriptographer_widget_ValueItem_setRange },
	{ "getIncrements", "()[F", (void *) &Java_com_scriptographer_widget_ValueItem_getIncrements },
	{ "setIncrements", "(FF)V", (void *) &Java_com_scriptographer_widget_ValueItem_setIncrements },
	{ "getValue", "()F", (void *) &Java_com_scriptographer_widget_ValueItem_getValue },
	{ "setValue", "(F)V", (void *) &Java_com_scriptographer_widget_ValueItem_setValue }
};

/* Registers native methods for a given class */
void ScriptographerEngine::registerClassNatives(JNIEnv *env, const char *className, const JNINativeMethod *methods, int count) {
	jclass cls = findClass(env, className);
	if (cls == NULL)
		throw new StringException("Cannot register native methods for class %s: Class not found.", className);
	// Call getConstructors on each class to fix a bug in JSE 1.6.
	// Only by doing so, the registered natives do not get lost!
	callObjectMethod(env, cls, mid_Class_getConstructors);
	// Now we can register the native methods.
	jint err = env->RegisterNatives(cls, methods, count);
	if (err != 0)
		throw new StringException("Cannot register native methods for class %s.", className);
}

/* Registers native methods for all classes, to be called from outside */
void ScriptographerEngine::registerNatives(JNIEnv *env) {
	registerClassNatives(env, "com/scriptographer/ai/Annotator", com_scriptographer_ai_Annotator_methods,
		sizeof(com_scriptographer_ai_Annotator_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/AreaText", com_scriptographer_ai_AreaText_methods,
		sizeof(com_scriptographer_ai_AreaText_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/ArtboardList", com_scriptographer_ai_ArtboardList_methods,
		sizeof(com_scriptographer_ai_ArtboardList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/CharacterStyle", com_scriptographer_ai_CharacterStyle_methods,
		sizeof(com_scriptographer_ai_CharacterStyle_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Color", com_scriptographer_ai_Color_methods,
		sizeof(com_scriptographer_ai_Color_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Curve", com_scriptographer_ai_Curve_methods,
		sizeof(com_scriptographer_ai_Curve_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Dictionary", com_scriptographer_ai_Dictionary_methods,
		sizeof(com_scriptographer_ai_Dictionary_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Document", com_scriptographer_ai_Document_methods,
		sizeof(com_scriptographer_ai_Document_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/DocumentList", com_scriptographer_ai_DocumentList_methods,
		sizeof(com_scriptographer_ai_DocumentList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/DocumentView", com_scriptographer_ai_DocumentView_methods,
		sizeof(com_scriptographer_ai_DocumentView_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/DocumentViewList", com_scriptographer_ai_DocumentViewList_methods,
		sizeof(com_scriptographer_ai_DocumentViewList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/FileFormat", com_scriptographer_ai_FileFormat_methods,
		sizeof(com_scriptographer_ai_FileFormat_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/FontFamily", com_scriptographer_ai_FontFamily_methods,
		sizeof(com_scriptographer_ai_FontFamily_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/FontList", com_scriptographer_ai_FontList_methods,
		sizeof(com_scriptographer_ai_FontList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/FontWeight", com_scriptographer_ai_FontWeight_methods,
		sizeof(com_scriptographer_ai_FontWeight_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Gradient", com_scriptographer_ai_Gradient_methods,
		sizeof(com_scriptographer_ai_Gradient_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/GradientStopList", com_scriptographer_ai_GradientStopList_methods,
		sizeof(com_scriptographer_ai_GradientStopList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Group", com_scriptographer_ai_Group_methods,
		sizeof(com_scriptographer_ai_Group_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Item", com_scriptographer_ai_Item_methods,
		sizeof(com_scriptographer_ai_Item_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Layer", com_scriptographer_ai_Layer_methods,
		sizeof(com_scriptographer_ai_Layer_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/LayerList", com_scriptographer_ai_LayerList_methods,
		sizeof(com_scriptographer_ai_LayerList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/LiveEffect", com_scriptographer_ai_LiveEffect_methods,
		sizeof(com_scriptographer_ai_LiveEffect_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/ParagraphStyle", com_scriptographer_ai_ParagraphStyle_methods,
		sizeof(com_scriptographer_ai_ParagraphStyle_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Path", com_scriptographer_ai_Path_methods,
		sizeof(com_scriptographer_ai_Path_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Pathfinder", com_scriptographer_ai_Pathfinder_methods,
		sizeof(com_scriptographer_ai_Pathfinder_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PathStyle", com_scriptographer_ai_PathStyle_methods,
		sizeof(com_scriptographer_ai_PathStyle_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PathText", com_scriptographer_ai_PathText_methods,
		sizeof(com_scriptographer_ai_PathText_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Pattern", com_scriptographer_ai_Pattern_methods,
		sizeof(com_scriptographer_ai_Pattern_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PlacedFile", com_scriptographer_ai_PlacedFile_methods,
		sizeof(com_scriptographer_ai_PlacedFile_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PlacedSymbol", com_scriptographer_ai_PlacedSymbol_methods,
		sizeof(com_scriptographer_ai_PlacedSymbol_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/PointText", com_scriptographer_ai_PointText_methods,
		sizeof(com_scriptographer_ai_PointText_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Raster", com_scriptographer_ai_Raster_methods,
		sizeof(com_scriptographer_ai_Raster_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/SegmentList", com_scriptographer_ai_SegmentList_methods,
		sizeof(com_scriptographer_ai_SegmentList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Swatch", com_scriptographer_ai_Swatch_methods,
		sizeof(com_scriptographer_ai_Swatch_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/SwatchList", com_scriptographer_ai_SwatchList_methods,
		sizeof(com_scriptographer_ai_SwatchList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Symbol", com_scriptographer_ai_Symbol_methods,
		sizeof(com_scriptographer_ai_Symbol_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/SymbolList", com_scriptographer_ai_SymbolList_methods,
		sizeof(com_scriptographer_ai_SymbolList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/TextItem", com_scriptographer_ai_TextItem_methods,
		sizeof(com_scriptographer_ai_TextItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/TextRange", com_scriptographer_ai_TextRange_methods,
		sizeof(com_scriptographer_ai_TextRange_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/TextStory", com_scriptographer_ai_TextStory_methods,
		sizeof(com_scriptographer_ai_TextStory_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/TextStoryList", com_scriptographer_ai_TextStoryList_methods,
		sizeof(com_scriptographer_ai_TextStoryList_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Timer", com_scriptographer_ai_Timer_methods,
		sizeof(com_scriptographer_ai_Timer_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Tool", com_scriptographer_ai_Tool_methods,
		sizeof(com_scriptographer_ai_Tool_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ai/Tracing", com_scriptographer_ai_Tracing_methods,
		sizeof(com_scriptographer_ai_Tracing_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ScriptographerEngine", com_scriptographer_ScriptographerEngine_methods,
		sizeof(com_scriptographer_ScriptographerEngine_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ui/MenuGroup", com_scriptographer_ui_MenuGroup_methods,
		sizeof(com_scriptographer_ui_MenuGroup_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/ui/MenuItem", com_scriptographer_ui_MenuItem_methods,
		sizeof(com_scriptographer_ui_MenuItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/Button", com_scriptographer_widget_Button_methods,
		sizeof(com_scriptographer_widget_Button_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/Dialog", com_scriptographer_widget_Dialog_methods,
		sizeof(com_scriptographer_widget_Dialog_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/Item", com_scriptographer_widget_Item_methods,
		sizeof(com_scriptographer_widget_Item_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/TextEditItem", com_scriptographer_widget_TextEditItem_methods,
		sizeof(com_scriptographer_widget_TextEditItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/TextItem", com_scriptographer_widget_TextItem_methods,
		sizeof(com_scriptographer_widget_TextItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/TextValueItem", com_scriptographer_widget_TextValueItem_methods,
		sizeof(com_scriptographer_widget_TextValueItem_methods) / sizeof(JNINativeMethod));

	registerClassNatives(env, "com/scriptographer/widget/ValueItem", com_scriptographer_widget_ValueItem_methods,
		sizeof(com_scriptographer_widget_ValueItem_methods) / sizeof(JNINativeMethod));

}
