/*
 * Scriptographer
 *
 * This file is part of Scriptographer, a Plugin for Adobe Illustrator.
 *
 * Copyright (c) 2002-2010 Juerg Lehni, http://www.scratchdisk.com.
 * All rights reserved.
 *
 * Please visit http://scriptographer.org/ for updates and contact.
 *
 * -- GPL LICENSE NOTICE --
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * -- GPL LICENSE NOTICE --
 * 
 * File created on Apr 14, 2008.
 */

package com.scriptographer.ai;

import com.scratchdisk.util.IntegerEnum;

/**
 * AIHitType
 * 
 * @author lehni
 */
public enum HitType implements IntegerEnum {
	/**
	 * Hit an anchor point
	 */
	ANCHOR(0),
	/**
	 * Hit a leading direction line end point
	 */
	HANDLE_IN(1),
	/**
	 * Hit a trailing direction line end point
	 */
	HANDLE_OUT(2),
	/**
	 * Hit a segment interior
	 */
	CURVE(3),
	/**
	 * Hit generated by in fill during preview mode
	 */
	FILL(4),
	/**
	 * Hit the center point of an object with show center point on
	 */
	CENTER(5),
	/**
	 * Hit the intersection of two guides
	 */
	GUIDE_INTERSECTION(6),
	// fake HIT values for Text, added from AITextPart + 10
	/**
	 * Right on text
	 **/
	TEXT(7),
	/**
	 * In port of either AreaText or PathText
	 **/
	TEXT_IN_PORT(8),
	/**
	 * Out port of either AreaText or PathText
	 **/
	TEXT_OUT_PORT(9),
	/**
	 * Start point of PathText
	 **/
	TEXT_START(10),
	/**
	 * Middle point of PathText
	 **/
	TEXT_MIDDLE(11),
	/**
	 * End point of PathText
	 **/
	TEXT_END(12);

	protected int value;

	private HitType(int value) {
		this.value = value;
	}

	public int value() {
		return value;
	}
}
